# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A233182

from math import isqrt
from sympy import primepi
def A233182(n):
    def f(x): return n+sum(primepi(x//y**2) for y in range(1,isqrt(x)+1))
    m, k = n, f(n)
    while m != k: m, k = k, f(k)
    return m # _Chai Wah Wu_, Jan 30 2025

