# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A276039

def A276039(n): return 6*int(bin(n+1)[3:])+(10**((n+1).bit_length()-1)-1)//9 # _Chai Wah Wu_, Jun 28 2025

