# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A348623

from math import prod
from itertools import islice
from sympy import factorint
def A348623gen(): # generator of terms
    n = 1
    yield n
    while True:
        n += prod(q+1 for p, q in factorint(n).items() if p > 2)
        yield n
A348623_list = list(islice(A348623gen(),20)) # _Chai Wah Wu_, Dec 13 2021

