# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A348907

from sympy import isprime
def aupton(nn):
    alst, primepi = [], 0
    for n in range(2, nn+1):
        if isprime(n): an, primepi = n, primepi + 1
        else: an = alst[n - primepi - 2]
        alst.append(an)
    return alst
print(aupton(76)) # _Michael S. Branicky_, Nov 04 2021

