# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A348467

from math import factorial
def A348467(n):
    s = str(factorial(n))
    m = len(s)
    return len(set(int(s[i:j]) for i in range(m) for j in range(i+1,m+1))) # _Chai Wah Wu_, Oct 19 2021

