# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A348487

from itertools import count, takewhile
def ok(n):
  s = str(n*n); return len(s.rstrip("1")) == len(s.lstrip("1")) == len(s)-1
def aupto(N):
  r = takewhile(lambda x: x<=N, (10*i+d for i in count(0) for d in [1, 9]))
  return [k for k in r if ok(k)]
print(aupto(1140)) # _Michael S. Branicky_, Oct 21 2021

