# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A348589

def a(n): return (10**n+2)**2//6
print([a(n) for n in range(1, 15)]) # _Michael S. Branicky_, Oct 24 2021

