# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A348443

from itertools import islice
def A348443(): # generator of terms
    yield 1
    c, p, a, i = 1, {1}, 1, 1
    while True:
        n, na = 1, a
        while na in p:
            n += 1
            na += a
        p.add(na)
        a = n
        i += 1
        if c < na:
            c = na
            yield i
A348443_list = list(islice(A348443(),100)) # _Chai Wah Wu_, Oct 21 2021

