# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A348763

from scipy.special import zeta
from math import log
int(''.join(n for n in list(str(zeta(2)/2-log(2)))[2:-2]))

