# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A023689

from itertools import islice
def A023689_gen(): # generator of terms
    yield (n:=127)
    while True: yield (n:=((n&~(b:=n+(a:=n&-n)))>>a.bit_length())^b)
A023689_list =  list(islice(A023689_gen(),30)) # _Chai Wah Wu_, Mar 06 2025

