# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A337510

def r(i):
  t = [[0, 1, 0], [0, 1, 1, 0]]
  for n in range(2, i+1):
    t.append([0])
    for k in range(1, n+2):
      t[n].append((t[n-1][k-1] + t[n-1][k])**2)
    t[n].append(0)
  return(sum(t[i]))

