# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A004201

from math import comb, isqrt
def A004201(n): return n+comb((m:=isqrt(k:=n<<1))+(k>m*(m+1)),2) # _Chai Wah Wu_, Nov 09 2024

