# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A245680

import itertools
from itertools import permutations
for n in range(1,10**5):
  plist = list(permutations(str(n)))
  for i in plist:
    num = ''
    for j in range(len(i)):
      num += i[j]
    if int(num)%n==0 and int(num)/n > 1:
      print(n,end=', ') # _Derek Orr_, Jul 29 2014

