# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A245710

def A245710(n): return (n+1>>1)-((n+1).bit_count()&1&(n+1)^1) # _Chai Wah Wu_, Mar 01 2023

