# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A010052

def A010052(n): return int(math.isqrt(n)**2==n) ##  appears to be faster than sympy.ntheory.primetest.is_square, up to 10^8 at least.
# _M. F. Hasler_, Mar 21 2022

