# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A111578

def A096038(n,m):
    if n < 1 or m < 1 or m > n:
        return 0
    elif n <=2:
        return 1
    else:
        return A096038(n-1,m-1)+(4*m-3)*A096038(n-1,m)
print( [A096038(n,m) for n in range(20) for m in range(1,n+1)] )
# _R. J. Mathar_, Oct 11 2009

