# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A111163

from sympy import prevprime,nextprime,isprime
A111163_list = [n*(n+1)//2 for n in range(3,10**4) if not isprime(n*(n+1)//4) and prevprime(n*(n+1)//4)+nextprime(n*(n+1)//4) == n*(n+1)//2] # _Chai Wah Wu_, Feb 11 2018

