# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A111163

from sympy import nextprime as np
from sympy import prevprime as pp
n=1
t=n*(n+1)//2
while t>0:
    if t%2==0 and t>3:
        i=t//2
        p=pp(i); q=np(p)
        if p+q==t :
            print(t)
    n=n+1
    t=n*(n+1)//2 # _Abhiram R Devesh_, May 17 2015

