# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A039934

from itertools import count, islice
def agen(startn=1, startk=1):
    n = startn
    for k in count(startk):
        ki, nn = k, 0
        while "3" in str(ki): ki += k; nn += 1
        while n < ki//k: yield k; n += 1
print(list(islice(agen(), 22))) # _Michael S. Branicky_, Jul 31 2022

