# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A110240

def A269160(n): return(n^((n<<1)|(n<<2)))
def genA110240():
    '''Yield successive terms of A110240 (Rule 30) starting from A110240(0)=1.'''
    s = 1
    while True:
       yield s
       s = A269160(s)
def take(n, g):
    '''Returns a list composed of the next n elements returned by generator g.'''
    z = []
    if 0 == n: return(z)
    for x in g:
        z.append(x)
        if n > 1: n = n-1
        else: return(z)
take(30, genA110240())
# _Antti Karttunen_, Oct 05 2019

