# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A000328

from math import isqrt
def A000328(n): return 1+(sum(isqrt(k*((n<<1)-k)) for k in range(1,n+1))<<2) # _Chai Wah Wu_, Feb 12 2025

