# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A000166

 See Hobson link.
A000166_list, m, x = [], 1, 1
for n in range(10*2):
    x, m = x*n + m, -m
    A000166_list.append(x) # _Chai Wah Wu_, Nov 03 2014

