# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A000169

from sympy import Matrix
def P(n): return [[ (i-n if i > j else i) + (i == 0) for j in range(n) ] for i in range(n)]
print(*(Matrix(P(n)).det() for n in range(1, 21)), sep=', ') # _C.S. Elder_, Mar 12 2024

