# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A000052

from num2words import num2words
def n2w(n):
  return num2words(n).replace(" and", "").replace(",", "").replace(" ", "")
def agen(maxdigits):
  for d in range(1, maxdigits+1):
    yield from sorted(range(10**(d-1)-(d==1), 10**d), key=lambda x: n2w(x))
print([an for an in agen(2)]) # _Michael S. Branicky_, Aug 05 2021

