# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A000041

from sympy.ntheory import npartitions
print([npartitions(i) for i in range(101)])  # _Indranil Ghosh_, Mar 17 2017

