# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A000587

# The objective of this implementation is efficiency.
# n -> [a(0), a(1), ..., a(n)] for n > 0.
def A000587_list(n):
    A = [0 for i in range(n)]
    A[n-1] = 1
    R = [1]
    for j in range(0, n):
        A[n-1-j] = -A[n-1]
        for k in range(n-j, n):
            A[k] += A[k-1]
        R.append(A[n-1])
    return R
# _Peter Luschny_, Apr 18 2011

