# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A000118

from sympy import divisors
def a(n): return 1 if n==0 else 8*sum(d for d in divisors(n) if d%4 != 0)
print([a(n) for n in range(57)]) # _Michael S. Branicky_, Jan 08 2021
from sympy import divisor_sigma
def A000118(n): return 1 if n == 0 else 8*divisor_sigma(n) if n % 2 else 24*divisor_sigma(int(bin(n)[2:].rstrip('0'),2)) # _Chai Wah Wu_, Jun 27 2022

