# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A000414

limit = 10026 # 10000th term in b-file
from functools import lru_cache
nzs = [k*k for k in range(1, int(limit**.5)+2) if k*k + 3 <= limit]
nzss = set(nzs)
@lru_cache(maxsize=None)
def ok(n, m): return n in nzss if m == 1 else any(ok(n-s, m-1) for s in nzs)
print([n for n in range(4, limit+1) if ok(n, 4)]) # _Michael S. Branicky_, Apr 07 2021
from itertools import count, islice
def A000414_gen(startvalue=0): # generator of terms >= startvalue
    return filter(lambda n:not(n in {0, 1, 3, 5, 9, 11, 17, 29, 41} or n>>((~n&n-1).bit_length()&-2) in {2,6,14}),count(max(startvalue,0)))
A000414_list = list(islice(A000414_gen(),30)) # _Chai Wah Wu_, Jul 09 2022

