# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A000378

def valuation(n, b):
    v = 0
    while n > 1 and n%b == 0: n //= b; v += 1
    return v
def ok(n): return n//4**valuation(n, 4)%8 != 7
print(list(filter(ok, range(84)))) # _Michael S. Branicky_, Jul 15 2021
from itertools import count, islice
def A000378_gen(): # generator of terms
    return filter(lambda n:n>>2*(bin(n)[:1:-1].index('1')//2) & 7 < 7, count(1))
A000378_list = list(islice(A000378_gen(),30)) # _Chai Wah Wu_, Jun 27 2022
def A000378(n):
    def f(x): return n-1+sum(((x>>(i<<1))-7>>3)+1 for i in range(x.bit_length()>>1))
    m, k = n-1, f(n-1)
    while m != k: m, k = k, f(k)
    return m # _Chai Wah Wu_, Feb 14 2025

