# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A135085

from sympy import bell
def A135085(n): return bell(2**n) # _Chai Wah Wu_, Jun 22 2022

