# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A230282

import math
for n in range(8):
  for k in range(10000000):
    if math.factorial(n*k) < math.factorial(k)**(n+1):
      print(k-1, end=', ')
      break

