# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A254868

from sympy import primerange, prime
def aupton(nn, seed=6, step=4):
  alst, step = [seed], step
  for n in range(1, nn+1, 1):
    x, y, z = alst[-1] - step, alst[-1] + step, alst[-1] * step
    if    x > 0 and x not in alst: alst.append(x)
    elif  y > 0 and y not in alst: alst.append(y)
    elif  z > 0 and z not in alst: alst.append(z)
    else: break
  return alst
print(aupton(57)) # _Michael S. Branicky_, Jun 02 2021

