# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A254029

seq=[]
for x in range (1,1000000):
    total_c,i = x,1
    while i < 6:
        if (total_c)%5 == 1:
            total_c = total_c - (total_c)//5 -1
            if i == 5:
                #print (x,total_c)
                break
        i += 1
    if total_c%5 == 1:
        seq.append(x)
# _Glen Gilchrist_, Jan 28 2023

