# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A257806

def A257806_print_upto(n):
  a = 0
  b = 0
  for n in range(n):
     print(b, end=", ")
     ta = a
     c0 = 0
     while ta>0:
         c0 += 1-(ta&1)
         ta >>= 1
     a += 1 + c0
     b += ((2*(1-(a&1))) - 1)
# By _Antti Karttunen_ after _Alex Ratushnyak_'s Python-code for A216431.

