# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A257588

def A257588(n):
    return abs(sum((int(d)**2*(-1)**j for j,d in enumerate(str(n)))))
# _Chai Wah Wu_, May 10 2015

