# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A029954

from gmpy2 import digits
def palQgen(l,b): # generator of palindromes in base b of length <= 2*l
    if l > 0:
        yield 0
        for x in range(1,l+1):
            for y in range(b**(x-1),b**x):
                s = digits(y,b)
                yield int(s+s[-2::-1],b)
            for y in range(b**(x-1),b**x):
                s = digits(y,b)
                yield int(s+s[::-1],b)
A029954_list = list(palQgen(4,7)) # _Chai Wah Wu_, Dec 01 2014
from gmpy2 import digits
from sympy import integer_log
def A029954(n):
    if n == 1: return 0
    y = 7*(x:=7**integer_log(n>>1,7)[0])
    return int((c:=n-x)*x+int(digits(c,7)[-2::-1]or'0',7) if n<x+y else (c:=n-y)*y+int(digits(c,7)[-1::-1]or'0',7)) # _Chai Wah Wu_, Jun 14 2024

