# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A242473

from sympy import Mod, binomial, prime
def A242473(n): return int(Mod(binomial(2*(p:=prime(n))-1,p-1,evaluate=False),p**4)) # _Chai Wah Wu_, Apr 24 2025

