# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A242171

# Python 3.2 or higher required.
from itertools import accumulate
from sympy import primefactors
A242171_list, bell, blist, b = [1], [1,1], [1], 1
for _ in range(20):
    blist = list(accumulate([b]+blist))
    b = blist[-1]
    fs = primefactors(b)
    for p in fs:
        if all([n % p for n in bell]):
            A242171_list.append(p)
            break
    else:
        A242171_list.append(1)
    bell.append(b) # _Chai Wah Wu_, Sep 19 2014

