# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A046353

from sympy import factorint
def is_046353(n):
    if n % 2 == 0: return False
    f = factorint(n)
    if sum([f[i] for i in f]) < 2: return False
    sfa = sum([i*f[i] for i in f])
    if sfa == int(str(sfa)[::-1]): return True
    return False # _John Cerkan_, Apr 24 2018

