# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A046699

from sympy import factorial
def a(n):
    if n<3: return 1
    s=1
    while factorial(2*s)%(2**(n - 1))>0: s+=1
    return s
print([a(n) for n in range(1, 101)]) # _Indranil Ghosh_, Jun 11 2017, after _Benoit Cloitre_

