# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A035070

from math import isqrt
def a(n): return isqrt(3*10**n) + 1
print([a(n) for n in range(1, 28)]) # _Michael S. Branicky_, Jun 18 2021

