# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A345114

def pal(s): return s == s[::-1]
def rotl(s): return s[1:] + s[0]
def A345111(n): return n + int(rotl(str(n)))
def A345112_bd(n, bd=10000):
    i, iter, seen = 0, n, set()
    while not (iter > n and pal(str(iter))) and iter not in seen and i < bd:
        seen.add(iter)
        i, iter = i+1, A345111(iter)
    return i if iter > n and pal(str(iter)) else 0
def aupto(lim, bd=10000):
    return [n for n in range(1, lim+1) if A345112_bd(n, bd=bd) == 0]
print(aupto(168, bd=100)) # _Michael S. Branicky_, Jun 09 2021

