# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A239474

import sympy
from sympy import isprime
def TwoMin(x):
  for k in range(1,5000):
    if isprime(k**x-x):
      return k
x = 1
while x < 100:
  print(TwoMin(x))
  x += 1

