# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A239913

from functools import lru_cache
@lru_cache(maxsize=None)
def A239913(n): return n-1 if n<=2 else A239913(a:=1+A239913(n-1))+A239913(b:=2+A239913(n-2))-a-b+n # _Chai Wah Wu_, Apr 13 2023

