# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A239072

def a(n): # Malen and Roldán, Theorem 2.1
    return (n+1)**2//3-1 if n%3==2 else n*(n+2)//3 - ((n+1).bit_count()>1) # _Andrei Zabolotskii_, Feb 20 2026

