# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A059833

from sympy import S
def alist(nn): return [4]+[(1+int(d))%10 for d in str(S.Pi.n(nn+2))[2:nn+1]]
print(alist(105)) # _Michael S. Branicky_, Apr 02 2021

