# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A059287

from itertools import islice
from sympy import is_nthpow_residue, nextprime
def A059287_gen(startvalue=2): # generator of terms >= startvalue
    p = max(1,startvalue-1)
    while (p:=nextprime(p)):
        if is_nthpow_residue(2,8,p) and not is_nthpow_residue(2,16,p):
            yield p
A059287_list = list(islice(A059287_gen(),10)) # _Chai Wah Wu_, Jun 23 2024

