# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A204455

from math import prod
from sympy import primefactors
def A204455(n): return prod(primefactors(n>>(~n&n-1).bit_length())) # _Chai Wah Wu_, Dec 03 2025

