# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A392522

from sympy import prime
def A392522(n):
    a, b, c, d, e = (prime(n+i) for i in range(5))
    return c*(a*e+(b*d<<1)-c**2)-a*d**2-b**2*e # _Chai Wah Wu_, Jan 20 2026

