# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A392498

# See also links.
from sympy import divisors
def is_sparse(n: int):
    if n < 4: return 0
    divs = divisors(n)[1:-1]
    if not divs: return 0
    if len(divs) == 1: return divs[0]
    L = divs.pop()
    return divs[0] if sum(divs) < L else 0
print([n for n in range(126) if is_sparse(n)])

