# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A392914

from sympy import primerange
def hamming_quadruples(limit):
    primes = list(primerange(2, limit))
    for p1, p2, p3, p4 in zip(primes, primes[1:], primes[2:], primes[3:]):
        if (bin(p1 ^ p2).count('1') == 1 and
            bin(p2 ^ p3).count('1') == 1 and
            bin(p3 ^ p4).count('1') == 1):
            print(p1, end=", ")
hamming_quadruples(500000)

