# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A392028

from itertools import count
record, g = -1, A255933_gen() # uses code/imports from A255933
[print(m, end=", ") for m in count(1) if (v:=next(g))>record and (record:=v)]
# _Michael S. Branicky_, Dec 28 2025

