# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A392731

def a(n):
    digits = [int(d) for d in str(n)]
    current_idx = 0
    while len(digits) > 1:
        v = digits[current_idx]
        target_idx = (current_idx + v) % len(digits)
        digits.pop(target_idx)
        if len(digits) > 0:
            current_idx = target_idx % len(digits)
    return digits[0]
print([a(n) for n in range(85)])

