# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A392984

from sympy import primerange
def k_inv(p):
    e = (p - 1) // 4
    A0 = sum(n for n in range(1, p) if pow(n, e, p) == 1)
    A2 = sum(n for n in range(1, p) if pow(n, e, p) == p - 1)
    return (A0 - A2) // p
print([k_inv(p) for p in primerange(13, 3000) if p % 8 == 5])

