# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A392459

from itertools import product
def a():
    a192580 = (2, 5, 11, 23, 47)
    elems = {1}
    for (p, q) in product(a192580, repeat=2):
        elems.add(p*q)
    return sorted(elems)

