# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A392990

from itertools import count, islice
def ssd(n): return sum(int(d)**2 for d in str(n))
def is_happy(n):
    while n not in [1, 4]: n = ssd(n) # iterate until fixed point or in cycle
    return n==1
def agen(): # generator of terms
    h1, h2, h3 = True, False, False
    for k in count(2):
        if (h1, h2, h3) == (True, False, True): yield k
        h1, h2, h3 = h2, h3, is_happy(k+2)
print(list(islice(agen(), 46))) # _Michael S. Branicky_, Feb 04 2026

