# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A392648

from sympy import divisors
def isA392648(n: int) -> int:
    if n == 0: return False
    divs = divisors(n)[1:-1]
    dp = [0] * (n + 1)
    dp[0] = 1
    for d in divs:
        for j in range(n, d - 1, -1):
            dp[j] += dp[j - d]
    return dp[n] > 1
print([n for n in range(350) if isA392648(n)])

