# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A341211

from sympy import isprime, nextprime
def a(n):
  p, pow2 = 3, 2**n
  while True:
    if isprime((p**pow2 + 1)//2): return p
    p = nextprime(p)
print([a(n) for n in range(9)]) # _Michael S. Branicky_, Mar 03 2021

