# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A341827

from sympy import prevprime, nextprime
for n in range(3, 1001):
    prevp = prevprime(n); nextp = nextprime(n)
    print(max(n - prevp, nextp - n))

