# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A341242

def ok(n):
  xor, b = 0, (bin(n)[2:])[::-1]
  for i, c in enumerate(b):
    if c == '1': xor ^= i
  return xor == 0
print([m for m in range(937) if ok(m)]) # _Michael S. Branicky_, Feb 07 2021

