# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A297159

from sympy import totient, divisor_sigma
def a(n): return 3*n-2*totient(n)-divisor_sigma(n)
print([a(n) for n in range(1, 101)]) # _Indranil Ghosh_, Mar 02 2018

