# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A043320

from itertools import count, islice, groupby
def A043320_gen(startvalue=1): # generator of terms >= startvalue
    return filter(lambda n:set(len(list(g)) for k, g in groupby(hex(17*n)[2:]))=={2},count(max(startvalue,1)))
A043320_list = list(islice(A043320_gen(),20)) # _Chai Wah Wu_, Mar 10 2023

