# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A090395

from math import gcd
from sympy import divisor_count
def A090395(n): return n//gcd(n,divisor_count(n)) # _Chai Wah Wu_, Jun 20 2022

