# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A088986

from sympy import primefactors
def ok(n):
    return all(len(primefactors(n + i))==2 for i in range(5))
print([n for n in range(1, 8001) if ok(n)]) # _Indranil Ghosh_, Jul 17 2017

