# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A171913

from itertools import count, islice
def A171913gen(): # generator of terms
    b, bdict = 3, {3:(1,)}
    for n in count(2):
        yield b
        if len(l := bdict[b]) > 1:
            b = n-1-l[-2]
        else:
            b = 0
        if b in bdict:
            bdict[b] = (bdict[b][-1],n)
        else:
            bdict[b] = (n,)
A171913_list = list(islice(A171913gen(),20)) # _Chai Wah Wu_, Dec 21 2021

