# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A171015

from sympy import prime
def a(n): return int(str(prime(n)).translate({49:50, 50:49}))
print([a(n) for n in range(1, 57)]) # _Michael S. Branicky_, Sep 17 2025

