# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A171642

from sympy import divisors
A171642 = []
for n in range(1, 10**5):
    d = divisors(n)
    s = sum(d)
    if s % 2 and 2*n <= s and s == 3*sum([x for x in d if x % 2]):
        A171642.append(n)
# _Chai Wah Wu_, Aug 20 2014

