# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A171000

def addn(m1, m2):
    s1, s2 = "{0:b}".format(m1), "{0:b}".format(m2)
    len_max = max(len(s1), len(s2))
    return int(''.join(max(i, j) for i, j in zip(s1.rjust(len_max, '0'), s2.rjust(len_max, '0'))))
def muln(m1, m2):
    s1, s2, prod =  "{0:b}".format(m1), "{0:b}".format(m2), '0'
    for i in range(len(s2)):
        k = s2[-i-1]
        prod = addn(int(str(prod), 2), int(''.join(min(j, k) for j in s1), 2)*2**i)
    return prod
L_p10, m = [1], 2
while m < 100:
    ct = 0
    for i in range(1, len(L_p10)):
        p = L_p10[i]
        for j in range(2, m):
            jp = int(str(muln(j, p)), 2)
            if jp > m: break
            if jp == m: ct += 1; break
        if ct > 0: break
    if ct == 0: L_p10.append(m)
    m += 1
L_p2 = []
for d in L_p10: L_p2.append("{0:b}".format(d))
print(*L_p2, sep =', ') # _Ya-Ping Lu_, Dec 27 2020

