# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A221697

from sympy import divisors
def ok(n): return '2' == max("".join(map(str, divisors(n))))
print([m for m in range(1, 112122) if ok(m)]) # _Michael S. Branicky_, Feb 22 2021
from sympy import isprime, divisors
from itertools import count, islice, product
def agen(): # generator of terms
    yield 2
    for d in count(2):
        for f in "12":
            for mid in product("012", repeat=d-2):
                for e in "12": # ending in zero has 5 as divisor
                    s = f+"".join(mid)+e
                    t = int(s)
                    if "2" in s and isprime(t): yield t; continue
                    if "2" == max("".join(map(str, divisors(t)))): yield t
print(list(islice(agen(), 50))) # _Michael S. Branicky_, Aug 03 2022

