# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A138290

from sympy import isprime
A138290_list = []
for n in range(1,10**3):
    k2, n2 = 1, 2**(n+1)
    for k in range(n):
        if isprime(n2-k2-1):
                break
        k2 *= 2
    else:
        A138290_list.append(n) # _Chai Wah Wu_, Sep 07 2021

