# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A138097

N = 50
a = [0] + [i for i in range(1, N+1)]
for n in range(1, N+1):
    for j in range(n, min(n+a[n]+1, len(a))):
        a[j] += 1
print(a[1:]) # _Michael S. Branicky_, Aug 10 2022

