# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A047778

def a(n): return int("".join([(bin(i))[2:] for i in range(1, n+1)]), 2)
print([a(n) for n in range(1, 19)]) # _Michael S. Branicky_, Jan 06 2021

