# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A034868

from itertools import count, islice
def A034868_gen(): # generator of terms
    yield from (s:=(1,))
    for i in count(0):
        yield from (s:=(1,)+tuple(s[j]+s[j+1] for j in range(len(s)-1)) + ((s[-1]<<1,) if i&1 else ()))
A034868_list = list(islice(A034868_gen(),30)) # _Chai Wah Wu_, Oct 17 2023

