# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A066512

from itertools import count, islice
def agen(): # generator of terms
    a, sums, products = [0], set(), set()
    yield from a
    for k in count(0):
        if k not in sums and k not in products:
            yield k
            sums.update(k+a[i] for i in range(len(a)))
            products.update(k*a[i] for i in range(len(a)))
            a.append(k)
        sums.discard(k)
        products.discard(k)
print(list(islice(agen(), 61))) # _Michael S. Branicky_, Jun 09 2025

