# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A066779

from sympy.ntheory.factor_  import core
def a(n): return sum ([i for i in range(1, n + 1) if core(i) == i]) # _Indranil Ghosh_, Apr 16 2017

