# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A267795

def f(n):
  """ This returns True iff n is in the sequence """
  l = [ n * i for i in range(1, 11) ]
  s = "".join(str(i) for i in l)
  c = [ s.count(str(j)) for j in range(10) ]
  return min(c) >= max(c) - 1
for n in range(1, 10000000):
  if f(n):
    print(n, end=', ')

