# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A267413

from sympy import isprime
def ok(n):
    if n < 7 or n%4 != 3: return n == 6
    b = bin(n)[2:]
    return all(isprime(int(b[:i]+b[i+1:], 2)) for i in range(len(b)))
print(list(filter(ok, range(2, 2**20)))) # _Michael S. Branicky_, Jun 07 2021

