# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A267875

from gmpy2 import mpz
def A267875(n): return int((mpz(2)**74207281-1)//mpz(10)**(44677235-n) % 10) # _Chai Wah Wu_, Jun 07 2021

