# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A144255

from sympy import primeomega
from itertools import count, takewhile
def aupto(limit):
    form = takewhile(lambda x: x <= limit, (k**2+1 for k in count(1)))
    return [number for number in form if primeomega(number)==2]
print(aupto(10202)) # _Michael S. Branicky_, Oct 26 2021

