# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A087961

from math import comb
def a_list(n: int) -> list[int]:
    T = [[0] * (n + 1) for _ in range(n + 1)]
    a = [0] * n
    a[0] = 1
    for m in range(1, n):
        g = [0] + [j * a[j - 1] for j in range(1, m + 1)]
        T[m][1] = g[m]
        for k in range(2, m + 1):
            s = 0
            for j in range(1, m - k + 2):
                s += comb(m - 1, j - 1) * g[j] * T[m - j][k - 1]
            T[m][k] = s
        s_a = 0
        for k in range(1, m):
            s_a += a[k] * T[m][k]
        a[m] = 1 - s_a
    return a
a_list(283)  # _Peter Luschny_, Jun 09 2026

