# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A326754

from itertools import chain, count, islice
def bin_i(n): #binary indices
    return([(i+1) for i, x in enumerate(bin(n)[2:][::-1]) if x =='1'])
def a_gen():
    for n in count(0):
        s = set(i for i in chain.from_iterable([bin_i(k) for k in bin_i(n)]))
        y = len(s)
        if sum(s) == (y*(y+1))//2:
            yield n
A326754_list = list(islice(a_gen(), 100)) # _John Tyler Rascoe_, Jun 20 2024

