# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A209615

def A209615(n): return -1 if ((n>>(m:=(~n&n-1).bit_length()))+1>>1)+m&1^1 else 1 # _Chai Wah Wu_, Feb 25 2025

