# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A330430

seq = []
bag = ""
for k in range(1000):
  m = str(k)
  for digit in m:
    if digit in bag:
      mndx = m.index(digit)
      m = m[:mndx] + m[mndx+1:]
      bndx = bag.index(digit)
      bag = bag[:bndx] + bag[bndx+1:]
  if m:
    seq.append(int(m))
    bag = bag + m
print(seq)

