# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A330024

def A330024(n):
  z=str(2**n).count('0')
  return n//z if z else 0 # _Pontus von Brömssen_, Jul 24 2021

