# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A330407

from math import isqrt
def A330407(n): return (n-(s:=isqrt(n))**2+(sum(n//k for k in range(1,s+1))<<1)<<1)-s-2 if n>1 else 3*n # _Chai Wah Wu_, Jan 27 2026

