# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A330503

from functools import lru_cache
@lru_cache(maxsize=None)
def A330503(n):
    if n == 0:
        return 0
    c, j = 0, 2
    k1 = n//j
    while k1 > 1:
        j2 = n//k1 + 1
        c += (j2-j)*(2*A330503(k1)//(k1+1)-1)
        j, k1 = j2, n//j2
    return (n+1)*(n*(n-1)-c+j)//2 # _Chai Wah Wu_, Mar 29 2021

