# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A107846

def a(n): return len(s:=str(n)) - len(set(s))
print([a(n) for n in range(105)]) # _Michael S. Branicky_, Jan 09 2023

