# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A119680

from itertools import count, islice
from sympy import isprime, nextprime
def ok(n):
    return n > 10 and isprime(n) and isprime(int("0".join(list(str(n)))))
def agen():
    p = 11
    while True:
        t = int("0".join(list(str(p))))
        if isprime(t): yield t
        p = nextprime(p)
print(list(islice(agen(), 50))) # _Michael S. Branicky_, Jul 11 2022

