# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A244474

from itertools import product
from functools import reduce
def A244474(n): return sorted(set(sum(reduce(lambda x,y:(x[0],x[0]+x[1]) if y else (x[0]+x[1],x[1]),k,(1,0))) for k in product((False,True),repeat=n)),reverse=True)[3] # _Chai Wah Wu_, Jun 20 2022

