# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A244428

from gmpy2 import iroot
from sympy import divisor_sigma
A244428_list = [i for i in range(1,10**4) if (iroot(i,3)[1] or not divisor_sigma(i,0) % 3) and iroot(int(divisor_sigma(i,1)),3)[1]] # _Chai Wah Wu_, Mar 10 2016

