# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A397252

def generate_edge(n_terms):
    limit = n_terms + 1
    is_prime = [False, False] + [True] * (limit - 2)
    for p in range(2, int(limit**0.5) + 1):
        if is_prime[p]:
            for i in range(p * p, limit, p):
                is_prime[i] = False
    pi = [0] * n_terms
    count = 0
    for i in range(n_terms):
        if is_prime[i]:
            count += 1
        pi[i] = count
    row = pi[:]
    edge = []
    while row:
        edge.append(row[0])
        row = [abs(row[i] - row[i + 1]) for i in range(len(row) - 1)]
    return edge
print(", ".join(map(str, generate_edge(120))))

