# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A000165

from math import factorial
def A000165(n): return factorial(n)<<n # _Chai Wah Wu_, Jan 24 2023

