# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A000670

from math import factorial
from sympy.functions.combinatorial.numbers import stirling
def A000670(n): return sum(factorial(k)*stirling(n,k) for k in range(n+1)) # _Chai Wah Wu_, Nov 08 2022

