# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A382986

from sympy import factorint
from itertools import count
def b(n): return n - max(factorint(n), default=0) if n&1 else n + 1
def a(n): return next(i for i in count(1) if not (n:=b(n))) if n > 1 else n
print([a(n) for n in range(90)]) # _Michael S. Branicky_, Apr 13 2025

