# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A382725

def A382725(n):
    n1 = n>>1
    n2 = n1>>1
    np = ~n
    n100 = (n2&(~n1)&np).bit_count()
    n110 = (n2&n1&np).bit_count()
    n10 = (n1&np).bit_count()
    return ((n100+1<<3)+(n110<<1)+n10*(n10+3))<<n.bit_count()>>3 # _Chai Wah Wu_, Aug 10 2025

