# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A382747

def A382747_generator(blocklength=4):
    a_set = set()
    a0 = 1
    while 1:
        while a0 in a_set:
            a_set.remove(a0)
            a0 += 1
        for i in range(1,blocklength+1):
            a = i*a0
            if i != 1 and a in a_set:
                for j in range(blocklength-i+1): yield 0
                break
            yield a
            a_set.add(a) # _Pontus von Brömssen_, Apr 30 2025

