# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A247884

count = 9 # Start with the first 9 digits
print(1, 9)
n = 2
while n < 101:
    for a in range(1, 10):
        count += 10**(n-1)//a
        if 10**(n-1) % a != 0:
            count += 1
    print(n, count)
    n += 1
# _David Consiglio, Jr._, Sep 26 2014

