# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A247282

# uses RLT function from A278159
def A247282(n): return RLT(n,lambda m: int(''.join(str(int(not(~(m-1)&k))) for k in range(m)),2)) # _Chai Wah Wu_, Feb 04 2022

