# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A247650

import sympy
from operator import mul
from functools import reduce
x, y = sympy.symbols('x y')
f = ((1/x**2+1/x+1+x+x**2)*(1/y**2+1/y+1+y+y**2)).expand(modulus=2)
A247650_list, g = [1], 1
for n in range(1, 101):
    s = [int(d, 2) for d in bin(n)[2:].split('00') if d != '']
    g = (g*f).expand(modulus=2)
    if len(s) == 1:
        A247650_list.append(g.subs([(x, 1), (y, 1)]))
    else:
        A247650_list.append(reduce(mul, (A247650_list[d] for d in s)))
# _Chai Wah Wu_, Sep 25 2014

