# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A268982

from __future__ import division
from sympy import divisors, divisor_sigma, gcd
def A268982(n):
    return n//gcd(n,sum(d*divisor_sigma(d)**(n//d)  for d in divisors(n, generator=True))) # _Chai Wah Wu_, Oct 02 2017

