# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A062115

from sympy import isprime
def ok(n):
    s = str(n)
    ss = (int(s[i:j]) for i in range(len(s)) for j in range(i+1, len(s)+1))
    return not any(isprime(k) for k in ss)
print([k for k in range(500) if ok(k)]) # _Michael S. Branicky_, May 02 2023

