# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A062139

import math
f=math.factorial
def C(n,r):return f(n)//f(r)//f(n-r)
i=0
for n in range(16):
    for m in range(n+1):
        i += 1
        print(i,((-1)**m)*f(n)*C(n+2,n-m)//f(m)) # _Indranil Ghosh_, Feb 24 2017

