# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A062289

def A062289(n): return n+(m:=n.bit_length())-(not n>=(1<<m)-m) # _Chai Wah Wu_, Jun 30 2024

