# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A062045

from math import prod
def ok(n): d = list(map(int, str(n))); return prod(d) == 12*sum(d)
print([k for k in range(1, 4400) if ok(k)]) # _Michael S. Branicky_, Sep 12 2022

