# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A224923

# O(log(n)) version, same as previous, but simpler and about 3x faster.
def xor_square(n: int) -> int:
    return sum((((n + 1 >> i) ** 2 >> 1 << i) +
               ((n + 1) & ((1 << i) - 1)) * (n + 1 + (1 << i) >> i + 1 << 1)
               << 2 * i) for i in range(n.bit_length()))
print([xor_square(n) for n in range(100)]) # _Gabriel F. Ushijima_, Feb 24 2024

