# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A308887

# uses code/imports in A308884 and A308885
print(list(islice(A308885_gen(t=2), 61))) # _Michael S. Branicky_, Feb 05 2026

