# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A364091

from sympy import isprime, nextprime
def A364091(n):
    if 5 <= n <= 6: return 8-n
    q = 5
    while True:
        p, c = q, 1
        while isprime(p:=(p<<1)+(-1 if p%3==1 else 1)):
            c += 1
            if c > n:
                break
        if c == n:
            return q
        q = nextprime(q) # _Chai Wah Wu_, Jul 07 2023

