# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A364039

def A364039_rowlist(row_max):
    A = []
    for n in range(0,row_max+1):
        A.append([])
        for k in range(0,n+1):
            z = 0
            if n==k: z += 1
            elif k > 1 and k-1 <= n-k: z += A[n-k][k-1]
            if k+1 <= n-k and k != 0: z += A[n-k][k+1]
            A[n].append(z)
        print(A[n])
A364039_rowlist(12)

