[project]
name = "oeis-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.2.0",
    "numpy>=2.2.5",
    "pydantic>=2.11.4",
    "sympy>=1.14.0",
]
