# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A294247

from sympy import mobius
def a(n): return n*sum(mobius(i)**2*mobius(n - i)**2 for i in range(1, ((n - 1)//2) + 1))
print([a(n) for n in range(1, 51)]) # _Indranil Ghosh_, Nov 07 2017

