# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A294226

# for odd n
m, p, q = 0, 6, 2
tl, nl, tb, nb = 3, 1, 2, 1
while nl < 10**100000000:
    tl = tl * nb + tb * nl
    nl = 2 * nl * nb
    nb = tl
    tb = p * nl
tl = tl *nb + tb * nl
nl = 2 * nl * nb
tel, noe = tl, nl
while m >= 0:
    tl = tel*q**m
    nl = noe
    a0 = tl//nl
    t = 0
    an = a0
    while an != 2*a0:
        tl = tl - an*nl
        tl, nl = nl, tl
        an = tl//nl
        t = t + 1
    print(2*m+1, t)
    m = m+1

