# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A001462

a=[0, 1, 2, 2]
for n in range(3, 21):a+=[n for i in range(1, a[n] + 1)]
a[1:] # _Indranil Ghosh_, Jul 05 2017

