# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A001101

# 1000000 primes: https://primes.utm.edu/lists/small/millions/primes1.zip
# "primes1.txt" must be formatted as a b-file before execution
import csv
with open("primes1.txt", "r") as f:
    reader = csv.reader(f, delimiter=" ")
    primes = set([int(rows[1]) for rows in reader])
i, n = 1, 1
with open("b001101.txt", "w") as f:
    while i <= 10000:
        if n % sum(map(int, str(n))) == 0 and n/sum(map(int, str(n))) in primes:
            f.write("{} {}\n".format(i, n))
            i += 1
        n += 1
# _Aaron Toponce_, Feb 14 2018

