# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A001468

def A001468(length):
    a = [1]
    for i in range(length):
        for _ in range(a[i]):
            a.append(2)
        a.append(1)
        if len(a)>=length:
            break
    return a[:length] # _Nicholas Stefan Georgescu_, Jun 02 2022
from math import isqrt
def A001468(n): return (n+1+isqrt(m:=5*(n+1)**2)>>1)-(n+isqrt(m-10*n-5)>>1) # _Chai Wah Wu_, Aug 25 2022

