# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A272890

from fractions import Fraction
from sympy.ntheory.factor_ import antidivisors
A272890_list = [n for n in range(3,10**5) if sum(Fraction(n,a) for a in antidivisors(n)).denominator == 1] # _Chai Wah Wu_, May 10 2016

