# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A272816

from gmpy2 import is_prime
for n in range(1000):
   if(is_prime(n) and is_prime(n+20)):
      print('{}, {}'.format(n,n+20),end=', ')
# _Soumil Mandal_, May 14 2016

