# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A175729

from sympy import factorint
def ok(n): return n>1 and (n-1)%sum(p*e for p, e in factorint(n).items())==0
print([k for k in range(10**4) if ok(k)]) # _Michael S. Branicky_, Sep 30 2022

