# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A175242

from sympy import divisors
def c(n): b = bin(n)[2:]; return b == b[::-1]
def a(n): return sum(1 for d in divisors(n, generator=True) if c(d))
print([a(n) for n in range(1, 106)]) # _Michael S. Branicky_, Jul 15 2022

