# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A175345

from sympy import integer_nthroot, divisor_count
A175345_list, k, c, = [], 1, 1
while k < 10**4:
    if integer_nthroot(c,2)[1]: A175345_list.append(k)
    k += 1
    c += divisor_count(k) # _Chai Wah Wu_, Oct 11 2021

