# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A175207

from gmpy2 import is_prime
from itertools import count, islice
def agen(): # generator of terms
    c, b = 1, 5
    yield from [c, b]
    for n in count(3):
        a = next(c + b*i for i in count(1) if is_prime(c+b*i))
        c, b = b, a
        yield a
print(list(islice(agen(), 22))) # _Michael S. Branicky_, Dec 21 2023

