# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A360081

from sympy import isprime, nextprime
def A360081(n):
    m = 1<<3*(1<<n)-1
    i = m
    while i:=nextprime(i):
        if isprime(k:=(i<<1)+1):
            return k-(m<<1) # _Chai Wah Wu_, Jan 27 2023

