# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A360822

def ok(n): return sum(1 for d in str(n**2) if d < "8") < 3
print([k for k in range(1, 10**5) if ok(k)]) # _Michael S. Branicky_, Feb 22 2023
 # see link for a faster version to find all terms

