# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A049445

A049445 = [n for n in range(1,10**5) if not n % sum([int(d) for d in bin(n)[2:]])] # _Chai Wah Wu_, Aug 22 2014

