# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A049785

def A049785(n):
    c, j = 0, 1
    while j <= n:
        c += (n%(k:=n//j))*(-j+(j:=n//k+1))
    return c # _Chai Wah Wu_, Jan 28 2026

