# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A049595

from itertools import islice
from sympy import nextprime, is_nthpow_residue
def A049595_gen(startvalue=2): # generator of terms >= startvalue
    p = max(startvalue-1,1)
    while (p:=nextprime(p)):
        if is_nthpow_residue(2,63,p):
            yield p
A049595_list = list(islice(A049595_gen(),20)) # _Chai Wah Wu_, May 06 2024

