# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A165818

from math import gcd
def a(n):
    b = bin(n)[2:]
    return max((t for i in range(len(b)) for j in range(i+1, len(b)+1) if gcd(n, (t:=int(b[i:j], 2)))==1))
print([a(n) for n in range(1, 87)]) # _Michael S. Branicky_, Mar 13 2026

