# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A165911

from operator import mul
from sympy import primefactors
from functools import reduce
def rad(n): return 1 if n<2 else reduce(mul, primefactors(n))
l=[0, 1]
for n in range(2, 101):
    l.append(rad(l[n - 1] + l[n - 2]))
print(l) # _Indranil Ghosh_, Jun 03 2017

