# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A383061

def ok(n):
    s = str(n)
    return any(s[i] <= s[i-1] for i in range(1, len(s)) if s[i] in "13579")
print([k for k in range(200) if ok(k)]) # _Michael S. Branicky_, Apr 19 2025

