# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A061743

from sympy import primepi
def A061743(n):
    def f(x): return int(n+2+primepi(x+1)+primepi(x+1>>1))
    m, k = n, f(n)
    while m != k: m, k = k, f(k)
    return m # _Chai Wah Wu_, Oct 17 2024

