# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A061928

from sympy import factorial as f
def T(n, m): return f(n + m + 1)/(f(n)*f(m))
for n in range(1, 11): print([T(m, n - m + 1) for m in range(1, n + 1)]) # _Indranil Ghosh_, Apr 29 2017

