# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A061607

from math import comb
def a(n):
    h = [1, 53, 476, 1044, 476, 53, 1]
    return (n+1) * sum(h[k] * comb(n-k+16, 16) for k in range(7))
print([a(n) for n in range(22)]) # _Steven Kotlarz_, Apr 09 2026

