# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A061051

from sympy import integer_nthroot
def A061051(n):
    if n == 0:
        return 0
    nstart = 10**(n-1)
    nend = 10*nstart
    for i in range(nstart,nend):
        k = int(str(i)*2)
        if integer_nthroot(k,2)[1]:
            return k
    for i in range(nstart,nend):
        si = str(i)*2
        for sj in '014569':
            k = int(si+sj)
            if integer_nthroot(k,2)[1]:
                return k # _Chai Wah Wu_, Mar 25 2020

