# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A061585

def A061585_first(n):
    an = "1"
    a061585 = []
    while n > 1:
        a061585.append(int(an))
        newan = ""
        for i in an:
            newan += str(7*int(i))
        an = newan
        n -= 1
    a061585.append(int(an))
    return a061585 # _John Cerkan_, May 25 2018

