# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A061204

from math import isqrt
from oeis_sequences.OEISsequences import A061201, A007425
def A061204(n):
    a = isqrt(n)
    b = A061201(a)
    return sum(A007425(i)*((A061201(n//i)<<1)-b) for i in range(1,a+1)) # _Chai Wah Wu_, Feb 01 2026

