# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A262361

from sympy import lucas as L
def a(n):  return L(L(L(n)))
print([a(n) for n in range(6)]) # _Michael S. Branicky_, Apr 01 2021

