# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A262037

def A262037(n):
    s = str(n); h = s[:(len(s)+1)//2]; return int(h + h[-1-len(s)%2::-1])
print([A262037(n) for n in range(77)]) # _Michael S. Branicky_, Sep 15 2022

