# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A262814

A262814_list = []
for k in range(1,10**3):
    n = k**k
    if not n % k:
        s = str(n)
        for i in range(len(s)-1):
            s = s[1:]+s[0]
            if int(s) % k:
                break
        else:
            A262814_list.append(k) # _Chai Wah Wu_, Oct 26 2015

