# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A262265

from itertools import product, permutations
def a(n): # only check words starting with 0 by symmetry
  ar = ("".join(u) for r in range(1, n//2+1) for u in product("01", repeat=r))
  abel_squares = set(w+"".join(wp) for w in ar for wp in permutations(w))
  words = ("0"+"".join(w) for w in product("10", repeat=n-1))
  maxn = -1
  for w in words:
    seen = set()
    for s in abel_squares:
      if s in w: seen.add(tuple(sorted(s)))
    maxn = max(maxn, len(seen))
  return maxn
print([a(n) for n in range(1, 14)]) # _Michael S. Branicky_, Dec 20 2020

