# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A064165

from math import prod
from collections import Counter
from sympy import factorint
def A064165(n): return prod(r+1 for q,r in sum((Counter(factorint((p**(n*(e+1))-1)//(p**n-1))) for p, e in factorint(n).items()),Counter()).items()) # _Chai Wah Wu_, Jan 28 2022

