# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A064819

from sympy import prime, primorial
def A064819(n): return primorial(n)-prime(n+1)**2 # _Chai Wah Wu_, Feb 24 2023

