# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A071220

from __future__ import division
from sympy import isprime, prevprime, nextprime, primepi
A071220_list, i = [], 2
while i < 10**6:
    n = i**3
    m = n//2
    if not isprime(m) and prevprime(m) + nextprime(m) == n:
        A071220_list.append(primepi(m))
    i += 1 # _Chai Wah Wu_, May 31 2017

