# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A071296

from gmpy2 import fib2
def A071296(n):
    if n%3==2: return 0
    f, g = fib2(n)
    return int(f*(f + (g<<1) + 6) + g*(g + 2) + 5>>2) # _Chai Wah Wu_, Mar 21 2023

