# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A260351

from gmpy2 import digits
def A260351(n):
    r, c = set([digits(d,n) for d in range(n)]), 0
    dc = set(digits(c,n))
    while len(dc) < n-1 or '0' in dc:
        c += max([int(d,n) for d in r - dc])
        dc = set(digits(c,n))
    return c # _Chai Wah Wu_, Jul 24 2015

