# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A260343

from gmpy2 import is_prime
def intbase(dlist,b=10): # convert list of digits in base b to integer
    y = 0
    for d in dlist:
        y = y*b + d
    return y
A260343_list = [n for n in range(2,500) if is_prime(intbase(list(range(1,n))+[1,0]+list(range(n-1,0,-1)), n))] # _Chai Wah Wu_, Aug 01 2015

