# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A260442

from sympy import factorint, prime, primepi
from operator import mul
from functools import reduce
def a048675(n):
    F=factorint(n)
    return 0 if n==1 else sum([F[i]*2**(primepi(i) - 1) for i in F])
def a003961(n):
    F=factorint(n)
    return 1 if n==1 else reduce(mul, [prime(primepi(i) + 1)**F[i] for i in F])
def a(n): return n + 1 if n<2 else a003961(a(n//2)) if n%2==0 else a((n - 1)//2)*a((n + 1)//2)
print([n for n in range(301) if a(a048675(n))==n]) # _Indranil Ghosh_, Jun 21 2017

