# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A260022

def A260022(n): return sum(int(not r & ~(2*n-r))*2**(n-r) for r in range(n+1)) # _Chai Wah Wu_, Jun 20 2022

