# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A260915

import datetime
 
def prime_number_days():
   j = 0
   date = datetime.date(1000,1,1)
   while date.year<2100:
      x = int(date.strftime("%Y%m%d"))
      while primes[j]<x:
         j += 1
      if primes[j]==x:
         yield x
      date += datetime.timedelta(days=1)

