# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A388723

import math
from sympy import isprime
def A388723(n):
    if n == 1:
        return 0
    k = math.ceil((math.sqrt(n) - 1) / 2)
    t = 2 * k
    m = (t + 1) * (t + 1)
    if n >= m - t:
        x, y = k - (m - n), -k
    elif n >= m - 2 * t:
        x, y = -k, -k + (m - t - n)
    elif n >= m - 3 * t:
        x, y = -k + (m - 2 * t - n), k
    else:
        x, y = k, k - (m - 3 * t - n)
    return abs(x) + abs(y)
def gen(limit):
    sequence = []
    count = 0
    n = 2
    while count < limit:
        if isprime(n):
            sequence.append(A388723(n))
            count += 1
        n += 1
    return sequence
print(gen(30))

