# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A282389

m = [3, 1]
for i in range(25):
    w, h = m[0], len(m)
    print(sum(m)) # print(w) for widths of the polyominoes
    m2 = [w-x for x in reversed(m) if w>x]
    m = [w+x for x in m2] + [w for x in m if x==w] + m2
# _Andrey Zabolotskiy_, Feb 14 2017

