# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A322850

import re
results = []
start_n = 0
N = 100
compare_list = []   # Store powers up to n-1
current_num = int(pow(2, start_n-1))    # Calculate (n-1) power. Convert to integer for better precision
for n in range(start_n, N):
    if n == 0:
        current_num = 1
    else:
        current_num += current_num
    current_string = str(current_num)
    count = 0
    for test_str in compare_list:
        count += len(re.findall(test_str, current_string))
    compare_list.append(current_string)
    results.append(count)
    a=1
print(results)

