# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A072193

from sympy import Rational, continued_fraction_iterator
A072193 = [cf for i in range(2, 12) for j in range(1, i) for cf in continued_fraction_iterator(Rational(i, j))]  # _Jwalin Bhatt_, Nov 24 2025

