# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A188649

from math import lcm
from sympy import divisors
def a(n): return lcm(*(int(str(d)[::-1]) for d in divisors(n)))
print([a(n) for n in range(1, 78)]) # _Michael S. Branicky_, Aug 14 2022

