# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A372473

from math import isqrt
from itertools import count
from sympy import factorint, mobius
from sympy.utilities.iterables import multiset_permutations
def A372473(n):
    if n==0: return 1
    for l in count(n):
        m = 1<<l
        for d in multiset_permutations('0'*n+'1'*(l-n)):
            k = m+int('0'+''.join(d),2)
            if max(factorint(k).values(),default=0)==1:
                 return sum(mobius(a)*(k//a**2) for a in range(1, isqrt(k)+1)) # _Chai Wah Wu_, May 10 2024

