# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A372400

 # uses imports/function in A372401
print(list(islice(A372401gen(p=5), 40))) # _Michael S. Branicky_, Jun 05 2024
from sympy import integer_log
def A372400(n):
    c, x = 0, 30**n
    for i in range(integer_log(x,5)[0]+1):
        for j in range(integer_log(y:=x//5**i,3)[0]+1):
            c += (y//3**j).bit_length()
    return c # _Chai Wah Wu_, Sep 16 2024

