# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A339916

from sympy import divisors
def a(n): return sum(2**((d-1)//2) for d in divisors(2*n+1))
print([a(n) for n in range(37)]) # _Michael S. Branicky_, Dec 24 2020

