# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A339146

def a(n):
    if n < 5:
        return 1
    q, r = divmod(n, 5)
    return a(q) * (r + 1)

