# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A153687

A153687_list, m, n, k, q = [], 1, 11, 10, 0
while m < 10**4:
    r = n % k
    if r > q:
        q = r
        A153687_list.append(m)
    m += 1
    n *= 11
    k *= 10
    q *= 10 # _Chai Wah Wu_, May 16 2020

