# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A153338

import math
def C(n,r):
    f=math.factorial
    return f(n)/f(r)/f(n-r)
def A153338(n):
    return str(n*2**(2*n-2)-(2*n-1)*C(2*n-2,n-1)) # _Indranil Ghosh_, Feb 19 2017

