# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A340184

def A340184(n):
  if n < 10: return 0
  strn = str(n)
  return int("".join(strn.rsplit(min(strn), 1)))
print([A340184(n) for n in range(90)]) # _Michael S. Branicky_, Jan 03 2021

