# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A178472

from sympy import mobius, divisors
def A178472(n): return -sum(mobius(n//d)<<d-1 for d in divisors(n,generator=True) if d<n) # _Chai Wah Wu_, Sep 21 2024

