# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A083367

from sympy import divisors
def sa(n): return int("".join(sorted(str(n))))
def ok(n): return n == sum(sa(d) for d in divisors(n, generator=True))
print([k for k in range(1, 3*10**5) if ok(k)]) # _Michael S. Branicky_, Dec 28 2022

