# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A083356

from math import isqrt
def A083356(n): return (k:=isqrt(n))*(k+1)*(2+4*k-3*k*(k+1))//24+sum(i*(m:=n//i)*(1+m)>>1 for i in range(1,k+1)) # _Chai Wah Wu_, Jul 11 2023

