# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A215879

def A215879(n):
    c = 0
    while (a:=divmod(n,3))[1]:
        c += 1
        n = a[0]
    return c # _Chai Wah Wu_, Oct 15 2022

