# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A333668

# Using graphillion
from graphillion import GraphSet
import graphillion.tutorial as tl
def A333668(n):
    universe = tl.grid(n - 1, n - 1)
    GraphSet.set_universe(universe)
    cycles = GraphSet.cycles()
    for i in [1, n, n * (n - 1) + 1, n * n]:
        cycles = cycles.including(i)
    return [cycles.len(2 * k).len() for k in range(2 * n - 2, n * n // 2 + 1)]
print([i for n in range(2, 8) for i in A333668(n)])

