# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A333666

for n in range(11, 20):
    for k in range(n, 1000000000, n):
       s = str(k)
       revk = "" # digit reversal of k
       sum = 0
       for i in range(len(s)):
          revk = revk + s[len(s) - i - 1]
          sum = sum + int(s[i])
       g = gcd(k,int(revk))
       if g == n and sum == n:
          print(n, k, revk, g)
          break

