# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A333996

from sympy import primepi
def A333996(n): return (n*(n+1)>>1)-primepi(n)-1 # _Chai Wah Wu_, Oct 14 2023

