# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A280879

from fraction import gcd
t = 1
to = 1
i = 1
x = 1
while x > 0:
    x = x + 1
    y = 0
    while y < x:
        y = y + 1
        if gcd(x,y) == 1:
            t = t + 2
    e = t*(x-1)*(x-1) - to*x*x
    if (e < 0 and x%2 == 1 and x%6 != 3):
        print(i,x)
        i = i + 1
    to = t
from sympy import totient
A280879_list, n, t = [], 1, 1
while len(A280879_list) < 1000:
    n += 1
    h = totient(n)
    t2 = t+h
    if n % 2 and n % 6 != 3 and 2*(n*(h*n - 2*t2 + 1) + t2) <  1:
        A280879_list.append(n)
    t = t2 # _Chai Wah Wu_, Feb 11 2017

