# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A375065

from itertools import count, islice
def agen(): # generator of terms
    seen, an, zcount, zdict, zn = {0}, 0, 0, dict(), 1
    for n in count(1):
        if an == 0:
            zcount += 1
        else:
            if zcount not in zdict:
                zdict[zcount] = n-zcount-1
            while zn in zdict: yield zdict[zn]; zn += 1
            zcount = 0
        an = 0 if n in seen else an + n
        seen.add(an)
print(list(islice(agen(), 7))) # _Michael S. Branicky_, Jul 29 2024

