# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A375938

from gmpy2 import is_prime, mpz, digits
def ok(n): return n%3!=0 and not any(is_prime(mpz(digits(n-j)+digits(j))) for j in range(1, n, 2))
print([k for k in range(2, 10**6) if ok(k)]) # _Michael S. Branicky_, Sep 03 2024

