# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A291630

A291630_list = [k for k in range(1,10**6) if min(str(k**2)) == '5'] # _Chai Wah Wu_, Aug 28 2017

