# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A291662

from sympy.core.cache import cacheit
@cacheit
def b(u, o, k): return 1 if u + o==0 else sum([b(u - j, o + j - 1, k) for j in range(1, min(1, u) + 1)]) + sum([b(u + j - 1, o - j, k) for j in range(1, min(k, o) + 1)])
def a(n): return b(0, 2*n, n) - (0 if n==0 else b(0, 2*n, n - 1))
print([a(n) for n in range(31)]) # _Indranil Ghosh_, Aug 30 2017

