# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A291301

from sympy import primorial, isprime, divisor_sigma
def A291301(n):
    m = primorial(n)
    while not isprime(m):
        m = divisor_sigma(m) - 1
    return m # _Chai Wah Wu_, Aug 31 2017

