# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A061345

from sympy import primepi, integer_nthroot
def A061345(n):
    def bisection(f,kmin=0,kmax=1):
        while f(kmax) > kmax: kmax <<= 1
        kmin = kmax >> 1
        while kmax-kmin > 1:
            kmid = kmax+kmin>>1
            if f(kmid) <= kmid:
                kmax = kmid
            else:
                kmin = kmid
        return kmax
    def f(x): return int(n+x-sum(primepi(integer_nthroot(x,k)[0])-1 for k in range(1,x.bit_length())))
    return bisection(f,n+1,n+1) # _Chai Wah Wu_, Feb 03 2025

