# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A061007

from sympy import isprime
def A061007(n): return 2 if n == 4 else int(isprime(n)) # _Chai Wah Wu_, Mar 22 2023

