# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A335233

from sympy import isprime
A335233_list, f = [], 1
for k in range(1,100):
    f *= k
    g = 1
    for i in range(1,k+1):
        g += f
        if isprime(g):
            break
    else:
        A335233_list.append(k)

