# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A292677

 # uses function in A292673
print([A292673(n, b=7) for n in range(1, 101)]) # _Michael S. Branicky_, Apr 13 2023

