# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A338807

def isok(n):
    t = 0
    seen = set()
    maxn = n
    steps = 0
    while n>1:
        maxn = max(maxn,n)
        tuples = set((n,m,t%m) for m in range(2,maxn+1))
        if tuples <= seen:
            break
        seen = seen.union(tuples)
        t += n
        if t%n==0:
            n += 1
        else:
            n -= 1
    return n==1

