# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A338754

def A338754(n): return int(''.join(d*2 for d in str(n))) # _Chai Wah Wu_, May 07 2022

