# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A338398

import sympy
def A338398(n):
  T=[]
  for k in range(n+1):
    T.append(sympy.prime(k+1))
    T.reverse()
    for i in range(k):
      T[i+1]=T[i]-T[i+1]
  return T[-1]

