# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A068645

from sympy import isprime
from itertools import count, islice
def agen(): yield from (t for i in count(0) if isprime(t:=int("1" + "3"*i + "1")))
print(list(islice(agen(), 7))) # _Michael S. Branicky_, Jan 27 2023

