# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A068860

def a(n):
    q, r = divmod(n-1, 9)
    d, f = q+1, r+1
    return int((str(f) + "0"*(f%2) + "10"*(d//2))[:d])
print([a(n) for n in range(1, 51)]) # _Michael S. Branicky_, Mar 19 2024

