# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A068076

from math import comb
def A068076(n):
    c, k = 0, 1
    for i,j in enumerate(bin(n)[-1:1:-1]):
        if j == '1':
            c += comb(i,k)
            k += 1
    return c # _Chai Wah Wu_, Mar 01 2023

