# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A180447

from math import isqrt
def A180447(n): return (m:=isqrt((k:=n<<1)//3))+(k>m*(3*m+5)) # _Chai Wah Wu_, Nov 04 2024

