# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A180560

from sympy import isprime, prime
def a(n):
    s = str(prime(n))
    return len(set(t for t in (s.translate({ord(c):ord(d), ord(d):ord(c)}) for c in set(s) for d in "0123456789" if d!=c) if isprime(int(t))))
print([a(n) for n in range(1, 106)]) # _Michael S. Branicky_, Oct 31 2023

