# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A180961

# uses function in A075774
print([k for k in range(500) if A075774(k) == 4]) # _Michael S. Branicky_, May 27 2024

