# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A183917

from sympy.utilities.iterables import partitions
def A183917_T(n,k): return sum(1 for p in partitions(k*n,m=n,k=k<<1)) # _Chai Wah Wu_, Aug 27 2024

