# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A183302

from math import isqrt
def A183302(n): return n+(m:=isqrt(n>>1))-(n<2*m*(m+1)+1) # _Chai Wah Wu_, Nov 05 2025

