# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A183220

from math import isqrt
def A183220(n): return n+(isqrt((n<<2)//3)+1>>1) # _Chai Wah Wu_, Oct 05 2024

