# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A234016

from sympy import factorial
def a046699(n):
    if n<3: return 1
    s=1
    while factorial(2*s)%(2**(n - 1)): s+=1
    return s
def a(n): return n - (a046699(n + 2) - 1)
print([a(n) for n in range(101)]) # _Indranil Ghosh_, Jun 11 2017

