# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A005132

l=[0]
for n in range(1, 101):
    x=l[n - 1] - n
    if x>0 and not x in l: l+=[x, ]
    else: l+=[l[n - 1] + n]
print(l) # _Indranil Ghosh_, Jun 01 2017
def recaman(n):
  seq = []
  for i in range(n):
    if(i == 0): x = 0
    else: x = seq[i-1]-i
    if(x>=0 and x not in seq): seq+=[x]
    else: seq+=[seq[i-1]+i]
  return seq
print(recaman(1000)) # _Ely Golden_, Jun 14 2018

