# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A005101

from sympy import divisors
def ok(n): return sum(divisors(n)) > 2*n
print(list(filter(ok, range(1, 271)))) # _Michael S. Branicky_, Aug 29 2021
from sympy import divisor_sigma
from itertools import count, islice
def A005101_gen(startvalue=1): return filter(lambda n:divisor_sigma(n) > 2*n, count(max(startvalue, 1))) # generator of terms >= startvalue
A005101_list = list(islice(A005101_gen(), 20)) # _Chai Wah Wu_, Jan 14 2022

