# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A005153

from sympy import factorint
def is_A005153(n):
    if n & 1: return n == 1
    f = factorint(n) ; P = (2 << f.pop(2)) - 1
    for p in f: # factorint must have prime factors in increasing order
        if p > 1 + P: return
        P *= p**(f[p]+1)//(p-1)
    return True # _M. F. Hasler_, Jan 02 2023
from sympy import divisors;from more_itertools import powerset
[i for i in range(1,253) if (lambda x:len(set(map(sum,powerset(x))))>sum(x))(divisors(i))] # _Nicholas Stefan Georgescu_, May 20 2023

