# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A345380

def A345380(n): return (l:=n.bit_length())-(l&1 and not (n&-n)^n)+(l&1 and not(n+1&-n-1)^n+1) if n>1 else n # _Chai Wah Wu_, Jun 23 2026

