# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A345029

def A345029(n):
    c, j = 0, 1
    while j <= n:
        c += 3**((k:=n//j)-1)*(-j+(j:=n//k+1))
    return c # _Chai Wah Wu_, Jan 28 2026

