# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A209398

#Through Recurrence
def a(n, adict={0:0, 1:0, 2:0, 3:2, 4:7}):
 if n in adict:
  return adict[n]
 adict[n]=3*a(n-1)-2*a(n-2)+a(n-3)-a(n-4)-2*a(n-5)
 return adict[n]

