# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A087116

def A087116(n):
    return sum(1 for d in bin(n)[2:].split('1') if len(d)) # _Chai Wah Wu_, Nov 04 2016

