# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A298827

from sympy import n_order
def A298827(n):
    return n_order(3,3**n+2) # _Chai Wah Wu_, Jan 29 2018

