# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A216021

import math
def modiv(a, b):
    return a - b*int(a//b)
def modlg(a, b):
    return a // b**int(math.log(a, b))
for n in range(1, 77):
    print(modlg(n**n, 2**n), end=', ')

