# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A029471

def concat_mod(base, k, mod): ...  # See A029479
for k in range(1, 3*10**10):
  if concat_mod(2, k, k) == 0: print(k) # _Jason Yuen_, Mar 24 2024

