# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A091800

from sympy import nextprime, factorint
def A091800(n: int) -> int:
    k, p, r, t = 0, 1, 1, 10**n
    while r < t:
       p = nextprime(p)
       r *= p
       k += 1
    m = t - 1
    while len(factorint(m)) != k - 1: m -= 1
    return m # _John Reimer Morales_, Aug 18 2025

