# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A025474

 A025474_upto = lambda N: [A001222(n) for n in A000961_list(N)] # _M. F. Hasler_, Jun 16 2022

