# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A204771

prpr = 0
prev = 1
for i in range(99):
    current = (prev)^(prpr*3)
    print(prpr, end=',')
    prpr = prev
    prev = current

