# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A057690

from sympy import prime, primerange
def a(n):
    P = prime(n)
    x, plst, traj, seen = P, list(primerange(2, P)), [], set()
    while x not in seen:
        traj.append(x)
        seen.add(x)
        x = next((x//p for p in plst if x%p == 0), P*x+1)
    return len(traj) - traj.index(x)
print([a(n) for n in range(2, 107)]) # _Michael S. Branicky_, Dec 11 2023

