# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A003137

from gmpy2 import digits
from oeis_sequences.OEISsequences import bisection, bsearch
def A003137(n):
    def g(x): return x+(m:=len(digits(x,3)))*(x+1)-3*(3**(m-1)-1)//2
    def f(x): return n+1+bsearch(g,x)
    return int((s:=digits(a:=bisection(f,n+1,n+1)-n,3))[n-1-a*(k:=len(s))+(3**k-1>>1)]) # _Chai Wah Wu_, Mar 02 2026

