# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A367367

b = 1
while b <= 57:
    b, k, lhs, rhs = b+1, 1, b-1, b-1
    while lhs >= rhs:
        k += 1
        lhs, rhs = k*(b-1)**k, b**k-1
    print(k-1, end = ", ")
def A367367(n):
    kmin, kmax = 1, 1
    while kmax*(n-1)**kmax >= n**kmax-1:
        kmax <<= 1
    while True:
        kmid = kmax+kmin>>1
        if kmid*(n-1)**kmid < n**kmid-1:
            kmax = kmid
        else:
            kmin = kmid
        if kmax-kmin <= 1:
            break
    return kmin # _Chai Wah Wu_, Dec 21 2023

