# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A113878

from sympy import isprime
def afind(limit):
    print("0, 1", end=", ")
    s, pow2 = 2**0 + 2**1, 2**2
    for m in range(2, limit+1):
        if isprime(s+pow2): print(m, end=", "); s += pow2
        pow2 *= 2
afind(2000) # _Michael S. Branicky_, Jul 11 2021

