# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A085986

from math import isqrt
from sympy import primepi, primerange
def A085986(n):
    def f(x): return int(n+x+(t:=primepi(s:=isqrt(x)))+(t*(t-1)>>1)-sum(primepi(x//k) for k in primerange(1, s+1)))
    m, k = n, f(n)
    while m != k:
        m, k = k, f(k)
    return m**2 # _Chai Wah Wu_, Aug 18 2024

