# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A303600

from collections import Counter
def A303600_list(num_terms):
    terms = [2, 3]
    sum_counts = Counter([4, 5, 6])
    next_term = 3
    for n in range(2, num_terms):
        next_term += 1
        while sum_counts[next_term] != 1: next_term += 1
        terms.append(next_term)
        for term in terms: sum_counts[term + next_term] += 1
    return terms
print(A303600_list(59))
# _David Radcliffe_, Jun 19 2025

