# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A358854

from itertools import accumulate, count, islice
def A196563(n): return sum(1 for d in str(n) if d in "02468")
def agen(): yield from accumulate(A196563(n) for n in count(0))
print(list(islice(agen(), 76))) # _Michael S. Branicky_, Dec 03 2022

