# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A358510

def A358510(i): # i-th iteration adds 2+4*i terms
    a, pos = [], 2
    for j in range(1, i + 1):
        a.extend([pos := pos + 1, pos := pos + (j<<2) - 1])
        a.extend(range(pos := pos + 2, pos := pos + (j<<2)))
    return a
print(A358510(10))

