# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A358038

from math import comb
from sympy import mobius, integer_nthroot
def A358038(n):
    def f(x): return int(n+x-sum(mobius(k)*(x//k**3) for k in range(1, integer_nthroot(x,3)[0]+1)))
    m, k = n, f(n)
    while m != k: m, k = k, f(k)
    return sum(mobius(k)*(s:=k**3)*comb(m//s+1,2) for k in range(1,integer_nthroot(m,3)[0]+1)) # _Chai Wah Wu_, Oct 20 2025

