# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A358686

from sympy import factorint
from itertools import count, islice
def agen(): # generator of terms
    nxt = []
    yield 5
    for k in count(6, 2):
        prv, nxt = nxt, list(factorint(k+1).values())
        if (prv==[1, 1] and nxt==[2]) or (prv==[2] and nxt==[1, 1]): yield k
print(list(islice(agen(), 44))) # _Michael S. Branicky_, Nov 26 2022

