# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A358311

from sympy import factorint
from itertools import islice
def A358311_gen(): # generator of terms
    a, b = 2,1
    while True:
        if any(e&1 and p&3==3 for p, e in factorint(a).items()):
            yield a
        a, b = b, a+b
A358311_list = list(islice(A358311_gen(),40))

