# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A358367

from sympy import binomial, S
def A358367(n): return (1<<n*3)*binomial(3*S.Half*n,n) # _Chai Wah Wu_, Nov 14 2022

