# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A280364

def a(n):
    if n==2:
        return 12
    return (((-2*(n-1)-1)*a(n-1))/(2*(n-1)-1))+8*(n-1)**2+10*(n-1)+3
for i in range(2,1001):
    print str(i)+" "+str(a(i))

