# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A280700

def A(n): return bin(2*n - bin(2*n)[2:].count("1"))[2:].count("1")
print([A(n) for n in range(151)]) # _Indranil Ghosh_, Mar 21 2017

