# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A219612

sum, prpr, prev = 0, 0, 1
for i in range(1, 1000):
  sum += prpr
  if sum % i == 0:  print i,
  prpr, prev = prev, prpr+prev

