# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A219219

from sympy import isprime
def aupto(limit):
  alst = []
  for k in range(1, limit+1):
    if isprime(pow(2, k, k*k)): alst.append(k)
  return alst
print(aupto(939)) # _Michael S. Branicky_, May 21 2021

