# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A365673

from functools import cache
@cache
def T(s, n, k):
    if k == 0: return 1
    if k == n: return T(s, n, k - 1)
    p = (n - k + 1) * ((s - 2) * (n - k + 1) - (s - 4)) // 2
    return p * T(s, n, k - 1) + T(s, n - 1, k)
def A(n, k): return T(n, k, k)
for n in range(9): print([A(n, k) for k in range(9)])

