# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A365108

from sympy.ntheory.residue_ntheory import nthroot_mod
def A365108(n):
    c, qdict = n**(n-1), {}
    for p in range(1,n+1):
        r, m = pow(p,n,n), p**n
        if r not in qdict:
            qdict[r] = tuple(nthroot_mod(r,n,n,all_roots=True))
        c = min(c,min(((m-q**n)//n for q in qdict[r] if q<p),default=c))
    return int(c) # _Chai Wah Wu_, Sep 23 2023

