# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A365738

from bisect import bisect
from sympy import totient
def A365738(n):
    k = 10**n
    plist, qlist, c = tuple(-totient(i) for i in range(1,k+1)), [0]*(k+1), 0
    for i in range(k):
        qlist[a:=bisect(qlist,plist[i],lo=1,hi=c+1,key=lambda x:plist[x])]=i
        c = max(c,a)
    return c

