# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A365740

from bisect import bisect
from sympy import totient, isprime
def A365740(n):
    plist = tuple(totient(i) for i in range(1,n+1) if not isprime(i))
    m = len(plist)
    qlist, c = [0]*(m+1), 0
    for i in range(m):
        qlist[a:=bisect(qlist,plist[i],lo=1,hi=c+1,key=lambda x:plist[x])]=i
        c = max(c,a)
    return c

