# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A370223

from itertools import count, islice
def A370223_gen(): # generator of terms
    a, b, s, p = 1, 1, 0, 1
    for n in count(1):
        s += a
        p *= a
        yield s**n-n**n*p
        a, b = b, a+b
A370223_list = list(islice(A370223_gen(),10)) # _Chai Wah Wu_, Feb 16 2024

