# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A370371

from math import isqrt
from sympy import multiplicity
from sympy.ntheory import digits
def a(n):
    ub = isqrt(sum(i*n**i for i in range(n)))
    if n%2 == 1 and multiplicity(2, n-1)%2 == 0:
        ub = isqrt(sum(i*n**(i-2) for i in range(2, n)))
    return(next(i for i in range(ub, -1, -1) if len(d:=sorted(digits(i*i, n)[1:])) == d[-1]-d[0]+1 == len(set(d))))
print([a(n) for n in range(2, 13)]) # _Michael S. Branicky_, Feb 23 2024

