# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A275734

from operator import mul
from sympy import prime, factorial as f
def a007623(n, p=2): return n if n<p else a007623(int(n/p), p+1)*10 + n%p
def a275732(n):
    x=str(a007623(n))[::-1]
    return 1 if n==0 or x.count("1")==0 else reduce(mul, [prime(i + 1) for i in range(len(x)) if x[i]=='1'])
def a257684(n):
    x=str(a007623(n))[:-1]
    y="".join(str(int(i) - 1) if int(i)>0 else '0' for i in x)[::-1]
    return 0 if n==1 else sum(int(y[i])*f(i + 1) for i in range(len(y)))
def a(n): return 1 if n==0 else a275732(n)*a(a257684(n))
print([a(n) for n in range(101)]) # _Indranil Ghosh_, Jun 19 2017

