# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A275272

from sympy import factorial, nextprime
def a(n): fn = factorial(n); return nextprime(nextprime(fn)) - fn
print([a(n) for n in range(1, 60)]) # _Michael S. Branicky_, Mar 05 2022

