# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A113951

from itertools import combinations, permutations
def no_repeated_digits():
    for d in range(1, 11):
        for p in permutations("0123456789", d):
            if p[0] == '0': continue
            yield int("".join(p))
def a(n):
    m = 0
    for k in no_repeated_digits():
        if set(str(k)) & set(str(k**n)) == set():
            m = max(m, k)
    return m
for n in range(2, 4): print(a(n), end=", ") # _Michael S. Branicky_, Aug 28 2021

