# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A242473

from __future__ import division
from sympy import isprime
A242473_list, b = [], 1
for n in range(1,10**4):
    if isprime(n):
        A242473_list.append(b % n**4)
    b = b*2*(2*n+1)//(n+1) # _Chai Wah Wu_, Jan 26 2016
from sympy import Mod, binomial, prime
def A242473(n): return int(Mod(binomial(2*(p:=prime(n))-1,p-1,evaluate=False),p**4)) # _Chai Wah Wu_, Apr 24 2025

