# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A125646

from itertools import count
from sympy import nthroot_mod, isprime, prime
def A125646(n):
    m = (p:=prime(n))**5
    r = sorted(nthroot_mod(1,p-1,m,all_roots=True))
    for i in count(0,m):
        for a in r:
            if isprime(i+a): return i+a # _Chai Wah Wu_, May 02 2024

