# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A125506

from itertools import combinations
afull = [0] + sorted(int("".join(t)) for d in range(1, 11) for t in combinations("236719458", d))
print(afull[:64]) # _Michael S. Branicky_, Aug 18 2022

