# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A125289

from itertools import count, product, islice
def A125289_gen(): # generator of terms
    yield from (int(d+''.join(m)) for l in count(0) for d in '123456789' for m in product('0'+d,repeat=l))
A125289_list = list(islice(A125289_gen(),20)) # _Chai Wah Wu_, Mar 14 2025

