# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A342625

for i in range(10000): print(i+1, wurm(i+1)[1] - wurm(i)[1]) # wurm is defined in the program for A256175.

