# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A063566

def a(n):
    s, k = str(n), 1
    while s not in str(3**k): k += 1
    return k
print([a(n) for n in range(70)]) # _Michael S. Branicky_, Oct 04 2021

