# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A063987

from sympy import jacobi_symbol as J, prime
def a(n):
    p = prime(n)
    return [1] if n==1 else [i for i in range(1, p) if J(i, p)==1]
for n in range(1, 11): print(a(n)) # _Indranil Ghosh_, May 27 2017

