# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A235540

from gmpy2 import is_prime, powmod, t_mod
A235540_list = []
for i in range(1,10**9+1):
    if not is_prime(i):
        d = 2*i*(2*i+1)
        n = t_mod(powmod(4,i,d)-powmod(2,i,d)+8*i*i-2,d)
        if not n:
            A235540_list.append(i) # _Chai Wah Wu_, Dec 02 2014

