# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A235775

def A235775(n):
    s = str(n)
    s = ''.join(str(s.count(d))+d for d in sorted(set(s)))
    return int(''.join(str(s.count(d))+d for d in sorted(set(s)))) # _Chai Wah Wu_, Feb 12 2023

