# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A115343

from operator import mul
from functools import reduce
from sympy import nextprime, sieve
from itertools import combinations
n = 190
m = 9699690*nextprime(n-1)
A115343 = []
for x in combinations(sieve.primerange(1,n),9):
    y = reduce(mul,(d for d in x))
    if y < m:
        A115343.append(y)
A115343 = sorted(A115343) # _Chai Wah Wu_, Sep 02 2014

