# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A349213

from sympy import divisor_count
def A349213(n): return (1+n*(m:=(~n&n-1).bit_length()))*divisor_count(n>>m) # _Chai Wah Wu_, Jul 16 2022

