# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A349712

from sympy import divisors, factorint
def sopf(n): return sum(factorint(n))
def a(n): return sum(sopf(d)*sopf(n//d) for d in divisors(n))
print([a(n) for n in range(1, 76)]) # _Michael S. Branicky_, Nov 26 2021

