# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A349709

from itertools import islice
from sympy import isprime, nextprime
def R(n): return int(str(n)[::-1])
def agen(): # generator of terms
    p, pr = 2, 2
    while True:
        q = nextprime(p)
        qr = R(q)
        if R(p*q) == pr * qr:
            yield p
        p, pr = q, qr
print(list(islice(agen(), 38))) # _Michael S. Branicky_, Jan 05 2022

