# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A349662

from math import isqrt
def A349662(n): return 0 if n <= 1 else isqrt(n**3-1) - n # _Chai Wah Wu_, Dec 08 2021

