# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A349724

from itertools import islice, count
from sympy import factorint
from math import prod
def A349724(): # generator of terms
    for k in count(1):
        if not k*(k+1)//2 % prod(p**(e-1)*((p-1)*e+p) for p, e in factorint(k).items()):
            yield k
A349724_list = list(islice(A349724(),20)) # _Chai Wah Wu_, Nov 29 2021

