# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A349472

from math import gcd
terms, appears = [1], {}
for n in range(2, 100):
    t = 2
    while True:
        if appears.get(t) is None and gcd(terms[-1]+n, t) > 1  :
            appears[t] = True; terms.append(t); break
        t += 1
print(terms) # _Gleb Ivanov_, Nov 19 2021

