# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A370458

from math import prod
def A370458(n): return prod((1<<(1<<i))-1 for i in range(n+1)) # _Chai Wah Wu_, Feb 19 2024

