# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A370676

def a(n):
    count = 0
    for i in range(1, 10**(n-1)):
        for j in range(i, 10**n//i+1):
            if len(str(i*j)) == n and sorted(str(i)+str(j)) == sorted(str(i*j)):
                count += 1
    print(n, count)

