# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A370517

from sympy import primerange
primes = list(primerange(100_000))
prime_gaps = tuple(q - p for p, q in zip(primes[1:], primes))
def a(n):
    seen = set()
    for i in range(1, len(primes) - n + 1):
        new_gaps = tuple(prime_gaps[i: i + n])
        if new_gaps in seen:
            return primes[i - 1]
        seen.add(new_gaps)
    return -1
print(*[a(n) for n in range(1, 14)], sep=', ')
# _David Radcliffe_, May 10 2025

