# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A370906

from math import prod
from sympy import factorint
def A370906(n): return sum((1 if k&1 else -1)*prod((lambda x:x[0]+int((x[1]<<1)>=p+1))(divmod(p**(e+1),p+1)) for p, e in factorint(k).items()) for k in range(1,n+1)) # _Chai Wah Wu_, Mar 05 2024

