# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A255589

def A255589(n):
    x=str(A007090(n))
    return int(x[-1]+x[:-1],4) # _Indranil Ghosh_, Feb 03 2017

