# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A255343

def fbr(n, p=2): # per _Indranil Ghosh_ in A007623
    return n if n<p else fbr(n//p, p+1)*10 + n%p
def ok(n): return str(fbr(n)).count('1') == 3
print(list(filter(ok, range(442)))) # _Michael S. Branicky_, Sep 27 2021

