# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A255192

from math import comb as binomial
def f(x, a, b, k):
    if b == k == 0:
        return 1
    if b == 0 or k == 0:
        return 0
    if x == a:
        return sum(binomial(a, n) * f(x, x, b - 1, k - n) for n in range(1, a + 1))
    return sum(binomial(b, n) * f(x, x, n, k2) * f(n, b, a - x, k - k2)
        for n in range(1, b + 1) for k2 in range(0, k + 1) )
def a(n, m):
    return f(1, n, n, m)
for n in range(1, 5):
    print([a(n, m) for m in range(1, n * n + 1)])

