# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A255591

def A255591(n):
    x=A007092(n)
    return int(x[-1]+x[:-1],6) # _Indranil Ghosh_, Feb 03 2017

