# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A186146

from math import isqrt
def A186146(n): return n+isqrt(n**3) # _Chai Wah Wu_, Oct 15 2025

