# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A350989

from itertools import count, islice
def ispal(s): return s == s[::-1]
def ok(n): return ispal(bin(n)[2:]) and ispal(bin(n*(n+1)//2)[2:])
print([k for k in range(10**6) if ok(k)]) # _Michael S. Branicky_, Jan 28 2022

