# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A350740

# Uses Python code in A046895
def A350740(n): return A046895(n*(n+1))-A046895(n*(n-1)) if n else 1 # _Chai Wah Wu_, Jun 21 2024

