# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A350588

from math import log, ceil
def A350588(n):
    if n <= 8:
        b, S = 10**n, set()
        for i in range(b):
            t, s, T = i, 0, set()
            while t not in T: T.add(t); t = (t**5)%b; s += 1
            S.add(s)
        return(len(S))
    else: return n*n - 3*n - 17 - sum(ceil(log(i, 2)) for i in range(9, n+1))

