# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A350867

from sympy import divisor_count as d
def ok(k): Rk = int(str(k)[::-1]); return Rk != k and d(k) == d(Rk)
print([k for k in range(320) if ok(k)]) # _Michael S. Branicky_, Feb 20 2022

