# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A350738

from math import prod, isqrt
from sympy import Poly
from sympy.abc import x
def A350738(n): return Poly(sum((-1 if k % 2 else 1)*x**(k**2)*prod(1+x**j for j in range(1,k+1)) for k in range(isqrt(n+1)+1))).all_coeffs()[-n-1] # _Chai Wah Wu_, Jan 14 2022

