# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A182187

def a(n):
  m = n + 1
  while bin(n^m).count('1') != 2: m += 1
  return m
print([a(n) for n in range(67)]) # _Michael S. Branicky_, Mar 02 2021

