# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A182273

a, z = [1], [1,2,3,5,7]
while len(a) < 100:
    k, s = 2, "2"
    while (k in a) or ("0" in s) or (a[-1] % 10 * int(s[0]) in z) or \
        any(int(s[n]) * int(s[n+1]) in z for n in range(0, len(s)-1)): s, k = str(k+1), k+1
    a.append(k)
print(a) # _Dominic McCarty_, Jan 30 2025

