# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A051674

 from gmpy2 import mpz
[mpz(prime(n))**mpz(prime(n)) for n in range(1,100)] # _Chai Wah Wu_, Jul 28 2014

