# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A387127

from itertools import count
from math import isqrt, gcd
from sympy.ntheory.primetest import is_square
def A387127(n):
    for w in count(1):
        c = 0
        w7 = w**7
        for z in count(1):
            z5 = w7-z**5
            if z5<2:
                break
            for y in count(1):
                y3 = z5-y**3
                if y3<1:
                    break
                if is_square(y3):
                    x = isqrt(y3)
                    if gcd(x,y,z)==1:
                        c += 1
                        if c>n:
                            break
        if c == n:
            return w # _Chai Wah Wu_, Nov 09 2025

