# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A387036

from math import comb
def A387036(n): return 1 if n == 0 else sum(comb(4*n-2, k) for k in range(n+1)) # _Aidan Chen_, Jan 23 2026

