# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A387123

from itertools import count, islice
from sympy.ntheory.primetest import is_square
def A387123_gen(startvalue=1): # generator of terms >= startvalue
    for k in count(max(startvalue,1)):
        if any(is_square(((k*r<<1)-r*(r+1)<<2)+1) and is_square(((k*r<<1)+r*(r+1)<<2)+1) for r in range(1,k)):
            yield k
A387123_list = list(islice(A387123_gen(),50)) # _Chai Wah Wu_, Aug 21 2025

