# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A387987

"""change values for the endpoint t(n,n,n,n) and the height bd=k"""
t = (5,5,5,5)
bd = 5
def ht(t):
    return 3 * t[0] - t[1] - t[2] - t[3]
def altern(t, bd):
    count = 0
    if t == (0, 0, 0, 0):
        return 1
    if t[0] > 0 and t[0] - 1 >= t[1]:
        count += altern((t[0] - 1, t[1], t[2], t[3]), bd)
    if t[1] > 0 and t[1] - 1 >= t[2] and ht((t[0], t[1] - 1, t[2], t[3])) <= bd:
        count += altern((t[0], t[1] - 1, t[2], t[3]), bd)
    if t[2] > 0 and t[2] - 1 >= t[3] and ht((t[0], t[1], t[2] - 1, t[3])) <= bd:
        count += altern((t[0], t[1], t[2] - 1, t[3]), bd)
    if t[3] > 0 and ht((t[0], t[1], t[2], t[3] - 1)) <= bd:
        count += altern((t[0], t[1], t[2], t[3] -1), bd)
    return count
def exact_height(t, bd):
    if bd < 0:
        return 0
    return altern(t, bd) - altern(t, bd - 1)
print(exact_height(t, bd))

