# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A387591

from sympy import nextprime
def A387591_generate():
    k, p_k, p_k_plus_1 = 1, 2, 3
    while True:
        if p_k * (k + 1) < k * p_k_plus_1:
            yield p_k
        k, p_k, p_k_plus_1 = k + 1, p_k_plus_1, nextprime(p_k_plus_1)
print([p_k for _, p_k in zip(range(70), A387591_generate())])

