# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A387810

from math import gcd
from itertools import count, islice
from sympy import primefactors
def A387810_gen(): # generator of terms
    k,m,mset,c = 2, 6, {1,2,6}, 3
    yield from (1,2,6)
    while True:
        r = set(primefactors(m))
        for i in range(m-1,c-1,-1):
            if i not in mset and gcd(i,m)>1 and gcd(i,k)==1 and not set(primefactors(i))<=r:
                yield i
                break
        else:
            for i in count(max(c,m+1)):
                if i not in mset and gcd(i,m)>1 and gcd(i,k)==1 and not set(primefactors(i))<=r:
                    yield i
                    break
        k, m = m, i
        mset.add(i)
        while c in mset:
            mset.remove(c)
            c += 1
A387810_list = list(islice(A387810_gen(),50)) # _Chai Wah Wu_, Sep 15 2025

