# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A371473

from numpy import prod
def primefact(a):
  factors = []
  d = 2
  while a > 1:
    while a % d == 0:
      factors.append(d)
      a /= d
    d = d + 1
  return factors
def squarefree(a):
  return sorted(list(set(primefact(a)))) == sorted(primefact(a))
sequence = [1]
a = 1
for n in range(1, 1001):
  if not squarefree(a):
    a = prod(list(set(primefact(a))))
  else:
    a += n+1
  sequence.append(a)
print(sequence)

