# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A371259

A371259 = lambda n, k: 0 if (k < 3 or k > n) else (1 if (n == 3 and k == 3) else (A371259(n-1, k-1) + ((n + k - 1)**2) * A371259(n-1, k)))
print([A371259(n, k) for n in range(3, 11) for k in range(3, n+1)])

