# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A371195

from sympy import primepi, integer_nthroot
def A371195(n):
    def f(x): return int(n-2+x-sum(primepi(integer_nthroot(x,k)[0]) for k in range(1,x.bit_length())))
    kmin, kmax = 1,2
    while f(kmax) >= kmax:
        kmax <<= 1
    while True:
        kmid = kmax+kmin>>1
        if f(kmid) < kmid:
            kmax = kmid
        else:
            kmin = kmid
        if kmax-kmin <= 1:
            break
    return kmax**4*(kmax-1) # _Chai Wah Wu_, Aug 20 2024

