# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A371864

# uses imports, functions in A370748
def agen(): # generator of terms
    record = -1
    for i, v in enumerate(A370748gen()):
        if v > record:
            idx, record = i, v
            yield idx
print(list(islice(agen(), 56))) # _Michael S. Branicky_, Apr 09 2024

