# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A325273

from sympy.ntheory import *
def red(v):
    r = {}
    for i in v: r[i] = r.get(i, 0) + 1
    return r
def omicron(v):
    if len(v) == 0: return 0
    if len(v) == 1: return v[0]
    else: return omicron(list(red(v).values()))
f, a_list = {}, []
for i in range(101):
    a_list.append(omicron(list(f.values())))
    g = factorint(i+1)
    for k in g: f[k] = f.get(k, 0) + g[k]
print(a_list) # _James Rayman_, Apr 17 2021

