# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A384715

def A384715(n): return (((n>>1)&~n).bit_count()+bool(n&(n<<1))+1)<<n.bit_count() # _Chai Wah Wu_, Jun 25 2025

