# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A384733

def A384733(n): return n*(n*(n*(n*(n*(n-15)+97)-297)+406)-192)//144 # _Chai Wah Wu_, Jun 11 2025

