# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A384799

from itertools import count, islice
def A384799_gen(): # generator of terms
    s, m = {0}, 1
    for n in count(1):
        c = n+1
        for i in range(n+1):
            if (k:=n**2+i**2) in s:
                c -= 1
            else:
                s.add(k)
        if c>m:
            yield n
            m = c
A384799_list = list(islice(A384799_gen(),30)) # _Chai Wah Wu_, Jul 07 2025

