# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A384229

from fractions import Fraction as frac
A384229 = lambda n: sum(frac(n<<k,k+1) for k in range(n)).numerator
# _Natalia L. Skirrow_, Jun 12 2026

