# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A124010

from sympy import factorint
def a(n):
    f=factorint(n)
    return [0] if n==1 else [f[i] for i in f]
for n in range(1, 21): print(a(n)) # _Indranil Ghosh_, May 16 2017

