# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A395578

from math import prod
from sympy import primepi, integer_nthroot, primefactors
from oeis_sequences.OEISsequences import bisection, squarefreepi
def A395578(n):
    def f(x): return n-2+x+(y:=x.bit_length())+sum(primepi(m:=integer_nthroot(x,k)[0])-squarefreepi(m) for k in range(2,y))
    return prod(primefactors(bisection(f,n+1,n+1))) # _Chai Wah Wu_, May 04 2026

