# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A395179

def count_runs(n):
    if n == 0: return 0
    s = bin(n)[2:]
    runs = 1
    for i in range(1, len(s)):
        if s[i] != s[i-1]:
            runs += 1
    return runs
def a(n):
    max_r = 0
    binary_n = bin(n)[2:]
    num_bits = len(binary_n)
    for i in range(num_bits):
        k = n ^ (1 << i)
        if k > n:
            max_r = max(max_r, count_runs(k))
    k_upper = n ^ (1 << num_bits)
    max_r = max(max_r, count_runs(k_upper))
    return max_r
print([a(n) for n in range(1, 91)])

