# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A395081

def A395081(n: int) -> list[list[int]]:
    """ Returns a list of lists, where each inner list is a flat representation:
    [value_1, multiplicity_1, value_2, multiplicity_2, ...] """
    def gen(n, i):  # Generator
        if n == 0: yield []
        elif i == 1: yield [1, n]
        else:
            if n >= i:
                for p in gen(n - i, min(n - i, i)):
                    if p and p[-2] == i:
                        new_p = list(p)
                        new_p[-1] += 1
                        yield new_p
                    else:
                        yield p + [i, 1]
            yield from gen(n, i - 1)
    if n == 0: return [[]]
    partitions = list(gen(n, n))
    # Sort by length: length is sum of multiplicities (every second element)
    partitions.sort(key=lambda p: sum(p[1::2]))
    return partitions
A395081row = lambda n: [p for parts in A395081(n) for p in parts] # flatten
for n in range(1, 8): print([n], A395081row(n))

