# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A395898

from math import isqrt, factorial
from sympy import divisors
from sympy.ntheory.primetest import is_square
def A395898(n): return next(isqrt((d<<3)+1)>>1 for d in reversed(divisors(factorial(n))) if is_square((d<<3)+1)) # _Chai Wah Wu_, May 09 2026

