# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A395811

from sympy import divisors
from sympy.ntheory.primetest import is_square
isFib = lambda n: (lambda t: is_square(t + 4) or is_square(t - 4))(5 * (n ** 2))
def A395811(n):
  a = 0
  for i in divisors(n):
    if i ** 2 <= n and isFib(i):
      a += 1
  return a
print([A395811(x) for x in range(1, 88)]) # _Aitzaz Imtiaz_, May 13 2026, following the Maple program.

