# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A395373

def T(n, k):
    c = 0
    for a in range(1, n+1):
        if k % a == 0 and k//a <= n:
            c += 1
    return c
def row(n):
    return [T(n, k) for k in range(1, n*n + 1)]
# triangle
a = []
for n in range(1, 7):
    a.extend(row(n))
print(a)

