# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A395716

import mpmath as mp
mp.mp.dps=1000
sol= mp.findroot(lambda ph,th: (2*th+mp.sin(2*th)-mp.pi*mp.sin(ph), mp.pi*mp.cos(ph)/(2*mp.sqrt(2)*mp.cos(th))-1), (0.71,0.57))
ph=sol[0] # ph is the transition latitude in radians; ph*180/mp.pi is the transition latitude in degrees
th=sol[1] # th is auxiliary angle for Mollweide projection in radians
H=2*(ph + mp.sqrt(2)*(1-mp.sin(th)))/mp.pi
print(str(2/H)[0:200])

