# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A395944

import math
def a(n):
    k = 3*n
    f = 1
    for m in range(1, 2284):
        f *= m
        if m >= 2:
            g = math.gcd(m**k - 1, f - 1)
            if g > 1:
                return g
print([a(n) for n in range(1, 70)])

