# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A395080

from math import comb as binomial
def A(n: int, k: int) -> int:
    return sum((n**j) * binomial(k, j) * binomial(2*k + 2, j) // (j + 1)
           for j in range(k + 1))
for n in range(8): print([A(n, k) for k in range(8)])

