# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A395746

from math import prod
from itertools import count, islice
from sympy.ntheory.factor_ import digits
from sympy import primefactors
def A395746_gen(startvalue=1): # generator of terms >= startvalue
    for n in count(max(startvalue,1)):
        m = n*((k:=n<<1)-1)
        l = (~m & m-1).bit_length()
        ps = primefactors(m>>l)
        if (prod(ps)<<bool(l))==(prod((p if sum(digits(k,p)[1:])==2 else 1) for p in ps)<<(not(n&-n)^n) if n>1 else 0):
            yield n
A395746_list = list(islice(A395746_gen(),50))

