# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A395741

from itertools import count
def a(n): return next(m for m in count(1) if all(m%k < (k+1)>>1 for k in range(1, n+1)))
print([a(n) for n in range(1, 31)]) # _Michael S. Branicky_, May 09 2026

