# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A267367

def A267367(n):
    i, s, z = n, 0, 1
    while 0 <= i: s += 1<<i; i -= z; z += z
    return s
print([A267367(n) for n in range(33)]) # _Peter Luschny_, Dec 02 2017

