# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A267794

a=[0, 0]
for i in range(1000):
    for j in range(i-1, -1, -1):
        if a[j:j+2] == a[-2:]:
            a.append(i-j)
            break
    else:
        a.append(0)
print(a)
# _Andrey Zabolotskiy_, Oct 27 2016

