# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A055044

def A055044(n):
    def bisection(f,kmin=0,kmax=1):
        while f(kmax) > kmax: kmax <<= 1
        kmin = kmax >> 1
        while kmax-kmin > 1:
            kmid = kmax+kmin>>1
            if f(kmid) <= kmid:
                kmax = kmid
            else:
                kmin = kmid
        return kmax
    def f(x): return n+x-sum(((x>>(i<<1)+1)-1>>3)+1 for i in range(x.bit_length()+1>>1))
    return bisection(f,n,n) # _Chai Wah Wu_, Mar 19 2025

