# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A366441

from sympy import divisor_count
def A366441(n): return divisor_count((n+(n>>1)<<1)-1) # _Chai Wah Wu_, Oct 10 2023

