# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A366188

from itertools import count, islice
from sympy import Poly, diff, bernoulli
from sympy.abc import x
def A366188_gen(): # generator of terms
    return filter(lambda k:k<=5 or all(c.is_integer for c in Poly(diff(bernoulli(k,x),x,5)).coeffs()),count(1))
A366188_list = list(islice(A366188_gen(),30)) # _Chai Wah Wu_, Oct 03 2023

