# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A155764

from sympy import isprime
a_rec = -1
m = 2
while 1:
    a = 0
    while a < m - 1:
        if isprime(m-a) == 1 and isprime(m+a) == 1:
            if a > a_rec:
                print(a)
                a_rec = a
            break
        a += 1
m += 1 # _Ya-Ping Lu_, Nov 27 2020

