# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A155762

from sympy import isprime, primerange
def ok(p): return not any(isprime(int(d+str(p))) for d in "123456789")
print(list(filter(isprime, primerange(2, 5500)))) # _Michael S. Branicky_, May 28 2022

