# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A342834

from sympy import prevprime
def aupton(nn):
  astr, alst = "", []
  for n in range(1, nn+1):
    astr += str(prevprime(10**n)); alst.append(int(astr))
  return alst
print(aupton(10)) # _Michael S. Branicky_, Mar 23 2021

