# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A342131

def A342131(n): return (3*n+1)//2 if n % 2 else n//2+n//4 # _Chai Wah Wu_, Mar 05 2021

