# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A342121

def A342121(n):
    a, b = sorted([n,int(bin(n)[:1:-1],2)])
    return b % a if n > 0 else 0 # _Chai Wah Wu_, Mar 01 2021

