# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A342264

def nondec(n): s = str(n); return s == "".join(sorted(s))
def aupton(terms):
  alst = [0]
  for n in range(2, terms+1):
    an = 1
    while True:
      while an in alst: an += 1
      if nondec(an) and nondec(alst[-1]+an): alst.append(an); break
      else: an += 1
  return alst
print(aupton(74)) # _Michael S. Branicky_, Mar 07 2021

