# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A342348

def only0123(n, b):
  while n >= b:
    n, r = divmod(n, b)
    if r > 3: return False
  return n <= 3
def a(n):
  k = max(4, n)
  while not all(only0123(k, b) for b in range(2, n+1)): k += 1
  return k
print([a(n) for n in range(2, 10)]) # _Michael S. Branicky_, Mar 12 2021

