# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A342441

def aupton(terms):
  alst, aset = [1], {1}
  while len(alst) < terms:
    an, anm1_digs = 2, set(str(alst[-1]))
    while True:
      while an in aset: an += 1
      if (set(str(an)) | anm1_digs) & set(str(an+alst[-1])) == set():
        alst.append(an); aset.add(an); break
      an += 1
  return alst
print(aupton(73)) # _Michael S. Branicky_, Mar 20 2021

