# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A038447

from itertools import islice
def A038447_gen(): # generator of terms
    yield int(bin(n:=31)[2:])
    while True: yield int(bin((n:=n^((a:=-n&n+1)|(a>>1)) if n&1 else ((n&~(b:=n+(a:=n&-n)))>>a.bit_length())^b))[2:])
A038447_list = list(islice(A038447_gen(),20)) # _Chai Wah Wu_, Mar 11 2025

