# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A355931

from math import gcd
from sympy import divisor_sigma
def A355931(n): return gcd(divisor_sigma(n),n>>(~n&n-1).bit_length()) # _Chai Wah Wu_, Jul 22 2022

