# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A355225

from sympy import isprime
from sympy.utilities.iterables import partitions
def c(p): return 2*sum(p[i] for i in p if isprime(i)) > sum(p.values())
def a(n): return sum(1 for p in partitions(n) if c(p))
print([a(n) for n in range(51)]) # _Michael S. Branicky_, Jun 28 2022

