# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A355592

from sympy import divisors
from itertools import count, islice
def b(n): f = str(n)[0]; return sum(1 for d in divisors(n) if str(d)[0]==f)
def agen(): # generator of terms
    record = -1
    for m in count(1):
        v = b(m)
        if v > record: yield m; record = v
print(list(islice(agen(), 17))) # _Michael S. Branicky_, Sep 24 2022

