# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A355697

import sympy
A355697 = A = [0,1]
for n in range(1,100):
      if sympy.isprime(A355697[-1]):
            y = A[-1] - A[-2] - 1
      else:
            y = A[-1] - A[-2] + 1
      A.append(A[-1] + y)

