# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A355430

from sympy import isprime
def ok(n): return str(n)[0] in "2468" and isprime(n)
print([k for k in range(822) if ok(k)]) # _Michael S. Branicky_, Jul 25 2022

