# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A241102

from itertools import islice
from sympy import isprime, nextprime
def A241102_gen(): # generator of terms
    p, q = 3**3, 5
    while True:
        if isprime((m:=q**3)-p>>1):
            yield m-p
        p, q = m, nextprime(q)
A241102_list = list(islice(A241102_gen(),10)) # _Chai Wah Wu_, Feb 27 2023

