# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A225693

def a(n): return sum(int(d)*(-1)**i for i, d in enumerate(str(n)))
print([a(n) for n in range(87)]) # _Michael S. Branicky_, Jul 14 2022

