# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A225193

from sympy import isprime
from itertools import count, islice, permutations
def agen(): yield from (k for k in count(1) if len(set(s:=str(k)))!=1 and not isprime(k) and all((t:=int("".join(m)))==k or isprime(t) for m in permutations(s)))
print(list(islice(agen(), 28))) # _Michael S. Branicky_, Dec 29 2023

