# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A225945

from sympy import nextprime, prime
from itertools import count, islice
def agen(startn=1): # generator of terms
    pn = prime(startn)
    for n in count(startn):
        if pow(n, n, pn) == pn - 1:
            yield n
        pn = nextprime(pn)
print(list(islice(agen(), 5))) # _Michael S. Branicky_, May 25 2023

