# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A044460

from gmpy2 import digits
A044460_list = [n for n in range(5**7) if '02' in digits(n,5) and '02' not in digits(n+1,5)] # _Chai Wah Wu_, Dec 03 2015

