# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A044995

from sympy.ntheory import count_digits
def ok(n): d = count_digits(n, 3); return d[0] == 1 and d[2] == 1
print(list(filter(ok, range(500)))) # _Michael S. Branicky_, Jun 11 2021

