# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A063383

from sympy import divisors, isprime
def aupton(terms):
    alst = [6]
    for n in range(2, terms+1):
        if isprime(alst[-1]): alst.append(int('1' + str(alst[-1])))
        else:
            divs = divisors(alst[-1])
            d1 = divs[(len(divs)-1)//2]
            d2 = alst[-1]//d1
            alst.append(int(str(d1) + str(d2)))
    return alst
print(aupton(27)) # _Michael S. Branicky_, Jun 23 2021

