# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A063946

import math
def a(n): return n if n<2 else 3/2*2**int(math.floor(math.log(n)/math.log(2))) - 2**int(math.floor(math.log(4/3*n)/math.log(2))) + n # _Indranil Ghosh_, Mar 22 2017

