# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A192776

def A192776(n):
    if n == 1: return 0
    a = 1<<(l:=n.bit_length()-2)
    m = a|(n&a-1)
    return int(bin(((m<<l+1)+int(bin(m)[-1:1:-1]or'0', 2) if a&n else (m<<l)+int(bin(m)[-2:1:-1]or'0', 2))**2)[2:]) # _Chai Wah Wu_, Jul 23 2024

