# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A352002

from sympy import primorial, prime
def a(n): return primorial(n) + prime(n)
for n in range(1,50):
    print(a(n), end=", ") # _Javier Rivera Romeu_, Mar 01 2022

