# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A352519

from sympy import primepi, integer_nthroot, primerange
def A352519(n):
    def f(x): return int(n+x-sum(primepi(primepi(integer_nthroot(x,p)[0])) for p in primerange(x.bit_length())))
    def bisection(f,kmin=0,kmax=1):
        while f(kmax) > kmax: kmax <<= 1
        while kmax-kmin > 1:
            kmid = kmax+kmin>>1
            if f(kmid) <= kmid:
                kmax = kmid
            else:
                kmin = kmid
        return kmax
    return bisection(f,n,n) # _Chai Wah Wu_, Sep 12 2024

