# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A105750

from sympy.functions.combinatorial.numbers import stirling
def A105750(n): return sum(stirling(n+1,n+1-(k<<1),kind=1)*(-1 if k&1 else 1) for k in range((n+1>>1)+1)) # _Chai Wah Wu_, Feb 22 2024

