# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A114622

from functools import cache
b = dict()
@cache
def T(n):
    global b
    if n == 1: return [1]
    l = []
    for i in T(n-1):
        j = i; s = []
        while j > 0:
            s.append(j)
            j = b.get(j, 0)
        for j in sorted(s):
            if b.get(i+j, 0) == 0:
                b[i+j] = i
                l.append(i+j)
    return l
print([Tik  for i in range(1, 9) for Tik in T(i)])  # _Michael S. Branicky_, Apr 28 2024 after _Alois P. Heinz_

