# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A118896

from math import isqrt
from sympy import integer_nthroot, factorint
def A118896(n):
    m = 10**n
    return sum(isqrt(m//x**3) for x in range(1,integer_nthroot(m,3)[0]+1) if max(factorint(x).values(),default=0)<=1) # _Chai Wah Wu_, May 13 2023

