# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A206805

from sympy import integer_log
def A206805(n): return integer_log(1<<n,3)[0]+n # _Chai Wah Wu_, Mar 12 2026

