# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A037089

a, m, n, i = [1,2,11], 1, 1, 0
while len(a) <= 100:
    while (a[-1]==a[-2] or not all(len(set([x % (10 ** j) for x in a])) <= a[j] for j in range(1,len(a)-1))):
        i += 1
        if (i == len(a)-1):i, m = 0, m+1
        a[-1] = (m*(10**n))+a[i]
    if (len(a) in a): m, n, i = 1, n+1, 0; a.append((10**n)+1)
    else: a.append(a[-1])
a.pop(); print(a) # _Dominic McCarty_, Jan 29 2025

