# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A037285

from sympy import divisors
def a(n):
  nontrivial_odd_divisors = [d for d in divisors(n)[1:-1] if d%2 == 1]
  if len(nontrivial_odd_divisors) == 0: return 0
  else: return int("".join(str(d) for d in nontrivial_odd_divisors))
print([a(n) for n in range(1, 70)]) # _Michael S. Branicky_, Dec 31 2020

