# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A037102

from itertools import accumulate
def f(n, _): return 9*n+1 if n%2 == 1 else n//2
def aupton(terms): return list(accumulate([3]*terms, f))
print(aupton(48)) # _Michael S. Branicky_, Mar 28 2021

