# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A364194

def A364194(n): return sum((k**2*(m:=n//k)*(m+1)>>1)**2 for k in range(1,n+1)) # _Chai Wah Wu_, Oct 20 2023
from math import isqrt
def A364194(n): return ((((s:=isqrt(n))*(s + 1))**3*(2*s+1)*(1-3*s*(s+1))>>1) + sum((q:=n//k)*(q+1)*k**3*(q*(15*k+q*(15*k+12*q+18)+2)-2) for k in range(1,s+1)))//60 # _Chai Wah Wu_, Oct 21 2023

