# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A364268

def A364268(n): return sum(k**4*(m:=n//k)*(m+1)*((m<<1)+1)//6 for k in range(1,n+1)) # _Chai Wah Wu_, Oct 20 2023
from math import isqrt
def A364268(n): return (((s:=isqrt(n))*(s+1)*(2*s+1))**2*(1-3*s*(s+1))//6 + sum((q:=n//k)*(q+1)*(2*q+1)*k**2*(5*k**2+3*q*(q+1)-1) for k in range(1,s+1)))//30 # _Chai Wah Wu_, Oct 21 2023

