# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A364835

from itertools import islice
from collections import Counter
def agen(): # generator of terms
    an = 1; c = Counter([1])
    while True: yield an; an = c[an+1] - c[an]; c[an] += 1
print(list(islice(agen(),1001))) # _Michael S. Branicky_, Aug 29 2023

