# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A364682

def A364682(n):
    c = 1
    while n not in {0,1,37,58,89,145,42,20,4,16}:
        n = sum((0, 1, 4, 9, 16, 25, 36, 49, 64, 81)[ord(d)-48] for d in str(n))
        c += 1
    return c

