# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A364198

a = [0]; [a.append(a[abs(n-a[n]**2)]+1) for n in range(1000)] # A364197
b = [a.index(n) for n in range(max(a)+1)] # A364198

