# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A385895

from functools import cache
@cache
def seidel(n: int, m: int) -> list[int]:
    if n == 0: return [1]
    rowA = seidel(n - 1, m)
    row = [0] + rowA
    row[1] = row[n]
    for k in range(2, n + 1):
        row[k] = row[k - 1] + m * rowA[n - k]
    return row
def A385895row(n: int) -> list[int]: return seidel(n, 2)
for n in range(9): print(A385895row(n))

