# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A385825

from gmpy2 import digits
from sympy.abc import x
from sympy import Poly, rem
def A385825(n):
    k = (1,2,4,3)
    s = digits(n,5)
    t = [s.count(str(i)) for i in range(1,5)]
    G = 2**t[0]*(x+2)**t[1]*(2*x**2+3)**t[3]*(2*x**3+2)**t[2]
    c = Poly(rem(G,x**4-1),x).all_coeffs()[::-1]
    return int(sum(k[i]*c[i] for i in range(len(c)) if c[i]))

