# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A385704

from math import isqrt
def A385704(n): return n+(m:=isqrt(5*n//3))+(n+m>=3*(m+1)**2//5)

