# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A263535

def moda(n):
    return sum(int(d)**(i + 1) for i, d in enumerate(str(n)))
b = 1
resu = [1]
for a in range(1, 100):
    b += moda(b)
    resu.append(b)
resu

