# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A257117

import sympy
def sumpow(sn0, n, p):
    af=0; bf=0; an=1
    sn1=sn0+n
    if n!=0:
        sn1=sympy.nextprime(sn0, n)
    while an**p<sn1:
        bnsq=sn1-(an**p)
        bn=sympy.ntheory.perfect_power(bnsq)
        if bn!=False and list(bn)[1]==p:
            af=an
            bf=list(bn)[0]
            an=sn1+100
        an=an+1
    return(af, bf)
s0=1; pw=2
while s0>0:
    a0, b0=sumpow(s0, 0, pw)
    a1, b1=sumpow(s0, 1, pw)
    if a0!=0 and a1!=0:
        print(s0)
    s0=sympy.nextprime(s0)

