# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A257492

from sympy import S
digits = 1000
pi, phi = str(S.Pi.n(digits+3)), str(S.GoldenRatio.n(digits+3))
print([k for k in range(2, digits+1) if pi[k] == phi[k]]) # _Michael S. Branicky_, May 06 2023

