# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A329825

from math import isqrt
def A329825(n): return 3*n+isqrt(17*n**2)>>2 # _Chai Wah Wu_, Feb 20 2026

