# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A393817

from math import lcm
def baker(i, j, n):
    i1 = i // 2
    j1 = 2 * j + (i % 2)
    if j1 < n:
        return [i1, j1]
    else:
        return [n - 1 - i1, 2 * n - 1 - j1]
def pixelperiod(i, j, n):
    U = baker(i, j, n)
    m = 1
    while U != [i, j]:
        U = baker(U[0], U[1], n)
        m += 1
    return m
U = []
for n in range(1,33):
    period = 1
    for i in range(n):
        for j in range(n):
            per = pixelperiod(i, j, n)
            period = lcm(period, per)
    U.append(period)
print(U)

