# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A393665

# Brute force for small n; use transfer matrix for n > 4
from itertools import product, combinations
def is_convex(S, n):
    S = set(S)
    for a in S:
        for b in S:
            if a[0]<=b[0] and a[1]<=b[1]:
                for c in product(range(a[0],b[0]+1), range(a[1],b[1]+1)):
                    if c not in S: return False
    return True
def a(n):
    grid = list(product(range(n), repeat=2))
    count = 0
    for r in range(len(grid)+1):
        for S in combinations(grid, r):
            if is_convex(S, n): count += 1
    return count
print([a(n) for n in range(1, 5)])  # [2, 13, 114, 1146]

