# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A393799

from gmpy2 import next_prime
from itertools import islice
def agen(): # generator of terms
    adict, n = {None: None}, 1
    p, q, r = 2, 3, 5
    while True:
        p, q, r = q, r, next_prime(r)
        v = (r-q)//2 if q-p == r-q + 2 else None
        if v not in adict:
            adict[v] = int(p)
            while n in adict: yield adict[n]; n += 1
print(list(islice(agen(), 34))) # _Michael S. Branicky_, Feb 28 2026

