# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A393138

from math import comb as binom
def A393138(n: int, k: int) -> int:
    return sum(binom(k, i) * binom(n-i, (n-i) >> 1) for i in range(k + 1))
for n in range(10): print([A393138(n, k) for k in range(n + 1)])

