# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A393748

def covers(l0, n, k):
    L = [[]]
    for i in range(min(k, (n-k-1)//2)+1):
        L2 = []
        b = l0[i] if i < len(l0) and l0[i] < k-i else k-i+1
        b = min(b, n-k-2*i)
        for l in L:
            if i > 0:
                b2 = min(l[i-1]-1, b) if l[i-1]>0 else 0
            else:
                b2 = b
            for j in range(0, b2+1):
                l2 = l.copy()
                l2.append(j)
                L2.append(l2)
        L = L2
    return [tuple(l) for l in L]
def a(n):
    t = tuple()
    D = {t:1}
    for k in range(n):
        D2 = {}
        for l in D:
            for t in covers(l, n, k):
                if t in D2:
                    D2[t] += D[l]
                else:
                    D2[t] = D[l]
        D = D2
    return sum(D.values())
print([a(n) for n in range(15)])

