# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A393142

from math import perm
def T(n: int, k: int) -> int:
    if k == 0: return k**n
    return (-1)**(n+1) * sum((-k)**(n-i) * perm(k-1, i-1) for i in range(1, k+1))

