# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A099351

from sympy import isprime
from math import factorial
print([k for k in range(300) if isprime(5*factorial(k) - 1)]) # _Michael S. Branicky_, Mar 05 2021

