# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A164790

# faster for initial segment of sequence; uses n2w/imports above
def A164790gen(t="e", i0=0, offset=1): # generator of terms w
    adict, n = dict(), offset
    for i in count(i0):
        w = n2w(i)
        if t in w:
            locs = [i+1 for i, c in enumerate(w) if w[i] == t]
            for v in locs:
                if v not in adict: adict[v] = i
        while n in adict: yield adict[n]; n += 1
print(list(islice(A164790gen(), 50))) # _Michael S. Branicky_, Apr 21 2023

