# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A127741

# requires Python 3.2 or higher. Otherwise use def'n of accumulate in Python docs.
from itertools import accumulate
A127741_list, blist, b = [], [1], 1
for n in range(1,1001):
    blist = list(accumulate([b]+blist))
    b = blist[-1]
    A127741_list.append(blist[-2]*n) # _Chai Wah Wu_, Sep 20 2014

