# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A117609

# uses Python code for A057655
from math import isqrt
def A117609(n): return A057655(n)+(sum(A057655(n-k**2) for k in range(1,isqrt(n)+1))<<1) # _Chai Wah Wu_, Jun 23 2024

