# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A333675

N = 60
notlucas = []
lucas = [2, 1]
for x in range(N):
    a = lucas[x] + lucas[x+1]
    lucas.append(a)
notlucas = [x for x in range(1, len(lucas)) if x not in lucas]
A333675 = []
for y in range(len(notlucas)):
    a = sum(notlucas[:y]) + notlucas[y]
    A333675.append(a)
print(', '.join(str(x) for x in A333675))

