# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A333596

import numpy as np
def qnary(n):
    e = n//4
    q = n%4
    if n == 0 : return 0
    if e == 0 : return q
    if e != 0 : return np.append(qnary(e), q)
m = 400
v = [0]
for i in range(1,m+1) :
    t = np.array(qnary(i))
    t[t%2 != 0] = 1
    t[t%2 == 0] = -1
    v = np.append(v, np.sum([np.sum(t), v[i-1]]))

