# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A333438

# Using graphillion
from graphillion import GraphSet
import graphillion.tutorial as tl
def A333438(n):
    universe = tl.grid(n - 1, n - 1)
    GraphSet.set_universe(universe)
    start, goal = 1, 2
    paths = GraphSet.paths(start, goal)
    return paths.len() * 2
print([A333438(n) for n in range(2, 10)])

