# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A371113

def A371113(n):
    try: return A371113.terms[n]
    except AttributeError: A371113.terms = []; A371113.least_unused = 0
    except IndexError: pass # just need to compute more terms
    while len(T := A371113.terms) <= n:
        if len(T)%3 < 2:
            T.append(x := A371113.least_unused)
            while x+1 in T: x += 1
            A371113.least_unused = x+1
        else:
            for i in range(1,len(suffix := (str(T[-2])+str(T[-1]))[::-1])+1):
                if suffix[-i] != '0' and (s := suffix[:-i-1:-1] + suffix
                    )==s[::-1] and (x := int(suffix[-i:])) not in T: break
            else: x = int('1'+suffix); assert x not in T
            T.append(x); assert x > A371113.least_unused
    return T[n] # _M. F. Hasler_, Apr 19 2024

