# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A371598

from sympy import fibonacci
def a(n):
    a_n = 1
    mod = fibonacci(n + 1)
    for i in range(1, n + 1):
        a_n = (a_n * fibonacci(i)) % mod
    return a_n

