# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A371568

# The Akiyama-Tanigawa algorithm for the binomial generates the rows.
# Adds row(0) = 0^k and column(0) = 0^n.
def ATBinomial(n, len):
    A = [0] * len
    R = [0] * len
    for k in range(len):
        R[k] = binomial(k, n)
        for j in range(k, 0, -1):
            R[j - 1] = j * (R[j] - R[j - 1])
        A[k] = R[0]
    return A
for n in range(11): print([n], ATBinomial(n, 11))  # _Peter Luschny_, Apr 19 2024

