# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A371666

from itertools import count, islice
from sympy import factorint
def A371666_gen(startvalue=4): # generator of terms >= startvalue
    for n in count(max(startvalue,4)):
        f = factorint(n)
        if sum(f.values()) > 1:
            c = 0
            for p in sorted(f,reverse=True):
                a, q = p.bit_length(), int(bin(p)[:1:-1],2)
                for _ in range(f[p]):
                    c = (c<<a)+q
            if c == n:
                yield n
A371666_list = list(islice(A371666_gen(),3)) # _Chai Wah Wu_, Apr 13 2024

