# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A371833

from itertools import count, islice
from sympy import primerange
def A371833_gen(): # generator of terms
    for l in count(1):
        m = 10**l
        for a in range(1,10):
            b = (a*10**3+234)*m
            yield from primerange(b,b+m)
A371833_list = list(islice(A371833_gen(),20)) # _Chai Wah Wu_, Apr 09 2024

