# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A220280

t=int((math.sqrt(8*n-7) - 1)/ 2)
n1=n-t*(t+1)/2
t1=int((math.sqrt(8*n1-7) - 1)/ 2)
a=n1-t1*(t1+1)/2

