# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A098700

from itertools import count, islice
from sympy import factorint
def A098700_gen(startvalue=2): # generator of terms >= startvalue
    return filter(lambda n:all(map(lambda m:sum((m*e//p for p,e in factorint(m).items())) != n,range(1,(n**2>>1)+1))),count(max(startvalue,2)))
A098700_list = list(islice(A098700_gen(),30)) # _Chai Wah Wu_, Sep 12 2022

