# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A098971

def A098971(n): return ((1<<(m:=n.bit_length()+2))+(1 if m&1 else -1))//3 # _Chai Wah Wu_, Oct 10 2024

