# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A305377

from sympy import prime
def A305377(n):
    m, tlist, s = prime(n), [1,2,4], 0
    while tlist[-1]+tlist[-2]+tlist[-3] <= m:
        tlist.append(tlist[-1]+tlist[-2]+tlist[-3])
    for d in tlist[::-1]:
        s *= 2
        if d <= m:
            s += 1
            m -= d
    return s # _Chai Wah Wu_, Jun 12 2018

