# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A289673

from itertools import product
A289673_list = [-1 if s == ('1',) else int((''.join(s)+('2212' if s[0] == '2' else '11'))[3:]) for l in range(1,10) for s in product('12',repeat=l)] # _Chai Wah Wu_, Aug 06 2017

