# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A289201

from networkx import empty_graph, find_cliques, complement
def A289201(n):
    G = empty_graph((i,j) for i in range(n) for j in range(n))
    G.add_edges_from(((i,j),(i+k,j+l)) for i in range(n) for j in range(n) for (k,l) in ((1,2),(1,-2),(-1,2),(-1,-2),(2,1),(2,-1),(-2,1),(-2,-1)) if 0<=i+k<n and 0<=j+l<n)
    return sum(1 for c in find_cliques(complement(G))) # _Chai Wah Wu_, Jan 11 2024

