# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A289720

from math import comb
def A289720(n): return 1+n*comb(2*n,n)-n**2*(n**2-2*n+3)//2 # _Aidan Chen_, Jan 23 2026

