# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A360674

def accel_asc(n):
    a = [0 for i in range(n + 1)]
    k = 1
    y = n - 1
    while k != 0:
        x = a[k - 1] + 1
        k -= 1
        while 2 * x <= y:
            a[k] = x
            y -= x
            k += 1
        l = k + 1
        while x <= y:
            a[k] = x
            a[l] = y
            yield a[:k + 2]
            x += 1
            y -= 1
        a[k] = x + y
        y = x + y - 1
        yield a[:k + 1]
for y in range(1000):
    num = 0
    for x in accel_asc(2*y):
        stop = len(x)//2+1
        if len(x) % 2 == 0:
            stop -= 1
        right = x[0:stop]
        left = x[stop:]
        if sum(right) == sum(left):
            num += 1
    print(y,num)
# _David Consiglio, Jr._, Mar 09 2023

