# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A360427

xm,ym,x,n = 0,1,0,1
while True:
    x,y = x+1,x+4
    while y*xm < ym*x:
        c,d,s = x+1,y-1,x**3+y**3
        while c<d:
            t=c**3+d**3
            if t<s:
                c+=1
            elif t>s:
                d-=1
            else:
                break
        if t==s:
            print("a({})={} x={} c={} d={} y={}".format(n,x,x,c,d,y))
            xm,ym,n = x,y,n+1
            break
        y+=1
# _Bert Dobbelaere_, Mar 18 2023

