# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A131551

def a(n):
  k, n2, np2 = 1, '2'*n, '2'*(n+1)
  while True:
    while not n2 in str(3**k): k += 1
    if np2 not in str(3**k): return k
    k += 1
print([a(n) for n in range(1, 8)]) # _Michael S. Branicky_, Mar 19 2021

