# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A347046

from sympy import divisors, factorint
def a(n):
    npf = len(factorint(n, multiple=True))
    for d in divisors(n)[-1:0:-1]:
        if 2*len(factorint(d, multiple=True)) == npf: return d
    return 1
print([a(n) for n in range(1, 82)]) # _Michael S. Branicky_, Aug 18 2021

