# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A347400

def ispal(s): return s == s[::-1]
def aupton(terms):
    alst, seen = [1], {1}
    for n in range(2, terms+1):
        an = 1
        while an in seen or not ispal(str(n) + str(an)): an += 1
        alst.append(an); seen.add(an)
    return alst
print(aupton(200)) # _Michael S. Branicky_, Aug 30 2021

