# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A347140

def delta(s): return str(int(s[0]) + int(s[1]))
def a(n):
    if n%10 == 0 and n%100 != 10: return 0
    s = "0"*(n < 10) + str(n)
    i, target, nexts = 1, s[:], delta(s[:2])
    s = s[1:] + nexts
    while target not in s:
        nexts = delta(s[:2])
        s = s[1:] + nexts
        i += 1
    return i
print([a(n) for n in range(1, 132)]) # _Michael S. Branicky_, Aug 19 2021

