# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A347323

def A347323(n): return int(''.join('0' if d == '0' else str(n % int(d)) for d in str(n))) # _Chai Wah Wu_, Sep 13 2021

