# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A347344

from sympy import isprime
def ok(n): s = str(n); return isprime(int(s[0] + s))
print(list(filter(ok, range(362)))) # _Michael S. Branicky_, Aug 27 2021

