# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A038366

from math import prod
def ok(n): d = list(map(int, str(n))); return n and n%(sum(d)+prod(d)) == 0
print([k for k in range(411) if ok(k)]) # _Michael S. Branicky_, Oct 19 2021

