# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A038024

from math import prod
from collections import Counter
from sympy import factorint
def A038024(n):
    if n == 1: return 1
    a = sum((Counter(factorint(i)) for i in range(2,n)),start=Counter())
    return prod(e+1 for e in (a+Counter(factorint(n))).values())-prod(e+1 for e in a.values()) # _Chai Wah Wu_, Feb 23 2026

