# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A389140

from functools import cache
def children(s):
    return set(int(s[:i]+str(q>>1)+s[j:]) for i in range(len(s)) for j in range(i+1, len(s)+1) if (w:=s[i:j])[0]!='0' and (q:=int(w))&1==0)
@cache
def a(n):
    if n.bit_count() == 1: return 1
    if set(s:=str(n)) <= set("13579"): return n
    return min(a(c) for c in children(s))
print([a(n) for n in range(1, 76)]) # _Michael S. Branicky_, Sep 28 2025

