# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A389725

from gmpy2 import is_prime
from itertools import islice
def f(n): # A389720
    s = str(n)
    return max((p for i in range(len(s)+1) for d in "0123456789" if is_prime(p:=int(s[:i]+d+s[i:]))), default=-1)
def agen(): # generator of terms
    an, prevan = 5, -1
    while an > prevan:
        yield an
        an, prevan = f(an), an
print(list(islice(agen(), 21)))

