# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A389674

from sympy.ntheory import digits
def a(n): return n if (b:=sum(d:=list(map(int, str(n)))))<2 else sum(di*10**i for i, di in enumerate(digits(n, b)[:0:-1]))
print([a(n) for n in range(1, 62)]) # _Michael S. Branicky_, Oct 10 2025

