# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A389838

print(sorted({v for max in [50] for j in range(2, max+1) for k in range(2, max+1) for v in (j*k, j*k+(j-1)*(k-1)) if v <= 2*max+1}))

