# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A389418

from itertools import count
def isconcat(n):
    if n < 10: return False
    s = str(n); mid = (len(s)+1)//2
    return s[mid] != '0' and int(s[:mid]) - 1 == int(s[mid:])
def a(n): return next(k for k in count(1) if isconcat(((k+n)*(k+n-1)-k*(k-1))//2))
print([a(n) for n in range(1, 66)]) # _Michael S. Branicky_, Oct 08 2025

