# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A237426

from itertools import permutations
print("0"," ","1")
print("1"," ","3")
for j in range(5,27,2):
    x = list(range(1,j+1))
    sum2 = 0
    for a in permutations(x):
        x = list(a)
        sum1 = x[0]+x[1]+x[2]
        d = 1
        for i in range(2,j-2,2):
            if (sum1== x[i]+x[i+1]+x[i+2]):
                d = 1
            else:
                d = 0
                break
        if (d==1):
            if (a[0]<a[j-1]):
                sum2 = sum2+1
    print((j-1)//2, " ", sum2)

