# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A372408

from sympy import isprime
from itertools import islice
from Levenshtein import distance as Ld
def agen(): # generator of terms
    an, aset, mink = 1, {1}, 4
    while True:
        yield an
        s, k = str(an), mink
        while k in aset or Ld(s, str(k)) != 1 or isprime(k): k += 1
        an = k
        aset.add(k)
        while mink in aset or isprime(mink): mink += 1
print(list(islice(agen(), 80))) # _Michael S. Branicky_, Apr 29 2024

