# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A372841

from math import gcd
from sympy import primepi, integer_nthroot, factorint
def A372841(n):
    def f(x):
        c = n+x+1+sum(primepi(integer_nthroot(x, k)[0]) for k in range(4, x.bit_length()))
        for u in range(1,integer_nthroot(x,7)[0]+1):
            if all(d<=1 for d in factorint(u).values()):
                for w in range(1,integer_nthroot(a:=x//u**7,6)[0]+1):
                    if gcd(w,u)==1 and all(d<=1 for d in factorint(w).values()):
                        for y in range(1,integer_nthroot(z:=a//w**6,5)[0]+1):
                            if gcd(w,y)==1 and gcd(u,y)==1 and all(d<=1 for d in factorint(y).values()):
                                c -= integer_nthroot(z//y**5,4)[0]
        return c
    def bisection(f,kmin=0,kmax=1):
        while f(kmax) > kmax: kmax <<= 1
        while kmax-kmin > 1:
            kmid = kmax+kmin>>1
            if f(kmid) <= kmid:
                kmax = kmid
            else:
                kmin = kmid
        return kmax
    return bisection(f,n,n) # _Chai Wah Wu_, Sep 10 2024

