# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A214252

SIZE=28  # must be even
grid = [0] * (SIZE*SIZE)
saveX = [0]* (SIZE*SIZE)
saveY = [0]* (SIZE*SIZE)
saveX[1] = saveY[1] = posX = posY = SIZE//2
grid[posY*SIZE+posX]=1
n = 2
def walk(stepX, stepY, chkX, chkY):
  global posX, posY, n
  while 1:
    posX+=stepX
    posY+=stepY
    grid[posY*SIZE+posX]=n
    saveX[n]=posX
    saveY[n]=posY
    n+=1
    if posY==0 or grid[(posY+chkY)*SIZE+posX+chkX]==0:
        return
while posY!=0:
    walk( 1, 1, -1,  0)    # right-down
    walk(-1, 0,  0, -1)    # left
    walk(0, -1,  1,  1)    # up
for n in range(1, 92):
    posX = saveX[n]
    posY = saveY[n]
    k = grid[(posY-1)*SIZE+posX] + grid[(posY+1)*SIZE+posX]
    k+= grid[(posY-1)*SIZE+posX-1] + grid[(posY-1)*SIZE+posX+1]
    k+= grid[(posY+1)*SIZE+posX-1] + grid[(posY+1)*SIZE+posX+1]
    k+= grid[posY*SIZE+posX-1] + grid[posY*SIZE+posX+1]
    print(k, end=' ')

