# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A214648

from __future__ import division
from gmpy2 import is_square
A214648_list, s, c, d = [], 0, 0, -1
for _ in range(10):
    k = 2
    q = 4*(k*(k*(k+c)+d))//3 + 1
    while not is_square(q):
        k += 1
        q = 4*(k*(k*(k+c)+d))//3 + 1
    A214648_list.append(k)
    s += k
    c, d = 3*s, 3*s**2-1 # _Chai Wah Wu_, Mar 01 2016

