# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A214939

from itertools import product
def a(n):
  if n == 1: return 5
  squares = ["".join(u) + "".join(u)
    for r in range(1, n//2 + 1) for u in product("01234", repeat = r)]
  words = ("0"+"".join(w) for w in product("01234", repeat=n-1))
  return 5*sum(all(s not in w for s in squares) for w in words)
print([a(n) for n in range(1, 10)]) # _Michael S. Branicky_, May 20 2021

