# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A158353

from num2words import num2words
def A158353upto(n):
  i, ans = 1, []
  for k in range(1, n+1):
    while sum(1 for c in num2words(i).replace(' and ', '') if c in "aeiouy") != k:
      i += 1
      ans.append(i)
  return ans
print(A158353upto(20)) # _Michael S. Branicky_, Oct 23 2020

