# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A354463

def A354463(n):
    c, m = 0, 2**n
    while m >= 5:
        m //= 5
        c += m
    return c # _Chai Wah Wu_, Jun 02 2022

