# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A354269

def ok(b): return pow(b, 10, 121)==1 and pow(b, 1006002, 1006003**2)==1
print([k for k in range(10**6) if ok(k)]) # _Michael S. Branicky_, May 25 2022

