# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A343421

def isf(s): # incrementally squarefree (check factors ending in last letter)
    for l in range(1, len(s)//2 + 1):
        if s[-2*l:-l] == s[-l:]: return False
    return True
def aupton(nn, verbose=False):
    alst, sfs = [], set("0")
    for n in range(1, nn+1):
        an, eo = 4*len(sfs), ["02", "13"]
        sfsnew = set(s+i for s in sfs for i in eo[n%2] if isf(s+i))
        alst, sfs = alst+[an], sfsnew
        if verbose: print(n, an)
    return alst
print(aupton(30)) # _Michael S. Branicky_, Jun 20 2022

