# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A343739

from math import isqrt
def A343739(n):
    i = isqrt(n)
    if i**2 == n:
        return -1
    m, dset = n, set()
    for d in (int(s) for s in str(i)):
        dset.add(d)
        if len(dset) == 10:
            return d
    while len(dset) < 10:
        m *= 100
        d = isqrt(m) % 10
        dset.add(d)
    return d # _Chai Wah Wu_, Jul 07 2021

