# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A343856

def auptorow(rows):
  alst, row, newrow = [1], [1], []
  for r in range(2, rows+1):
    for i, v in enumerate(row, start=1): newrow += [v, v] if i%2 else [2*v]
    alst, row, newrow = alst + newrow, newrow, []
  return alst
print(auptorow(9)) # _Michael S. Branicky_, May 04 2021

