# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A343403

def getBaseTen(howMany=100):
    listToReturn = []
    listOfObtainedValues = []
    count = 0
    while len(listToReturn) < howMany:
        afterOnePermutation = 1
        for num in str(count):
            afterOnePermutation *= int(num)
            if afterOnePermutation == 0:
                break
        if not afterOnePermutation in listOfObtainedValues:
            listToReturn.append(count)
            listOfObtainedValues.append(afterOnePermutation)
        count += 1
    return listToReturn

