# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A343431

from math import prod
from sympy import factorint
def A343431(n): return prod(p**e for p, e in factorint(n).items() if not (p+1)%6) # _Chai Wah Wu_, Dec 26 2022

