# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A116333

from itertools import count, islice
from sympy import sqrt_mod
def A116333_gen(): # generator of terms
    for j in count(0):
        b = 10**j
        a = b*10+1
        for k in sorted(sqrt_mod(22,a,all_roots=True)):
            if a*(b-6) <= k**2-22 < a*(a-7) and k>4:
                yield k-4
A116333_list = list(islice(A116333_gen(),10)) # _Chai Wah Wu_, Feb 21 2024

