# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A048332

A048332_list = [0] + [int(d*l,7) for l in range(1,10) for d in '123456'] # _Chai Wah Wu_, May 30 2016

