# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A048338

A048338_list = [0] + [int(d*l,14) for l in range(1,10) for d in '123456789abcd'] # _Chai Wah Wu_, May 30 2016

