# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A048766

from sympy import integer_nthroot
def a(n): return integer_nthroot(n, 3)[0]
print([a(n) for n in range(105)]) # _Michael S. Branicky_, Oct 19 2021

