# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A048679

def A048679(n):
    tlist, s = [1,2], 0
    while tlist[-1]+tlist[-2] <= n: tlist.append(tlist[-1]+tlist[-2])
    for d in tlist[::-1]:
        if d <= n:
            s += 1
            n -= d
        else:
            s <<= 1
    return s # _Chai Wah Wu_, Apr 24 2025

