# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A081091

from itertools import count, islice
from sympy import isprime
from sympy.utilities.iterables import multiset_permutations
def A081091_gen(): # generator of terms
    return filter(isprime,map(lambda s:int('1'+''.join(s)+'1',2),(s for l in count(1) for s in multiset_permutations('0'*(l-1)+'1'))))
A081091_list = list(islice(A081091_gen(),30)) # _Chai Wah Wu_, Jul 19 2022

