# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A081400

from sympy import primefactors, factorint, divisor_count
from operator import mul
def bigomega(n): return 0 if n==1 else bigomega(n/primefactors(n)[0]) + 1
def a005361(n):
    f=factorint(n)
    return 1 if n==1 else reduce(mul, [f[i] for i in f])
def a(n): return divisor_count(n) - bigomega(n) - a005361(n) # _Indranil Ghosh_, May 25 2017

