# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A255576

from sympy import isprime, divisors
from fractions import Fraction
def ok(n):
    divs = divisors(n)
    f = sum(Fraction(dn, dd) for dn, dd in zip(divs[:-1], divs[1:]))
    return f.denominator == 1 and isprime(f.numerator)
print([k for k in range(1, 40000) if ok(k)]) # _Michael S. Branicky_, Feb 06 2022

