# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A047813

def c(s): return (s[0] != "0" or s == "0") and s == s[::-1]
def a(n):
    s = str(n)
    ss = (s[i:j] for i in range(len(s)) for j in range(i+1, len(s)+1))
    return max(int(w) for w in ss if c(w))
print([a(n) for n in range(96)]) # _Michael S. Branicky_, Sep 18 2022

