# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A047853

def A047853(n): return (pow(8,n) +6)//7
print([A047853(n) for n in range(41)]) # _G. C. Greubel_, Jan 12 2025

