# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A286584

from sympy import factorint, nextprime
from operator import mul
def a048673(n):
    f = factorint(n)
    return 1 if n==1 else (1 + reduce(mul, [nextprime(i)**f[i] for i in f]))/2
def a(n): return a048673(n)%4 # _Indranil Ghosh_, Jun 12 2017

