# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A286242

from sympy import prime, factorint
import math
def T(n, m): return ((n + m)**2 - n - 3*m + 2)/2
def A(n): return n - 2**int(math.floor(math.log(n, 2)))
def b(n): return n + 1 if n<2 else prime(1 + (len(bin(n)[2:]) - bin(n)[2:].count("1"))) * b(A(n))
def a005940(n): return b(n - 1)
def P(n):
    f=factorint(n)
    return sorted([f[i] for i in f])
def a046523(n):
    x=1
    while True:
        if P(n) == P(x): return x
        else: x+=1
def a003188(n): return n^(n>>1)
def a243353(n): return a005940(1 + a003188(n))
def a278219(n): return a046523(a243353(n))
def a278222(n): return a046523(a005940(n + 1))
def a(n): return T(a278222(n), a278219(n)) # _Indranil Ghosh_, May 07 2017

