# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A286359

from sympy import divisor_sigma as D
def T(n, m): return ((n + m)**2 - n - 3*m + 2)/2
def a(n): return T(D(n), D(2*n)) # _Indranil Ghosh_, May 12 2017

