# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A286298

def A286298(n):
    if n <= 1:
        return n
    a, b = divmod(n, 2)
    return A286298(a) + 1 + b + (-1)**b*(a % 2) # _Chai Wah Wu_, Jun 02 2017

