# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A286357

from sympy import divisor_sigma as D
def a001511(n): return bin(n)[2:][::-1].index("1") + 1
def a(n): return a001511(D(n)) # _Indranil Ghosh_, May 12 2017

