# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A286851

from sympy import divisors, gcd
from sympy.core.cache import cacheit
@cacheit
def a(n):
    l=[x for x in divisors(n) if gcd(x, n//x)==1]
    @cacheit
    def b(m): return 1 if m==0 else sum(b(m - j) for j in l if j <= m)
    return b(n)
print([a(n) for n in range(61)]) # _Indranil Ghosh_, Aug 01 2017, after Maple code

