# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A101115

from sympy import isprime, prime
def a(n):
    pn = prime(n)
    s, c, found = str(pn), 0, True
    while found:
        found = False
        for d in "123456789":
            if isprime(int(d+s)):
                s, c, found = d+s, c+1, True
                break
    return c
print([a(n) for n in range(1, 91)]) # _Michael S. Branicky_, Jun 24 2022

