# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A101701

from sympy import divisors
A101701_list = [n for n in range(1,10**6) if n == sum([int(d) for d in (str(x)[::-1] for x in divisors(n))])]
# _Chai Wah Wu_, Dec 06 2014

