# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A232116

from sympy import isprime,primerange
def Pow(n):
    s = 0
    for i in str(n):
        k = int(i)
        if k:
            s += k**k
    return s
{print(pn, end=', ') for pn in primerange(1,2000) if isprime(Pow(pn))}
## Simplified by _Derek Orr_, Apr 05 2015

