# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A176923

def A176923(n):
    if n == 1: return 0
    a = 1<<n.bit_length()-2
    s = bin(a|(n&a-1))[2:]
    return int(s+(s[::-1] if a&n else s[-2::-1]))**2 # _Chai Wah Wu_, Jun 10 2024

