# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A176297

from sympy import factorint
def ok(n): return 3 in [e for e in factorint(n).values()]
print(list(filter(ok, range(713)))) # _Michael S. Branicky_, Aug 24 2021

