# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A378907

def generate_A378907(n):
    f, A000166, A378907 = 6, 2, [0, 1, 0, 2]
    A003471 = [1, 0, 0, 0]
    for i in range(4, n):
        f *= i
        A000166 = i*A000166 + (1 if i%2==0 else -1)
        d, e = (2,4) if i%2==0 else (1,2)
        A003471.append((i-1)*A003471[-1] + 2*(i-d)*A003471[-e])
        A003471 = A003471[1:]
        s = f - 2*A000166 + A003471[-1]
        A378907.append(s)
    return A378907
A378907 = generate_A378907(23)  # _Jwalin Bhatt_, Dec 27 2024

