# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A378373

# use Python code from A013929
from sympy import primepi
def A378373(n): return (b:=A013929(n+1))-(a:=A013929(n))-primepi(b)+primepi(a)-1 # _Chai Wah Wu_, Dec 20 2025

