# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A378588

def mchains(n,k):
    B,d1,S1 = [1,1],{(1,): 1},{(1,)}
    for i in range(n-1):
        d2,S2 = dict(),set()
        for j in S1:
            for x in [j+(1,), (1,)+j]+[j[:z]+tuple([j[z]+1])+j[z+1:] for z in range(len(j)) if j[z] < k]:
                if x not in S2: S2.add(x); d2[x] = d1[j]
                elif x != tuple([1]*(i+2)): d2[x] += d1[j]
        B.append(sum(d2.values())); d1 = d2; S1 = S2
    return B[:n+1]
def A378588_list(max_n):
    B = [mchains(max_n,i+1) for i in range(max_n)]
    return [[B[k][j+1] for k in range(j+1)] for j in range(max_n)]

