# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A378625

from mpmath import mp
mp.dps = 1000000
pi_digits = str(mp.pi)[2:]
def first_divisible(n):
    current_number = 0
    for digit in pi_digits:
        current_number = current_number * 10 + int(digit)
        if current_number % n == 0:
            return current_number
    return None
results = [first_divisible(n) for n in range(1, 21)]
print(results)

