# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A093562

from math import comb, isqrt
def A093562(n): return comb(r:=(m:=isqrt(k:=n+1<<1))-(k<=m*(m+1)),a:=n-comb(r+1,2))*(r+(r-a<<2))//r if n else 1 # _Chai Wah Wu_, Nov 12 2024

