# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A064538

from __future__ import division
from sympy.ntheory.factor_ import digits, nextprime
def A064538(n):
    p, m = 2, n+1
    while p <= (n+2)//(2+ (n% 2)):
        if sum(d for d in digits(n+1,p)[1:]) >= p:
            m *= p
        p = nextprime(p)
    return m # _Chai Wah Wu_, Mar 07 2018

