# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A064690

from itertools import count, islice
def A064690_gen(): # generator of terms
    ap, aq, sa = 1, 1, True
    for n in count(1):
        if (r:=ap+aq) > 0:
            bq = aq*r
            bp = ap*r-aq**2
        else:
            bq = -aq*r
            bp = aq**2-ap*r
        if (sa is not (sb:=bp>0)):
            yield n
        ap, aq, sa = bp, bq, sb
A064690_list = list(islice(A064690_gen(),7)) # _Chai Wah Wu_, Jul 24 2023

