# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A064825

from collections import Counter
from itertools import count, takewhile, combinations_with_replacement as mc
def aupto(N):
    tris = takewhile(lambda x: x <= N, (i*(i+1)//2 for i in count(1)))
    sum3 = filter(lambda x: x <= N, (sum(c) for c in mc(tris, 3)))
    sum3counts = Counter(sum3)
    return sorted(k for k in sum3counts if sum3counts[k] == 2)
print(aupto(1000)) # _Michael S. Branicky_, Dec 17 2021

