# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A064235

from gmpy2 import digits
def A064235(n): return 3**len(digits(n-1,3)) if n>1 else 1 # _Chai Wah Wu_, Oct 21 2024

