# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A002206

from math import factorial
from fractions import Fraction
from sympy.functions.combinatorial.numbers import stirling
def A002206(n): return (sum(Fraction(stirling(n+1,k,kind=1,signed=True),k+1) for k in range(n+2))/factorial(n+1)).numerator # _Chai Wah Wu_, Feb 12 2023

