# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A002805

from math import factorial, gcd
def A002805(n): return (m:=factorial(n))//gcd(sum(m//i for i in range(1,n+1)),m) # _Chai Wah Wu_, May 01 2026

