# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A002734

from math import isqrt, prod
from sympy import factorint
def A002734(n):
    k = isqrt(n)
    return prod(p for p, e in factorint(n+k+int(n>k*(k+1))).items() if e&1) # _Chai Wah Wu_, Jun 05 2025

