# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A091636

from sympy import primerange
def a(n): return sum('2' not in str(p) for p in primerange(2, 10**n))
print([a(n) for n in range(1, 7)]) # _Michael S. Branicky_, Mar 22 2021

