# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A376269

from sympy import factorial
def A376269(n): return n**2*factorial(n-2)+n-3 # _Chai Wah Wu_, Sep 20 2024

