# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A376252

def a(n): return int(str(n+1)+str(n))%n
print([a(n) for n in range(1, 81)]) # _Michael S. Branicky_, Sep 17 2024

