# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A179622

def A179622(up_to_n):
    sequence=[1,1,1,1,1,1,1,1,1,1]
    for n in range(len(sequence),up_to_n+1):
        seed_of_new_element=[-int(x) for x in str(n).replace("0","")]
        new_element=sum(list(map(sequence.__getitem__, seed_of_new_element)))
        sequence.append(new_element)
    return sequence
A179622(63) # _Bence Bernáth_, Nov 08 2022
from functools import cache
@cache
def a(n): return 1 if n<10 else sum(a(n-int(i)) for i in str(n) if i!='0')
print([a(n) for n in range(1, 81)]) # _Michael S. Branicky_, Nov 12 2022

