# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A076775

from math import gcd
def A076775(n): return gcd(n,int(bin(n)[2:])) # _Chai Wah Wu_, Sep 12 2022

