# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A094798

from itertools import accumulate, count, islice
def f(_, n): return _ + str(n).count("1")
def agen(): yield from accumulate(count(1), f)
print(list(islice(agen(), 75))) # _Michael S. Branicky_, Aug 09 2022

