# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A054347

from math import isqrt
from itertools import count, islice, accumulate
def A054347_gen(): # generator of terms
    return accumulate(n+isqrt(5*n**2)>>1 for n in count(0))
A054347_list = list(islice(A054347_gen(),30)) # _Chai Wah Wu_, Aug 29 2022

