# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A054212

def agen(POW=5):
  n = 1
  while True:
    k = 0
    while True:
      kpowstr = str(pow(k, POW))
      q, r = divmod(len(kpowstr), n)
      if r == 0:
        ok = True
        for d in set(kpowstr):
          if kpowstr.count(d) != n:
            ok = False; break
        if ok: break
        k += 1
      else: # go to next multiple of n digits: (q+1)*n
        k = max(k+1, int((10**((q+1)*n-1))**(1/POW)))
    yield k
    n += 1
g = agen() # call with POW=4, 3, 2 for A052093, A052071, A052069
print([next(g) for n in range(1, 5)]) # _Michael S. Branicky_, Dec 17 2020

