# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A054268

from sympy import prime
A054268 = [prime(n) for n in range(2,10**5) if len(set(str(int((prime(n+1)-prime(n)-1)*(prime(n+1)+prime(n))/2)))) == 1]
# _Chai Wah Wu_, Aug 12 2014

