# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A054845

from sympy import primerange
def aupton(nn): # modification of PARI by Zak Seidov
    alst = [0 for n in range(nn+1)]
    for x in primerange(2, nn+1):
        s = x
        alst[s] += 1
        for y in primerange(x+1, nn+1):
            s += y
            if s <= nn:
                alst[s] += 1
            else:
                break
    return alst
print(aupton(101)) # _Michael S. Branicky_, Feb 17 2022

