# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A278328

import math
n = 0
while True:
    if math.sqrt(abs(n-int(str(n)[::-1])))%1 == 0:
        print(n)
    n += 1 # _Jonathan Frech_, Nov 18 2016

