# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A010567

def A010567(n): # For illustration - becomes slow for n > 5
    if not hasattr(A:=A010567, 'terms'):
        A.terms=[6]; O=0,; A.paths=[(O*3, (1,)+O*2, t+O)for t in((2,0),(1,1))]
    while n > len(A.terms):
        for L in (0,1):
            new = []; cycles = 0
            for path in A.paths:
                end = path[-1]
                for i in (0,1,2):
                   for s in (1,-1):
                      t = tuple(end[j]if j!=i else end[j]+s for j in (0,1,2))
                      if t not in path: new.append(path+(t,))
                      elif L and t==path[0]: cycles += 24 if path[2][1] else 6
            A.paths = new
        A.terms.append(cycles)
    return A.terms[n-1] # _M. F. Hasler_, Jun 17 2025

