# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A308918

def nextpal(n,base): # m is the first palindrome successor of n in base base
    m, pl = n+1, 0
    while m > 0:
        m, pl = m//base, pl+1
    if n+1 == base**pl:
        pl = pl+1
    n = n//(base**(pl//2))+1
    m, n = n, n//(base**(pl%2))
    while n > 0:
        m, n = m*base+n%base, n//base
    return m
def ispal(n,b):
    if n%b == 0:
        return 0
    else:
        nn, m = n, 0
        while n > 0:
            n, m = n//b, m*b+n%b
        return m == nn
n, d = 1, 7
while n < 20000:
    n = n+1
    p = n**(d-1)-1
    a = 0
    while p < n**d:
        p = nextpal(p,n+1)
        if ispal(p,n):
            a = a+1
    print(n,a)

