# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A128302

from math import isqrt, prod
from sympy import primerange, integer_nthroot, primepi, prime
def A128302(n):
    def g(x,a,b,c,m): yield from (((d,) for d in enumerate(primerange(b,isqrt(x//c)+1),a)) if m==2 else (((a2,b2),)+d for a2,b2 in enumerate(primerange(b,integer_nthroot(x//c,m)[0]+1),a) for d in g(x,a2,b2,c*b2,m-1)))
    m = prime(n)**3
    return int(sum(primepi(m//prod(c[1] for c in a))-a[-1][0] for a in g(m,0,1,1,3))) # _Chai Wah Wu_, Jan 02 2026

