# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A352023

from sympy import n_order, nextprime
from itertools import islice
def A352023_gen(): # generator of terms
    yield from (2,3,5)
    p = 7
    while True:
        if '9' not in str(10**(n_order(10, p))//p):
            yield p
        p = nextprime(p)
A352023_list = list(islice(A352023_gen(),9)) # _Chai Wah Wu_, Mar 03 2022

