# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A092221

from sympy import bernoulli
A092221_list = [n for n in range(10**3) if not bernoulli(2*n).p % 59] # _Chai Wah Wu_, May 28 2016

