# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A092679

A092679 = [i for i,n in enumerate(map(lambda x:3*2**x,range(20))) if len([d for d in range(2,n,2) if n%d and not 2*n%d]+[d for d in range(3,n,2) if n%d and 2*n%d in [d-1,1]])==1] # _Chai Wah Wu_, Aug 09 2014

