# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A198775

from itertools import count, islice
def A198775_gen(startvalue=1): # generator of terms >= startvalue
    for n in count(max(startvalue,1)):
        c = 0
        for y in range(n+1):
            if c > 4 or y**2 > n:
                break
            for x in range(y+1):
                z = x*(x+y)+y**2
                if z > n:
                    break
                elif z == n:
                    c += 1
                    if c > 4:
                        break
        if c == 4:
            yield n
A198775_list = list(islice(A198775_gen(),10)) # _Chai Wah Wu_, May 16 2022

