# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A198584

# just prints the sequence
for a in range (5,100,1):
  for b in range(a-8+4*(a&1),0,-6):
    print(( ((1<<a)-(1<<b))//3-1)//3 ,end=",") # _André Hallqvist_, Aug 14 2019

