# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A127962

from gmpy2 import divexact
from sympy import prime, isprime
A127962 = [int(bin(p)[2:]) for p in (divexact(2**prime(n)+1,3) for n in range(2,10**2)) if isprime(p)] # _Chai Wah Wu_, Sep 04 2014

