# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A118118

from sympy import isprime
def selfplusneighs(n):
    s = str(n); d = "0123456789"; L = len(s)
    yield from (int(s[:i]+c+s[i+1:]) for c in d for i in range(L))
def ok(n): return all(not isprime(k) for k in selfplusneighs(n))
print([k for k in range(1131) if ok(k)]) # _Michael S. Branicky_, Jun 19 2022

