# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A296084

from math import prod
from sympy import factorint
def A296084(n):
    f = factorint(n).items()
    return int(not (prod((p**(e+1)-1)//(p-1) for p,e in f)-1)%(prod(e+1 for p,e in f)-1)) if n>1 else 0 # _Chai Wah Wu_, Oct 14 2023

