# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A358421

from itertools import count, islice
from sympy import isprime, primerange
def agen(): # generator of terms
    for d in count(1):
        pow = 10**d
        for p in primerange(10**(d-1), pow):
            for q in primerange(10**(d-1), pow):
                t = p*pow + q
                if isprime(t): yield t
print(list(islice(agen(), 51))) # _Michael S. Branicky_, Nov 15 2022

