# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A358178

from math import gcd, factorial
from itertools import combinations
f, terms = [2,], []
for i in range(2,100):
    f.append(factorial(i)+1)
    terms.append(len(set([gcd(*t) for t in combinations(f, 2)])))
print(terms)
from math import gcd
from itertools import count, islice
def A358178_gen(): # generator of terms
    m, f, g = 1, [], set()
    for n in count(1):
        m *= n
        g |= set(gcd(d,m+1) for d in f)
        f.append(m+1)
        yield len(g)
A358178_list = list(islice(A358178_gen(),20)) # _Chai Wah Wu_, Dec 15 2022

