# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A358127

from sympy import nextprime
from math import gcd
from itertools import combinations
pr, terms = [2,3], []
for i in range(100):
    terms.append(len(set([gcd(t[0]+1, t[1]+1) for t in combinations(pr,2)])))
    pr.append(nextprime(pr[-1]))
print(terms)
from math import gcd
from itertools import count, islice
from sympy import prime
def A358127_gen(): # generator of terms
    a, b = [3], set()
    for n in count(2):
        q = prime(n)+1
        b |= set(gcd(p,q) for p in a)
        yield len(b)
        a.append(q)
A358127_list = list(islice(A358127_gen(),100)) # _Chai Wah Wu_, Nov 02 2022

