# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A274016

#by _Charlie Neder_, using an algorithm from _David A. Corneth_, Aug 14 2018
limit = 10000
res = [0 for i in range(limit-1)]
a = 1
while not all(i > 0 for i in res):
  for b in range(1, a+1):
    for c in range(1, b+1):
      for d in range(1, c+1):
        for e in range(1, d+1):
          for f in range(1, e+1):
            if a*b*c + d*e*f in range(2, limit+1):
              if not res[a*b*c + d*e*f - 2]:
                res[a*b*c + d*e*f - 2] = a*b*c
  a += 1
for i in range(limit-1):
  print(i+2, res[i])

