# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A287817

def a(n):
 if n in [0, 1, 2, 3, 4]:
  return [1, 9, 67 , 501, 3747][n]
 return 8*a(n-1)-a(n-2)-23*a(n-3)+10*a(n-4)+a(n-5)

