# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A030503

from math import comb
def A030503(n):
    a, b = divmod(comb(n,3)<<3,(n<<1|1))
    return a+bool(b) # _Chai Wah Wu_, May 12 2026

