# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A030477

def ok(n):
    s = "".join("0" if d in "02468" else "1" for d in str(n**2))
    return len(set(s.rstrip(s[-1]))) < 2
print([k for k in range(141) if ok(k)]) # _Michael S. Branicky_, Oct 27 2024

