# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A123663

from math import isqrt
def A123663(n): return (m:=n<<1)-1-isqrt((m<<1)-1) # _Chai Wah Wu_, Jul 28 2022

