# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A244932

import sympy
from sympy import isprime
def a(n):
  for k in range(n+1,10**4):
    if isprime(k**8+n**8):
      return k
n = 1
while n < 100:
  print(a(n),end=', ')
  n += 1

