# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A069869

from collections import Counter
from operator import itemgetter
from sympy.utilities.iterables import partitions, multiset_permutations
from sympy import isprime
def A069869(n):
    smax, m = 0, 0
    if n==3 or n%3:
        for s, p in sorted(partitions(n,size=True),key=itemgetter(0),reverse=True):
            if s<smax:
                break
            for a in multiset_permutations(Counter(p).elements()):
                if isprime(k:=int(''.join(str(d) for d in a))):
                    m = max(k,m)
            if m>0:
                smax=s
    return m # _Chai Wah Wu_, Feb 21 2024

