# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A069686

from sympy import isprime
for p in filter(isprime, range(100, 855)):
    if isprime(int(str(p)[1:-1])): print(p) # _Jason Yuen_, Mar 28 2024

