# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A069588

from sympy import nextprime
def a(n): return 11 if n == 1 else nextprime(10**(n-1))
print([a(n) for n in range(1, 21)]) # _Michael S. Branicky_, Nov 11 2021

