# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A069865

def A069865(n):
    m, g = 1, 0
    for k in range(n+1):
        g += m
        m = m*(n-k)**6//(k+1)**6
    return g # _Chai Wah Wu_, Oct 04 2022

