# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A283902

from functools import lru_cache
@lru_cache(maxsize=None)
def A283902(n): # assumes n <= 11969
    if n < -701: return 0
    if -701<=n<=-698: return (4 if n&1 else 702)
    return A283902(n-A283902(n-1))+A283902(n-A283902(n-2)) # _Chai Wah Wu_, May 25 2026

