# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A283840

from itertools import product
def a283840(N):
    s=set()
    for x in product( range(N), repeat=N**2):
        sig=0
        for a in range(N):
            for b in range(N):
                for c in range(N):
                    sig = N*sig + x[N*x[N*a+b]+c]
        s.add(sig)
    return len(s)
# _Bert Dobbelaere_, Mar 31 2025

