# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A283321

from sympy import binomial, factorial
def T(n,k):
    if k==n: return factorial(n)//2
    elif k==n-1: return n**2 * factorial(n - 1) // 2
    else: return binomial(n, k)**2 * factorial(k)
i = 0
for n in range(10):
    for k in range(n + 1):
        if n < 2: print("1")
        else: print(T(n, k))
    i += 1 # _Indranil Ghosh_, Mar 16 2017

