# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A376993

from math import isqrt
from itertools import count
from sympy import isprime
def A376993(n):
    for k in count(isqrt(((a:=10**(n-1))<<1)-1>>2)):
        m = 2*k*(k+1)+1
        if m >= a and isprime(m):
            return m-a # _Chai Wah Wu_, Oct 13 2024

