# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A376550

from itertools import islice
from sympy import isprime, nextprime
from sympy.utilities.iterables import multiset_derangements as md
def f(n): return len(set(tuple(d) for d in md(list(str(n))) if isprime(int("".join(d)))))
def agen(): # generator of terms
    record, p = -1, 2
    while True:
        v = f(p)
        if v > record:
            yield p
            record = v
        p = nextprime(p)
print(list(islice(agen(), 26))) # _Michael S. Branicky_, Nov 27 2024

