# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A376296

def A376296(n):
    c = 0
    for x in range(n):
        for y in range(x,n):
            xy,xyp = x*y%n,(x+y)%n
            for z in range(y,n):
                xyz, xyzp = xy*z%n-1,(xyp+z)%n
                c += sum(not (xyz*w-xyzp)%n for w in range(z,n))
    return c # _Chai Wah Wu_, Sep 19 2024

