# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A376920

from sympy import isprime, nextprime
def A376920(n):
    p = n
    while (p:=nextprime(p)):
        if isprime(n**2+(p-n)**2) and not any(isprime(k**2+(p-k)**2) for k in range(1,min(n-1,p//2)+1)):
            return p # _Chai Wah Wu_, Oct 14 2024

