# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A376014

from math import comb
from itertools import takewhile
from sympy import divisors
def A376014(n): return sum(d**d*comb(n//d,d) for d in takewhile(lambda d:d**2<=n,divisors(n))) # _Chai Wah Wu_, Sep 06 2024

