# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A215014

# _Ely Golden_, Dec 26 2017
def consecutive(li):
  for i in range(len(li)-1):
    if(li[i+1]!=1+li[i]): return False
  return True
def sorted_digits(n):
  lst=[]
  while(n>0):
    lst+=[n%10] ; n//=10
  lst.sort() ; return lst
j=0
for i in range(1,10001):
  while(not consecutive(sorted_digits(j))): j+=1
  print(str(i)+" "+str(j)) ; j+=1
 # alternate for generating full sequence in seconds
from itertools import permutations as perms
frags = ["0123456789"[i:j] for i in range(10) for j in range(i+1, 11)]
afull = sorted(set(int("".join(s)) for f in frags for s in perms(f)))
print(afull[:70]) # _Michael S. Branicky_, Aug 04 2022

