# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A215894

import math
def modiv(a,b):
    return a - b*(a//b)
def modlg(a,b):
    return a // b**int(math.log(a,b))
for n in range(2,100):
    a = 2**n
    print(modlg(a,n), end=',')

