# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A161154

from fractions import gcd
i=j=1
while j<=100:
    if gcd(bin(i)[2:].count("0"),i)==1==gcd(bin(i)[2:].count("1"),i):
        print(str(j)+" "+str(i))
        j+=1
    i+=1 # _Indranil Ghosh_, Mar 08 2017

