# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A285227

from itertools import count, islice
from collections import Counter
from sympy.utilities.iterables import partitions, multiset_permutations
from sympy import isprime
def A285227_gen(): # generator of terms
    yield 7
    for l in count(2):
        for i in range(1,10):
            yield from sorted(q for q in (int(str(i)+''.join(map(str,j))) for s,p in partitions(7*l-i,m=l-1,k=9,size=True) for j in multiset_permutations([0]*(l-1-s)+list(Counter(p).elements()))) if isprime(q))
A285227_list = list(islice(A285227_gen(),30)) # _Chai Wah Wu_, Nov 29 2023

