# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A236346

import math
def getXY(n):
  y = int(math.sqrt(n*2))
  if n<=y*(y+1)/2: y-=1
  x = n - y*(y+1)/2
  return x, y
for n in range(1, 77):
  ox, oy = getXY(n*n)
  nx, ny = getXY((n+1)**2)
  print str(abs(nx-ox)+abs(ny-oy))+',',

