# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A163057

from sympy import sieve as A000040
def A163057(n): return n + A000040[n + 1] // 2 # _Karl-Heinz Hofmann_, Jul 23 2024

