# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A163511

from sympy import prime
def A163511(n):
    if n:
        k, c, m = n, 0, 1
        while k:
            c += 1
            m *= prime(c)**(s:=(~k&k-1).bit_length())
            k >>= s+1
        return m*prime(c)
    return 1 # _Chai Wah Wu_, Jul 17 2023

