# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A163491

def a(n): return (n+2)//3 if n%3==1 else a(n*2//3)
print([a(n) for n in range(1, 78)]) # _Michael S. Branicky_, Jan 16 2021

