# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A011538

def ok(n): return '8' in str(n)
print(list(filter(ok, range(290)))) # _Michael S. Branicky_, Aug 18 2021

