# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A327544

# see link for faster version
from itertools import product
def lrp(s): # longest repeated prefix (overlaps allowed)
  for i in range(len(s)-1, 0, -1):
    if s.find(s[:i], 1) >= 0: return s[:i]
  return ""
def a(n):
  if n == 1: return 2
  c = 0
  for p in product("01", repeat=n-1):
    b = "1" + "".join(p)
    if lrp(b) == lrp(b[::-1])[::-1]: c += 1
  return 2*c
print([a(n) for n in range(1, 17)]) # _Michael S. Branicky_, Feb 05 2021

