# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A327723

n, a, msdc = 0, 0, [1,0,0,0,0,0,0,0,0,0]
while n <= 62:
    print(n,a)
    s = str(a)
    msd = int(s[0])
    n, a = n+1, msdc[msd]*10+msd
    msdc[msd] = msdc[msd]+1 # _A.H.M. Smeets_, Sep 25 2019

