# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A327913

# After PARI implementation.
from functools import cache
@cache
def F(b, c, t, w):
    if w == 0:
        return 1 if t == 0 else 0
    return sum(
        sum(
            F(i, j, t + i - j, w - 1)
            for j in range((t + i - 1) // w, min(t + i, c) + 1)
        )
        for i in range(b + 1)
    )
A327913 = lambda n, m: F(n, n, 0, m)
for n in range(10):
    print([A327913(n, m) for m in range(0, 8)]) # _Peter Luschny_, Apr 09 2021

