# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A327933

from itertools import count, islice
from sympy import factorint
def A327933_gen(startvalue=2): # generator of terms >= startvalue
    return filter(lambda n: (m:=sum((n*e//p for p,e in factorint(n).items())))&1 and not m%3, count(max(startvalue,2)))
A327933_list = list(islice(A327933_gen(),40)) # _Chai Wah Wu_, Nov 04 2022

