# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A327235

from functools import lru_cache
from itertools import combinations
from fractions import Fraction
from math import prod, gcd, factorial
from sympy import mobius, divisors
from sympy.utilities.iterables import partitions
def A327235(n):
    if n == 0: return 1
    @lru_cache(maxsize=None)
    def b(n): return int(sum(Fraction(1<<sum(p[r]*p[s]*gcd(r,s) for r,s in combinations(p.keys(),2))+sum((q>>1)*r+(q*r*(r-1)>>1) for q, r in p.items()),prod(q**r*factorial(r) for q, r in p.items())) for p in partitions(n)))
    @lru_cache(maxsize=None)
    def c(n): return n*b(n)-sum(c(k)*b(n-k) for k in range(1,n))
    def a(n): return sum(mobius(n//d)*c(d) for d in divisors(n,generator=True))//n if n else 1
    return 1+b(n)-sum(a(i) for i in range(1,n+1)) # _Chai Wah Wu_, Jul 03 2024

