# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A327474

from itertools import count, islice
from sympy import totient
def A327474_gen(): # generator of terms
    a, b = 4, 6
    yield from (1,2,4,6)
    for n in count(3):
        a, b = b, (b<<1)-a+totient(n)
        yield b
A327474_list = list(islice(A327474_gen(),30)) # _Chai Wah Wu_, Feb 22 2023

