# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A290585

from sympy import isprime
A=[0, 1]
p=1
for n in range(2, 201):
    for k in range(n, -1, -1):
        if isprime(1 + k*p):
            A.append(k)
            p*=k
            break
print(A[1:]) # _Indranil Ghosh_, Aug 10 2017

