# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A013661

  # Use some guard digits when computing.
# BBP formula (3 / 16) P(2, 64, 6, (16, -24, -8, -6,  1, 0)).
from decimal import Decimal as dec, getcontext
def BBPzeta2(n: int) -> dec:
    getcontext().prec = n
    s = dec(0); f = dec(1); g = dec(64)
    for k in range(int(n * 0.5536546824812272) + 1):
        sixk = dec(6 * k)
        s += f * ( dec(16) / (sixk + 1) ** 2 - dec(24) / (sixk + 2) ** 2
                 - dec(8)  / (sixk + 3) ** 2 - dec(6)  / (sixk + 4) ** 2
                 + dec(1)  / (sixk + 5) ** 2 )
        f /= g
    return (s * dec(3)) / dec(16)
print(BBPzeta2(2000))  # _Peter Luschny_, Nov 01 2023

