# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A022559

from sympy import primepi, integer_nthroot
def A022559(n):
    c, j, v = 0, 1, 0
    while j <= n:
        k = n//j
        m = n//k
        c += k*(-v+(v:=sum(primepi(integer_nthroot(m,r)[0]) for r in range(1,m.bit_length()))))
        j = m+1
    return c # _Chai Wah Wu_, May 14 2026

