# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A234000

from itertools import count, islice
def A234000_gen(startvalue=1): # generator of terms >= startvalue
    return filter(lambda n:not (m:=(~n&n-1).bit_length())&1 and (n>>m)&7==1,count(max(startvalue,1)))
A234000_list = list(islice(A234000_gen(),30)) # _Chai Wah Wu_, Jul 09 2022
def A234000(n):
    def bisection(f,kmin=0,kmax=1):
        while f(kmax) > kmax: kmax <<= 1
        kmin = kmax >> 1
        while kmax-kmin > 1:
            kmid = kmax+kmin>>1
            if f(kmid) <= kmid:
                kmax = kmid
            else:
                kmin = kmid
        return kmax
    def f(x): return n+x-sum(((x>>(i<<1))-1>>3)+1 for i in range((x.bit_length()>>1)+1))
    return bisection(f,n,n) # _Chai Wah Wu_, Feb 14 2025

