# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A045336

from sympy import isprime
from itertools import count, product, takewhile
def primedigpals():
    for d in count(1, 2):
        for p in product("2357", repeat=d//2):
            left = "".join(p)
            for mid in "2357":
                yield int(left + mid + left[::-1])
def aupto(N):
    return list(takewhile(lambda x: x<=N, filter(isprime, primedigpals())))
print(aupto(10**7)) # _Michael S. Branicky_, Dec 18 2021

