# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A045710

from itertools import chain, count, islice
from sympy import primerange
def A045710_gen(): # generator of terms
    return chain.from_iterable(primerange((m:=10**l)<<2,5*m) for l in count(0))
A045710_list = list(islice(A045710_gen(),40)) # _Chai Wah Wu_, Dec 08 2024

