# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A045584

from itertools import islice, count
def A045584_gen(startvalue=1): # generator of terms >= startvalue
    kstart = max(startvalue,1)
    k3, k4 = 3**kstart, 4**kstart
    for k in count(kstart):
        if (k3+k4) % k == 0:
            yield k
        k3 *= 3
        k4 *= 4
A045584_list = list(islice(A045584_gen(),10)) # _Chai Wah Wu_, May 16 2022

