# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A045537

from itertools import count
def a(n):
    s = str(n)
    return next(e for e in count(2) if s in str(n**e))
print([a(n) for n in range(88)]) # _Michael S. Branicky_, Feb 23 2025

