# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A048543

def A048543(n):
    k, m = 1, 2
    while True:
        if str(m).count('7') == n:
            return k
        k += 1
        m += 2*k # _Chai Wah Wu_, Mar 23 2018

