# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A147574

from sympy import integer_log
from oeis_sequences.OEISsequences import bisection
def A147574(n):
    ptuple = (2, 3, 5, 7, 11, 13, 17)
    def g(x, m): return sum(g(x//(ptuple[m]**i), m-1) for i in range(1,integer_log(x, ptuple[m])[0]+1)) if m else x.bit_length()-1
    return bisection(lambda x: n+x-g(x,6),510510*n,510510*n) # _Chai Wah Wu_, Mar 18 2026

