# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A130901

def a(n): return sum(10**n//k for k in range(1, 10))
print([a(n) for n in range(20)]) # _Michael S. Branicky_, Jan 26 2021

