# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A359446

from sympy import n_order, nextprime
p = 3
best = 0
while True:
    if p!=5:
        period = n_order(10,p)
        k = (p-1)//period
        if k > best:
            best = k
            print(period, end=',')
    p = nextprime(p)

