# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A359400

def a(n): return sum(i for i, bi in enumerate(bin(n)[:1:-1], 1) if bi=='0')
print([a(n) for n in range(78)]) # _Michael S. Branicky_, Jan 09 2023

