# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A359356

def A359356(n, A=[0]):
  while len(A) <= n:
    t = 0
    while t in A or any(d not in str(t) for d in str(t+A[-1])):
      t += 1
    A.append(t)
  return A[n]

