# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A359803

def a(length):
    sequence = [1]
    while len(sequence) < length:
        last_term = sequence[-1]
        if last_term == 1:
            next_term = len(sequence)
        elif last_term % 2 == 0:
            next_term = last_term // 2
        else:
            next_term = 3 * last_term + 1
        sequence.append(next_term)
    return sequence

