# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A359469

from functools import reduce
from operator import iand
from sympy import factorint, primepi
def A359469(n):
    f = [(primepi(p)&1, int(e==1)) for p, e in factorint(n).items()]
    return reduce(iand,(e for p, e in f if not p),1)^reduce(iand,(e for p, e in f if p),1) # _Chai Wah Wu_, Jan 06 2023

