# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A351807

from math import prod
def pod(n): return prod(map(int, str(n)))
def ok(m): pdm = pod(m); return pdm > 0 and pod(m*m)%pdm == 0
print([m for m in range(124) if ok(m)]) # _Michael S. Branicky_, Feb 19 2022

