# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A351224

import numpy as np
def find_records(m):
    l=np.array([0]+[-1 for i in range(m-1)])
    for n in range(len(l)):
        path=[n+1]
        while path[-1]>m or l[path[-1]-1]==-1:
            if path[-1]%2==0:
                path.append(path[-1]//2)
            else:
                path.append(path[-1]*3+1)
        path.reverse()
        for i in range(1,len(path)):
            if path[i]<=m:
                l[path[i]-1]=l[path[0]-1]+i
    seq=[]
    c,lsteps,record=1,0,0
    for n in range(1,len(l)):
        if l[n]==lsteps:
            c+=1
        else:
            if c>record:
                record=c
                seq.append(c)
            c=1
        lsteps=l[n]
    return seq
print(", ".join([str(i) for i in find_records(1000000)]))

