# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A351355

def A351355(n): return 0 if n == 1 else n*n-sum(2*n//k for k in range(2,2*n))+sum(n//k for k in range(2,n)) # _Chai Wah Wu_, Feb 08 2022

