# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A383075

from itertools import count
from sympy import integer_nthroot
def A383075(n): return next(m for m in count(integer_nthroot(3*n,3)[0]) if not m*(m+1)*((m<<1)+1)%(6*n)) # _Chai Wah Wu_, Apr 21 2025

