# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A383777

from sympy import primefactors; mp = lambda x: (0 if x ==1 else x - min(primefactors(x)) if x%2 else 2*x+1)
def A383777(n, c = 0):
    while n != 0: n = mp(n); c += 1
    return c

