# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A383969

from sympy import isprime
from itertools import count
def a(n): return next(m for m in count(0, 2) if all(not isprime(m+2*i+1) for i in range(n)))
print([a(n) for n in range(1, 43)]) # _Michael S. Branicky_, May 23 2025

