# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A383430

def a(n):
    low = [0, 1, 2, 3, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 7, 8, 8, 9, 10, 10, 10]
    if n < len(low):
        return low[n]
    else:
        return a(n - 13) + 6

