# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A383578

from sympy import prime, factorial
def A383578(n):
    p, c = prime(n), 1
    f = factorial(p-1)+1
    a, b = divmod(f,p)
    while not b:
        c *= p
        f = a
        a, b = divmod(f,p)
    return c # _Chai Wah Wu_, May 12 2025

