# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A266551

from sympy import isprime, primefactors
def a(n): return 3*n + 1 if isprime(n) else n//min(primefactors(n))
print([a(n) for n in range(2, 101)]) # _Indranil Ghosh_, Apr 22 2017

