# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A229836

import math
import sympy
from sympy import sieve
x = 1
while x < 50:
    y = [i for i in sieve.primerange(math.factorial(x),x**x)]
    print(len(y))
    x += 1

