# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A263609

def decimal_to_quaternary(n):
    if n == 0:
        return '0'
    b = ''
    while n > 0:
        b = str(n % 4) + b
        n = n // 4
    return b
x = 0
counter = 0
while True:
    y = decimal_to_quaternary(x ** 2)
    if y == y[::-1]:
        print(int(decimal_to_quaternary(x)))
        counter += 1
    x += 1  # _Mattew Bondar_, Mar 10 2021

