# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A263715

from itertools import count, islice
from sympy import factorint
def A263715_gen(): # generator of terms
    return filter(lambda n: n & 3 != 2 or all(p & 3 != 3 or e & 1 == 0 for p, e in factorint(n).items()),count(0))
A263715_list = list(islice(A263715_gen(),30)) # _Chai Wah Wu_, Jun 28 2022

