# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A084837

from sympy import isprime
from itertools import count, islice, combinations_with_replacement as mc
def agen(): # generator of terms
    yield from (2, 3, 5, 7, 11)
    for d in count(2):
        nind = (int("".join(m+m[:-1][::-1])) for m in mc("9876543210", d))
        yield from sorted(filter(isprime, nind))
print(list(islice(agen(), 40))) # _Michael S. Branicky_, Jun 26 2022

