# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A084006

from itertools import count, islice
from math import prod, isqrt
from sympy import factorint
def A084006_gen(): # generator of terms
    for l in count(1):
        m = 10**l-1
        x = prod(p for p, e in factorint(m).items() if e&1)
        yield from (j**2*x*m for j in range(isqrt(10**(l-1)//x)+1,isqrt(m//x)+1))
A084006_list = list(islice(A084006_gen(),20)) # _Chai Wah Wu_, Mar 20 2025

