# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A205509

from math import factorial
def A205509(n): return ((f:=factorial(n-1))^f*n).bit_count() # _Chai Wah Wu_, Jul 13 2022

