# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A309377

from math import isqrt, prod
from sympy import factorint
def A309377(n): return (isqrt(n**n) if (c:=prod(n*e+1 for e in factorint(n).values())) & 1 else 1)*n**(n*(c//2)) # _Chai Wah Wu_, Jun 25 2022

