# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A309816

from sympy import n_order, prime
def A309816(n): return (~(m:=n_order(2,prime(n))) & m-1).bit_length() # _Chai Wah Wu_, Nov 10 2023

