# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A243374

import sympy
from sympy import isprime
def a(n):
  for k in range(1,10**5):
    if isprime(int(str(k)+str(n))) and isprime(int(str(n)+str(k))):
      return k
n = 1
while n < 100:
  print(a(n),end=', ')
  n += 1

