# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A243977

def a(n,p):
  lst = []
  for c in range(10**p+1):
    m = n**c%10**p
    if m in lst:
      return [c,c-lst.index(m)]
    else:
      lst.append(m)
def cou(n):
  if n % 10 == 0:
    return 0
  ww = []
  p = 2
  aa = a(n,p)[0]
  ww.extend(range(aa))
  while p < 100:
    newlst = ww
    w = []
    for i in newlst:
      m = n**i%10**p
      if len(str(m))==p and m%int('1'*p)==0:
        w.append(i)
    if w:
      ww = []
      for k in w:
        j = k
        while j <= a(n,p+1)[0]:
          ww.append(j)
          j += a(n,p)[1]
      ww.sort()
      p += 1
    else:
      return p-1
n = 2
while n < 100:
  if cou(n):
    print(cou(n),end=', ')
  else:
    print(0,end=', ')
  n += 1

