# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A009188

from sympy import primepi
def A009188(n):
    def f(x): return int(n+2+primepi(x)+primepi(x>>1))
    m, k = n+2, f(n+2)
    while m != k: m, k = k, f(k)
    return m # _Chai Wah Wu_, Oct 17 2024

