# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A300160

from itertools import combinations_with_replacement
A300160_list = []
for k in range(1, 16):
  a = [i**k for i in range(10)]
  for b in combinations_with_replacement(range(10), k):
    y = sum(map(lambda y:a[y], b))
    for x in (y-1,y+1):
      if x > 0 and tuple(int(d) for d in sorted(str(x))) == b:
        A300160_list.append(x)
print(sorted(A300160_list))  # _John Drake_, Mar 14 2023

