# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A079832

for i in range(1,1100):
    if int(str(i)[::-1])//i==3:
        print(i,end=', ')
# _Edward Jiang_, Aug 16 2014

