# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A356872

from sympy import factorint, isprime
from itertools import count, islice
def f(n): return 1 if isprime(n) else len(factorint(n))
def agen():
    n = 1
    for k in count(0):
        v = f(3*k+1)
        while v >= n: yield k; n += 1
print(list(islice(agen(), 7))) # _Michael S. Branicky_, Sep 02 2022

