# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A356329

from itertools import accumulate, groupby, repeat
def summarize(n, _): return int("".join(k+bin(len(list(g)))[2:] for k, g in groupby(str(n))))
def aupto(terms): return list(accumulate(repeat(1, terms), summarize))
print(aupto(11)) # _Michael S. Branicky_, Sep 18 2022

