# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A356847

from math import gcd
from itertools import count, islice
from sympy import isprime, nextprime
def agen(): # generator of terms
    alst = [5]
    while True:
        yield alst[-1]
        p = nextprime(alst[-1])
        while any(not isprime(ai + p - 1) for ai in alst):
            p = nextprime(p)
        alst.append(p)
print(list(islice(agen(), 9))) # _Michael S. Branicky_, Feb 23 2023

