# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A356690

from math import prod
from sympy import isprime
def A356690(n): return prod(m for i in (1,3,7,9) if isprime(m:=10*n+i)) if n else 210 # _Chai Wah Wu_, Sep 23 2022

