# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A356555

from sympy.ntheory import digits
def row(n): return [b for b in range(2, n+2) if n%sum(digits(n, b)[1:])==0]
print([an for n in range(1, 18) for an in row(n)]) # _Michael S. Branicky_, Aug 12 2022

