# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A356296

from sympy import fibonacci
def a(n): return pow(fibonacci(n), 2, n)
print([a(n) for n in range(1, 87)]) # _Michael S. Branicky_, Aug 04 2022

