# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A356434

from sympy import prevprime, nextprime
def A356434(n): return (r if (m:=nextprime(k:=1<<n)) > (k<<1)-(r:=prevprime(k)) else m) if n>1 else 2 # _Chai Wah Wu_, Aug 08 2022

