# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A163498

from sympy import prime, isprime
[prime(n) for n in range(1,1000) if isprime(int(bin(prime(n)).replace('1','01'),2))] # _Chai Wah Wu_, Jul 28 2014

