# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A163836

from sympy import factorint
def ok(n):
  f = factorint(n)
  return sum(f[p] for p in f) > 1 and 2*max(f) == sum(p*f[p] for p in f)
print(list(filter(ok, range(3571)))) # _Michael S. Branicky_, Apr 09 2021

