# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A238507

def StrInc(x):
  for n in range(10**5):
    count = 0
    i = 0
    string = str(3**n)
    if len(string) == x and x == 1:
      return n
    while i < len(string)-1:
      if int(string[i]) == int(string[i+1])-1:
        count += 1
        i += 1
      else:
        if count >= x-1:
          return n
        else:
          count = 0
          i += 1
    if count >= x-1:
      return n
x = 1
while x < 15:
  print(StrInc(x))
  x += 1

