# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A238454

def isqrt(a):
    sr = 1 << (int.bit_length(int(a)) >> 1)
    while a < sr*sr:  sr>>=1
    b = sr>>1
    while b:
        s = sr + b
        if a >= s*s:  sr = s
        b>>=1
    return sr
def a(n):
    nn = 2**(2*n+1)
    s = isqrt(nn)
    return (s+1)**2-nn
for n in range(77):  print(str(a(n)), end=',')

