# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A238714

def primfacs(n):
   i = 2
   primfac = []
   while i * i <= n:
       while n % i == 0:
           primfac.append(i)
           n //= i
       i += 1
   if n > 1:
       primfac.append(n)
   return primfac
def sopfr(n):
   plist = primfacs(n)
   l = len(plist)
   s = 0
   while l > 0:
       s += plist[l - 1]
       l -= 1
   return s
n = 2
max = 1000
lst = []
while n <= max:
   rem = n
   while rem > 1:
       last = sopfr(rem)
       rem = rem % last
   lst.append(last)
   n += 1
print(lst)

