# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A238628

from sympy.utilities.iterables import partitions
def A238628(n): return sum(1 for p in partitions(n) if n-max(p,default=0) in p) # _Chai Wah Wu_, Sep 21 2023

