# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A124661

from sympy import prime
A124661_list = []
for n in range(1,10**6):
    p = prime(n)
    for k in range(1,n-1):
        if prime(n-k)+prime(n+k) < 2*p:
            break
    else:
        A124661_list.append(p) # _Chai Wah Wu_, Jul 25 2017

