# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A036498

def A036498(n): return (n*(3*n-5)>>1)+1 if n&1 else n*(3*n-1)>>1 # _Chai Wah Wu_, Mar 25 2025

