# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A036839

def A036839(n):
    x = str(n+int(str(n)[::-1]))
    return int("".join(sorted(x))) # _Indranil Ghosh_, Jan 28 2017

