# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A178550

from sympy import isprime
print([i for i in range(1000) if str(i).count('1') == 1 and isprime(i)]) # _Daniel Starodubtsev_, Mar 29 2020

