# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A178244

from math import comb
def A178244(n): return comb(n.bit_length(),n.bit_count()) # _Chai Wah Wu_, Mar 13 2023

