# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A178366

def ok(n): s = str(n); return 5*len(s) < sum(map(int, s)) <= 6*len(s)
print(list(filter(ok, range(458)))) # _Michael S. Branicky_, Jun 29 2021

