# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A367360

def A367360(n): return (0, 10, 40, 90, 60, 50, 60, 90, 40, 10)[n%10]+int(str((n+1)**2)[0]) # _Chai Wah Wu_, Dec 22 2023

