# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A367962

from functools import cache
@cache
def a_row(n: int) -> list[int]:
    if n == 0: return [1]
    row = a_row(n - 1) + [0]
    for k in range(n): row[k] *= n
    row[n] = row[n - 1] + 1
    return row

