# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A367191

from sympy.abc import x,y
from sympy.solvers.diophantine.diophantine import diop_quadratic
def A367191(n): return max(diop_quadratic(x*(x+n)+n**2-y**2))[0] if n else 0 # _Chai Wah Wu_, Nov 11 2023

