# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A367340

def cp(n):
    y = int(str(n)[0])
    x = (n-y)%10
    k = n - y - 10*x
    kk = k + 10*x + y-1
    return k if k > 0 and int(str(kk)[0]) != y-1 else -1
def ok(n): return n > 0 and cp(n) > 0
print([k for k in range(1, 119) if ok(k)]) # _Michael S. Branicky_, Dec 18 2023

