# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A367363

from itertools import islice
def agen(): # generator of terms
    an, y = 1, 1
    while y:
        yield an
        an, y = an + 100*(an%100), 1
        y = next((y for y in range(1, 100) if str(an+y)[:2] == str(y)), 0)
        an += y
print(list(islice(agen(), 36))) # _Michael S. Branicky_, Nov 23 2023

