# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A367341

from itertools import islice
def ok(n):
    an, y = n, 1
    while y < 10:
        an, y = an + 10*(an%10), 1
        while y < 10:
            if str(an+y)[0] == str(y):
                an += y
                break
            y += 1
        if y < 10:
            return False
    return True
print([k for k in range(10**6) if ok(k)]) # _Michael S. Branicky_, Nov 15 2023

