# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A367175

from sympy import divisor_sigma, primefactors
def A367175(n): return divisor_sigma(n)-(sum(primefactors(n))<<1) # _Chai Wah Wu_, Nov 10 2023

