# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A367367

b = 1
while b <= 57:
    b, k, lhs, rhs = b+1, 1, b-1, b-1
    while lhs >= rhs:
        k += 1
        lhs, rhs = k*(b-1)**k, b**k-1
    print(k-1, end = ", ")

