# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A353503

from itertools import count, islice
from math import prod
from sympy import primepi, factorint
def A353503_gen(startvalue=1): # generator of terms >= startvalue
    return filter(lambda n: n == 1 or prod((f:=factorint(n)).values()) == prod(primepi(p)**e for p,e in f.items()), count(max(startvalue,1)))
A353503_list = list(islice(A353503_gen(),20)) # _Chai Wah Wu_, May 20 2022

