# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A353066

from sympy import divisors
def ok(n):
    counts = [0]*10
    for d in divisors(n, generator=True):
        for di in str(d): counts[int(di)] += 1
        if min(counts) > 2: return True
    return False
print([k for k in range(5455) if ok(k)]) # _Michael S. Branicky_, Apr 21 2022

