# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A184387

from sympy import divisor_sigma
def A184387(n): return (m:=divisor_sigma(n))*(m+1)>>1 # _Chai Wah Wu_, Jul 05 2023

