# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A144795

from sympy import Matrix
from oeis_sequences.OEISsequences import bisection
def A144795(n):
    def f(x):
        s = bin(x)[-1:1:-1]
        t = '0'+s+'0'
        return n+1+x-sum((Matrix([[2,-1,1],[1,0,0],[0,1,0]])**i*Matrix([1,1,0]))[0] for i in range(len(s)) if s[i]=='1' and not '010' in '0'+t[i+2:])-('010' not in t)
    return bisection(f,n,n) # _Chai Wah Wu_, Jun 10 2026

