# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A366842

from math import gcd
from sympy.utilities.iterables import partitions
def A366842(n): return sum(1 for p in partitions(n) if gcd(*(q for q in p if q&1))>1) # _Chai Wah Wu_, Oct 28 2023

