# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A366168

from math import lcm
from sympy import Poly, diff, bernoulli
from sympy.abc import x
def A366168(n): return lcm(*(c.q for c in Poly(diff(bernoulli(n,x),x,2)).coeffs())) if n>=3 else 1 # _Chai Wah Wu_, Oct 04 2023

