# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A369833

from itertools import permutations
from sympy import primerange, prime, Matrix
def A369833(n): return len({Matrix([p[i:0:-1]+p[:n-i] for i in range(n)]).per() for p in permutations(primerange(prime(n)+1))}) if n else 1 # _Chai Wah Wu_, Feb 11 2024

