# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A369791

from itertools import islice
from collections import Counter
def A369791_gen(): # generator of terms
    c, a = {0:1}, []
    while True:
        a.append(max(c.values()))
        yield a[-1]
        d = Counter(c)
        for k in c:
            for b in a:
                d[k+b] += c[k]
        c = d
A369791_list = list(islice(A369791_gen(),10)) # _Chai Wah Wu_, Feb 01 2024

