# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A369104

from sympy import pi, N;
def A369104(n):
    return list(map(int, str(N((pi*(pi-2))/(4+(pi-2)**2), n)).replace(".", "")))

