# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A006013

from math import comb
def A006013(n): return comb(3*n+1,n)//(n+1) # _Chai Wah Wu_, Jul 30 2022

