# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A380596

from itertools import combinations
def get_all_substrings(string):
    length = len(string) + 1
    return [string[x:y] for x, y in combinations(range(length), r=2)]
def is_palindrome(n):
    return str(n) == str(n)[::-1]
def ok(n):
    subsets = get_all_substrings(str(n))
    subsets = [subset for subset in subsets if is_palindrome(subset) and len(subset)>1 and len(subset)<len(str(n))]
    return len(subsets)>0
print([k for k in range (100,400) if ok(k)])

