# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A349792

from sympy import primerange
from statistics import median
def ok(n): return n>1 and int(median(primerange(n**2, (n+1)**2)))==n*(n+1)
print([k for k in range(999) if ok(k)]) # _Michael S. Branicky_, Dec 05 2021

