# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A349993

from math import isqrt
def A349993(n): return isqrt(n**3) - n + 1 # _Chai Wah Wu_, Dec 08 2021

