# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A273355

from sympy import isprime,prevprime,nextprime
for i in range(0,160000001,6):
  if isprime(i-1) and isprime(i+1) and prevprime(i-1) == i-47 and nextprime(i+1) == i+47: print (i,end=', ')

