# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A246135

from sympy import isprime
A246135 = []
for n in range(1,9):
    for m in range(n-1, -1, -1):
        l = ''.join([str(d) for d in range(n, m-1, -1)])
        p = int(l+l[-2::-1], 9)
        if isprime(p):
            A246135.append(p)
    for m in range(n+1, 9):
        l = ''.join([str(d) for d in range(n, m+1)])
        p = int(l+l[-2::-1], 9)
        if isprime(p):
            A246135.append(p)
A246135 = sorted(A246135)

