# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A246839

def a(n):
  s = 1
  for k in range(n+1):
    s *= k**k
  i = 1
  while not s % 10**i:
    i += 1
  return i-1
n = 1
while n < 100:
  print(a(n),end=', ')
  n += 1 # _Derek Orr_, Sep 04 2014
from sympy import multiplicity
A246839, p5 = [0,0,0,0,0], 0
for n in range(5,10**3,5):
    p5 += multiplicity(5,n)*n
    A246839.extend([p5]*5)
# _Chai Wah Wu_, Sep 05 2014

