# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A362951

from gmpy2 import mpz, hamdist
from sympy import totient
a = lambda n: hamdist(mpz(n), mpz(totient(n)))
print([a(n) for n in range(1, 87)])

