# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A362945

ispower5 = lambda n: n==round(n**.2)**5
is_A362945 = lambda n: ispower5(sum(int(d)**5 for d in str(n))+n)
def A362945(n, A=[0]):
    while len(A) < n:
        A.append(A[-1]+1)
        while not is_A362945(A[-1]): A[-1]+=1
    return A[n]

