# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A362429

from gmpy2 import is_prime
from sympy.ntheory import digits
from itertools import count, islice
def c(base, s=""):
    if base == 1: yield from (s:=s+"1"*n for n in count(1))
    else:
        yield from (s:=s+"".join(map(str, digits(n, base)[1:])) for n in count(1))
def a(n):
    if n == 1: return -1
    return next(k for k, t in enumerate(c(n), 1) if is_prime(int(t)))

