# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A336298

from sympy import prime, prevprime
def A336298(n):
    return prevprime(prime(n)//2+1) # _Chai Wah Wu_, Nov 26 2020

