# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A336644

from math import prod
from sympy.ntheory.factor_ import primefactors, core
def A336644(n): return (n-prod(primefactors(n)))//core(n) # _Chai Wah Wu_, Dec 30 2021

