# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A323192

for n in range(1,20000000):
    b1 = (1 << n.bit_length()) - 1
    n2 = n*n
    b2 = (1 << n2.bit_length()) - 1
    if b1-n > b2-n2:  print(str(n), end=', ')

