# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A323244

from sympy import divisor_sigma, primepi, factorint
def A323244(n): return (lambda n: (n<<1)-divisor_sigma(n))(sum((1<<primepi(p)-1)<<i for i, p in enumerate(factorint(n,multiple=True)))) if n > 1 else 0 # _Chai Wah Wu_, Mar 10 2023

