# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A295465

from math import comb
def A295465(n): return comb(30*n,15*n)*comb(15*n,3*n)*comb(3*n,n)//(comb(10*n,5*n)*comb(5*n,2*n)) # _Chai Wah Wu_, Feb 16 2026

