# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A295462

from math import comb
def A295462(n): return comb(15*n,5*n)*comb(2*n,n)//comb(6*n,n) # _Chai Wah Wu_, Feb 16 2026

