# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A295316

from sympy import factorint
def A295316(n): return int(all(map(lambda m:m&1,factorint(n).values()))) # _Chai Wah Wu_, Jan 04 2023

