# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A295446

from math import comb
def A295446(n): return comb(10*n,n)*comb(6*n,n)//comb(2*n,n) # _Chai Wah Wu_, Feb 15 2026

