# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A295087

from functools import reduce
from itertools import count, islice
def A295087_gen(): # generator of terms
    s = {0}
    yield 0
    for n in count(1):
        if (m:=sum(reduce(lambda x,y:(x[0],x[0]+x[1]) if int(y) else (x[0]+x[1],x[1]),bin(n)[-1:2:-1],(1,0)))) not in s:
            yield m
            s.add(m)
A295087_list = list(islice(A295087_gen(),20)) # _Chai Wah Wu_, May 18 2023

