# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A295450

from math import comb
def A295450(n): return comb(14*n,2*n)*comb(4*n,n)//comb(7*n,n) # _Chai Wah Wu_, Feb 15 2026

