# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A328981

def A328981(n): return ((n&1)|((~n & n-1).bit_length()&1))^1 # _Chai Wah Wu_, Jan 24 2023

