# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A004494

 # T(n, m) in A004489
def a(n): return T(n, 5)
print([a(n) for n in range(68)]) # _Michael S. Branicky_, May 03 2021

