# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A004165

def a(n): return int(str(n**3)[::-1])
print([a(n) for n in range(1, 45)]) # _Michael S. Branicky_, May 24 2022

