# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A334085

import math
from sympy import primerange
def a(n):
    b = 1
    for i in primerange(n):
        b *= i
    return math.gcd(n,b)

