# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A081415

from sympy import nextprime; p, q, r, s, t, u, v = 2, 3, 5, 7, 11, 13, 17
while v < 29000000:
    if p + v == q + u == r + t == 2*s: print(s, end = ', ')
    p, q, r, s, t, u, v = q, r, s, t, u, v, nextprime(v) # _Ya-Ping Lu_, May 11 2024

