# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A065428

from sympy import isprime
def ok(n): return not any(isprime((x**2)%n) for x in range(2, n))
print(list(filter(ok, range(1, 2000)))) # _Michael S. Branicky_, May 08 2021

