# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A227054

from sympy.ntheory.primetest import is_square
from sympy.solvers.diophantine.diophantine import diop_DN
def A227054(n):
    if is_square((n<<3)+1): return 1
    if is_square(n): return 0
    c, a, b = None, diop_DN(n,1-n), diop_DN(n,1)
    while c is None:
        a2 = []
        for r, s in a:
            if (sa:=abs(s))>1 and sa&1:
                c = min(c,sa) if c is not None else sa
            for t, u in b:
                w, d = r*u+s*t, r*t+s*u*n
                if (wa:=abs(w))>1 and wa&1:
                    c = min(c,wa) if c is not None else wa
                a2.extend([(d,w),(d,-w),(-d,w),(-d,-w)])
        a.extend(a2)
    return c*c-1>>3 # _Chai Wah Wu_, Oct 11 2025

