# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A227228

from sympy import divisors
def rev(n):
  r = ''
  for i in str(n):
    r = i + r
  return int(r)
for i in range(10**6):
  s = sum(divisors(i))-i
  if rev(i) == i and s > 10 and rev(s) == s:
    print(i,end=', ')
# simplified by _Derek Orr_, Oct 16 2014

