# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A227225

def DS(n):
  s = 0
  for i in str(n):
    s += int(i)
  return s
def DP(n):
  p = 1
  for i in str(n):
    p *= int(i)
  return p
for n in range(2000):
  k = 0
  while k**3 <= DS(n)+DP(n):
    if k**3 == DS(n)+DP(n):
      print(n,end=', ')
      break
    else:
      k += 1
## Edited by _Derek Orr_, Apr 10 2015

