# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A227948

from sympy import isprime
def DP(n):
  p = 1
  for i in str(n):
    p *= int(i)
  return p
{print(n,end=', ') for n in range(5000) if DP(n) and isprime(n+DP(n)) and isprime(n-DP(n))}
## Simplified by _Derek Orr_, Apr 05 2015

