# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A227064

from sympy import sieve as p
print([p[k] for k in range(3, 264) if p[k-1] - p[k-2] == p[k+2] - p[k+1]])
# _Karl-Heinz Hofmann_, May 04 2022

