# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A227993

from sympy import divisors
from fractions import Fraction
def ok(n):
    if n < 2: return False
    divs = divisors(n)
    f = sum(Fraction(dn, dd) for dn, dd in zip(divs[:-1], divs[1:]))
    return f.denominator == 1
print([k for k in range(70000) if ok(k)]) # _Michael S. Branicky_, Feb 06 2022

