# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A319744

for n in range(50):
  a = n
  b = 0
  c = 0
  while a:
    if ''.join(sorted(str(b))) != str(b) and ''.join(sorted(str(b)))[::-1] != str(b): c += b; a -= 1
    b += 1
  print(c)
from itertools import count, islice
def A319744_gen(): # generator of terms
    c = 0
    for n in count(101):
        l = len(s:=tuple(int(d) for d in str(n)))
        for i in range(1,l-1):
            if (s[i-1]-s[i])*(s[i]-s[i+1]) < 0:
                c += n
                yield c
                break
A319744_list = list(islice(A319744_gen(),30)) # _Chai Wah Wu_, Jul 28 2023

