# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A169936

from num2words import num2words
def alst(ALLBELOW=1000):
  out, ana = set(), dict()
  for i in range(ALLBELOW):
    key = "".join(sorted(num2words(i)))
    if key in ana: out.update([ana[key], i])
    else: ana[key] = i
  return sorted(out)
print(alst()) # _Michael S. Branicky_, Dec 14 2020

