# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A251240

from gmpy2 import gcd, is_square, is_prime, isqrt
A251240_list, l1, l2, s, b = [], 3, 2, 4, {}
for n in range(4,10**4):
    i = s
    while True:
        if not i in b and gcd(i,l1) == 1 and gcd(i,l2) > 1:
            l2, l1, b[i] = l1, i, 1
            while s in b:
                b.pop(s)
                s += 1
            if is_square(i) and is_prime(isqrt(i)):
                A251240_list.append(n)
            break
        i += 1
print(A251240_list) # _Chai Wah Wu_, Dec 06 2014

