# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A394016

def row(n):
    r = []
    for k in range(1, n*n + 1):
        found = 0
        for a in range(1, n+1):
            if k % a == 0 and k//a <= n:
                found = 1
                break
        r.append(found)
    return r
# triangle
a = []
for n in range(1, 6):
    a.extend(row(n))
print(a)

