# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A394815

from sympy import divisor_sigma, gcd, isprime
def ok(k):
    return isprime(k-1) and isprime(k+1) and gcd(k, divisor_sigma(k)) == 2
print([k for k in range(1, 600000) if ok(k)])

