# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A394554

from itertools import count, islice
from sympy import factorint
def agen(): # generator of terms
    wlst, adict, n = [set(factorint(1+i)) for i in range(4)], dict(), 2
    for m in count(1):
        v = len(wlst[0] | wlst[1] | wlst[2] | wlst[3])
        if v >= n and v not in adict:
            adict[v] = m
            while n in adict:
                yield adict[n]
                n += 1
        wlst = wlst[1:] + [set(factorint(m+4))]
print(list(islice(agen(), 15))) # _Michael S. Branicky_, May 05 2026

