# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A394258

from sympy import prime, primefactors, prevprime
SEARCH_GOAL = 120 # Find this many terms
def is_prime_complete(n):
   pf = primefactors(n)
   return prime(len(pf)) == pf[-1]
last_prime_complete, results = 4, []
while len(results) < SEARCH_GOAL:
   results.append(prevprime(last_prime_complete))
   last_prime_complete += 2
   while not is_prime_complete(last_prime_complete): last_prime_complete += 2
print(results)

