# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A394110

from math import comb
def A394110(n):
    return comb(3*n, n)*(7*n+3)//(n+1)//(2*n+1)

