# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A036013

from sympy import isprime
from itertools import count
a,p = [2],2
for _ in range(100):
    q = next(filter(lambda x:isprime(x*p-1), count(2)))
    p = p*q
    a.append(q)
print(a) # _Nicholas Stefan Georgescu_, Mar 06 2023

