# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A330243

A330243_list = [n for n in range(10**3) if str(2**n)[0] == '7'] # _Chai Wah Wu_, Dec 12 2019

