# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A330591

from decimal import *
n=1000
for j in range(2,n):
  i=6**j+1
  count=0
  while(i!=1):
    if(i%2==0):
      i=i//2
    else:
      i=3*i+1
    count=count+1
  print(count)

