# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A331701

from sympy import isprime
TOP = 10**5
primePowers={}
primePowers[1]=1
for x in range(2,TOP):
    if isprime(x):
        p = pp = x
        while pp < TOP**2:
            pp *= p
            primePowers[pp] = 1
a=[]
pps = sorted(primePowers.keys())[:]
for pp in pps:
    for p in pps:
        if p*2 > pp: break
        if (pp-p) in primePowers:
            print(pp)
            a.append(pp)
            break
print(sorted(a))

