# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A318742

from math import isqrt
def A318742(n): return -(s:=isqrt(n))**4 + sum((q:=n//k)*(3*k*(k-1)+q**2+1) for k in range(1,s+1)) # _Chai Wah Wu_, Oct 21 2023

