# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A046808

from gmpy2 import is_prime
from itertools import count, islice
def agen(): # generator of terms
    an = 1
    while True:
        yield an
        an = next(k for k in count(an+1) if is_prime(an*(1<<k) + 1))
print(list(islice(agen(), 18))) # _Michael S. Branicky_, Aug 12 2025

