# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A046838

def ok(n):
    s, t = str(n), str(n**2)
    return any(s == t[:i]+t[j:] for i in range(len(t)) for j in range(i, len(t)+1))
print([k for k in range(900000) if ok(k)]) # _Michael S. Branicky_, Sep 12 2025

