# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A054248

def A054248(n):
    s, i, z = n - (n-1) % 2, n-1, 1
    while 0 <= i: s += i; i -= z; z += z
    return s
print([A054248(n) for n in range(1, 55)]) # _Peter Luschny_, Nov 30 2017

