# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A057660

from math import gcd
def A057660(n): return sum(n//gcd(n,k) for k in range(1,n+1)) # _Chai Wah Wu_, Aug 24 2023

