# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A057168

def a(n): u = n&-n; v = u+n; return (((v^n)//u)>>2)+v
print([a(n) for n in range(1, 72)]) # _Michael S. Branicky_, Jul 10 2022 after _Charles R Greathouse IV_
def A057168(n): return ((n&~(b:=n+(a:=n&-n)))>>a.bit_length())^b # _Chai Wah Wu_, Mar 06 2025

