# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A007318

from math import comb, isqrt
def A007318(n): return comb(r:=(m:=isqrt(k:=n+1<<1))-(k<=m*(m+1)),n-comb(r+1,2)) # _Chai Wah Wu_, Nov 11 2024

