# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A053006

from sympy import n_order
def A053006_gen(startvalue=1): # generator of terms >= startvalue
    return filter(lambda n:n_order(2,(n<<1)-1)&1,count(max(startvalue,1)))
A053006_list = list(islice(A053006_gen(),20)) # _Chai Wah Wu_, Feb 07 2023

