# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A053344

def A053344(n):
    a, b = divmod(n,25)
    c, d = divmod(b,10)
    return a+c+sum(divmod(d,5)) # _Chai Wah Wu_, Nov 08 2022

