# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A053004

from mpmath import mp, agm, sqrt
mp.dps=106
print([int(z) for z in list(str(agm(1, sqrt(2))).replace('.', '')[:-1])]) # _Indranil Ghosh_, Jul 11 2017

