# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A053600

from gmpy2 import digits, mpz, is_prime
A053600_list, p = [2], 2
for _ in range(30):
    m, ps = 1, digits(p)
    s = mpz('1'+ps+'1')
    while not is_prime(s):
        m += 1
        ms = digits(m)
        s = mpz(ms+ps+ms[::-1])
    p = s
    A053600_list.append(int(p)) # _Chai Wah Wu_, Apr 09 2015

