# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A373317

from num2words import num2words
def n2w(n): return "".join(c for c in num2words(n).replace(" and", "") if c.isalpha())
def ok(n):
    d = [ord(c) - ord('A') + 1 for c in n2w(n).upper()]
    if sum(d) < n: return False
    return any(abs(sum(d[:i])-sum(d[i:])) == n for i in range(1, len(d)))
print([k for k in range(1005) if ok(k)]) # _Michael S. Branicky_, Jun 03 2024

