# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A373893

from fractions import Fraction
from sympy.ntheory.continued_fraction import continued_fraction
def A373893(n): return len(continued_fraction(sum(Fraction(1 if k&1 else -1,k) for k in range(1,n+1))))-1 # _Chai Wah Wu_, Jun 27 2024

