# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A373965

from math import gcd
from itertools import count, islice
from sympy import integer_nthroot
def A373965_gen(): # generator of terms
    alist, a, b = [1], 1, False
    yield 1
    while True:
        for m in count(a+1):
            if all(gcd(m,d) == 1 for d in alist):
                if (x:=integer_nthroot(a:=m,2))[1]: yield x[0]
                alist = alist[(b:=not b):]+[a]
                break
A373965_list = list(islice(A373965_gen(),40)) # _Chai Wah Wu_, Jun 25 2024

