# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A373048

from math import isqrt, factorial
def A373048(n): return isqrt((m:=factorial(n))*(n+1))-isqrt(m) # _Chai Wah Wu_, Aug 03 2024

