# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A373043

from sympy.ntheory.primetest import is_square
def A373043(n): return sum(1 for k in range(3,n) for j in range(2,k) if is_square(j*k*n)) # _Chai Wah Wu_, May 31 2024

