# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A086204

from sympy import isprime
def conv(s, b): return sum(b**k for k, bk in enumerate(s[::-1]) if bk=='1')
def ok(s, n): return all(isprime(conv(s, b)) for b in range(2, n+1))
def a(n):
    if n < 4: return 2
    k = 3
    while not ok(bin(k)[2:], n): k += 2
    return int(bin(k)[2:], 2)
print([a(n) for n in range(2, 9)]) # _Michael S. Branicky_, Oct 10 2021

