# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A368366

from itertools import count, islice
def AGM(g): # generator of AGM transform of sequence given by generator g
    S, P = 0, 1
    for n, an in enumerate(g, 1):
        S += an
        P *= an
        yield S**n-n**n*P
print(list(islice(AGM(count(1)), 15))) # _Michael S. Branicky_, Jan 24 2024

