# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A368372

from fractions import Fraction
from sympy import harmonic
def A368372(n): return (Fraction(n+1,2)-Fraction(n,harmonic(n))).numerator # _Chai Wah Wu_, Jan 25 2024

