# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A025281

from sympy import factorial, factorint
def A025281(n): return sum(p*e for p, e in factorint(factorial(n)).items()) # _Chai Wah Wu_, Apr 09 2021

