# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A379426

from sympy import isprime, nextprime
m = p = 0
while p < 500:
    p = nextprime(p); m = 10*m + p
    if isprime(m): print(m, end = ', ')

