# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A379596

from itertools import count
from sympy.ntheory.primetest import is_square
def A379596(n): return next(k for k in count(1) if is_square(k**2+(k+n)**2)) # _Chai Wah Wu_, Mar 02 2025

