# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A377083

from itertools import count, islice
def f(n): return (d:=list(map(int, str(n))))[0] * sum(di*di for di in d)
def ok_count(n):
    if n == 1: return True, 0
    traj, c = {n}, 0
    while (n:=f(n)) not in traj: traj.add(n); c += 1
    return 1 in traj, c
def agen(): # generator of terms
    for n in count(1):
        elated, iterations = ok_count(n)
        if elated: yield iterations
print(list(islice(agen(), 90))) # _Michael S. Branicky_, Oct 16 2024

