# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A020956

prpr = 0
prev = 1
for n in range(2,100):
    print(prev, end=", ")
    curr = prpr+prev + n//2
    prpr = prev
    prev = curr
# _Alex Ratushnyak_, Jul 30 2012

