# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A103364

from functools import cache
@cache
def T(n: int, k: int) -> int:
    if n == k: return 1
    elif k == 1: return -sum(T(n, j) for j in range(2, n + 1))
    elif 1 < k < n: return T(n - 1, k - 1) * n * (n - 1) // (k * (k - 1))
    return 0
for n in range(1, 10): print([T(n, k) for k in range(1, n + 1)])  # _Peter Luschny_, May 17 2026

