# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A159684

from math import isqrt
def A159684(n): return -isqrt(m:=(n+1)**2<<1)+isqrt(m+(n<<2)+6)-1 # _Chai Wah Wu_, Aug 03 2022

