# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A043562

def a(n): return len(s:=str(n))-sum(1 for i in range(1, len(s)) if s[i-1] == s[i])
print([a(n) for n in range(90)]) # _Michael S. Branicky_, Jan 08 2025 after _Charles R Greathouse IV_

