# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A292384

from sympy.core.cache import cacheit
from sympy import factorint, prevprime, prod
def a064989(n):
    f = factorint(n)
    return 1 if n == 1 else prod(prevprime(i)**f[i] for i in f if i != 2)
def a252463(n): return 1 if n==1 else n//2 if n%2==0 else a064989(n)
@cacheit
def a(n): return 1 if n==1 else 4*a(a252463(n)) + n%4
print([a(n) for n in range(1, 51)]) # _Indranil Ghosh_, Sep 21 2017

