# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A338576

from math import isqrt
from sympy import divisor_count
def A338576(n): return (isqrt(n) if (c:=divisor_count(n)) & 1 else 1)*n**(c//2+1) # _Chai Wah Wu_, Jun 25 2022

