# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A273050

def ROR(n):                # returns A038572(n)
    BL = len(bin(n))-2
    return (n>>1) + ((n&1) << (BL-1))
def ROL(n):                # returns A006257(n) for n>0
    BL = len(bin(n))-2
    return (n*2) - (1<<BL) + 1
print('0', end=',')
for n in range(1,100000):
    if  ROR(n) ^ ROL(n) == n: print(n, end=',')

