# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A273161

from math import comb
def A273161(n):
    c, j = 0, 1
    while j <= n:
        k = n//j
        m = n//k
        c += comb(n-j+1,k)-comb(n-m,k)
        j = m+1
    return c # _Chai Wah Wu_, May 14 2026

