# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A363694

 # Inefficient but works
import sympy
m = 100
dict1 = {}
for n in range(1,m):
    edges = 0
    for i in sympy.primerange(n):
        for j in sympy.primerange(n):
            if i != j and i + j <= n:
                edges += 1
    dict1[n] = int(edges/2)
print(dict1.values())

