# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A363762

from itertools import count, islice
from sympy import factorint
def A363762_gen(startvalue=1): # generator of terms >= startvalue
    for n in count(max(startvalue,1)):
        for k in range(n>>1,((n+1)**2<<1)+1):
            c = 0
            for m in range(k**2+1,(k+1)**2):
                if all(p==2 or p&3==1 or e&1^1 for p, e in factorint(m).items()):
                    c += 1
                    if c>n:
                        break
            if c==n:
                break
        else:
            yield n
A363762_list = list(islice(A363762_gen(),20)) # _Chai Wah Wu_, Jun 22 2023

