# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A363497

from math import isqrt
A363497 = [0]
for n in range(1,50): A363497.append(A363497[-1] + isqrt(n)**3)
print(A363497) # _Karl-Heinz Hofmann_, Jun 14 2023

