# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A363031

from sympy import divisor_sigma
def A363031(n): return divisor_sigma(6*n+1) # _Chai Wah Wu_, Sep 07 2023

