# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A003053

def size_binary_orthogonal_group(n):
    k = n-1
    if k%2==0:
        m=k//2
        p=2**(m**2)
        for i in range(1,m+1):
            p*=4**i-1
    else:
        m=(k+1)//2
        p=2**(m**2)
        for i in range(1,m):
            p*=4**i-1
    return p
#call and print output for a(n)
print([size_binary_orthogonal_group(n) for n in range(1, 10)])
# _Nathan J. Russell_, Nov 01 2017

