# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A003053

from math import prod
def A003053(n): return (1 << (n//2)**2)*prod((1 << i)-1 for i in range(2,2*((n-1)//2)+1,2)) # _Chai Wah Wu_, Jun 20 2022

