# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A007088

def a(n): return int(bin(n)[2:])
print([a(n) for n in range(40)]) # _Michael S. Branicky_, Jan 10 2021
from itertools import product
n = 4
for p in product([0, 1], repeat=n): print(''.join(str(x) for x in p))
# _Peter Luschny_, Jan 22 2024

