# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A007376

A007376_list = [int(d) for n in range(10**2) for d in str(n)] # _Chai Wah Wu_, Feb 04 2015

