# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A007018

from itertools import islice
def A007018_gen(): # generator of terms
    a = 1
    while True:
        yield a
        a *= a+1
A007018_list = list(islice(A007018_gen(),9)) # _Chai Wah Wu_, Mar 19 2024

