# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A357571

from fractions import Fraction
from math import factorial, comb
def A357571(n): return int(factorial(n)**2*sum(Fraction(1<<(n-j<<2),3*factorial(n-j))*sum((1+i)*(2+i)*factorial(4+i)*comb(14+j+(i<<1),j-i)*(-1 if (j-i)&1 else 1)<<(j-i) for i in range(j+1)) for j in range(n+1)))>>4 # _Chai Wah Wu_, Apr 20 2023

