# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A357019

from sympy.abc import x, y
from sympy.solvers.diophantine.diophantine import diop_quadratic
def A357019(n): return max((a for a,b in diop_quadratic(x*(x-y)+y**2-n)),default=0) # _Chai Wah Wu_, Sep 12 2022

