# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A357589

from itertools import islice
def A357589_gen(): # generator of terms
    a, b, i = 1, 1, 1
    while True:
        yield from (j-a for j in range(i,i+a))
        i += a
        a, b = b, a+b
A357589_list = list(islice(A357589_gen(),30)) # _Chai Wah Wu_, Oct 13 2022

