# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A368275

from functools import cache
@cache
def a(n):
  if n < 3: return [1,1,2][n]
  x, y = (n-1)>>1, n>>1
  if n & 1 == 1: return a(x) + a(x-1) + 1
  else: return a(y) + a(y+1) + 1
print([a(n) for n in range(0,67)])

