# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A368431

from itertools import islice
from functools import reduce
def uniq(r): return reduce(lambda u, e: u if e in u else u+[e], r, [])
def agen():  # generator of terms
    R, aset = [["0", "1"]], set()
    while R:
        r = R.pop(0)
        for b in r:
            d = int(b, 2)
            if d not in aset: yield d; aset.add(d)
        if len(r) > 1: R.append(uniq([r[k]+"0" for k in range(1, len(r))]))
        R.append(uniq([r[0]+"0", r[0]+"1"] + [r[k]+"1" for k in range(1, len(r))]))
print(list(islice(agen(), 70))) # _Michael S. Branicky_, Dec 24 2023

