# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A248080

from mpmath import *
mp.dps=102
xi=1/(1 + sqrt(e))
C = log(xi)**2/2 + log(xi) + polylog(2, xi) - pi**2/12 + 1
print([int(n) for n in list(str(C)[2:-1])]) # _Indranil Ghosh_, Jul 04 2017

