# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A195199

from math import prod
from itertools import count
from collections import Counter
from sympy import factorint
def A195199(n):
    f = Counter(factorint(n))
    d = prod(e+1 for e in f.values())
    for m in count(2):
        if prod(e+1 for e in (f+Counter(factorint(m))).values()) > 2*d:
            return m*n # _Chai Wah Wu_, Feb 28 2022

