# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A210513

import numpy as np
from functools import reduce
def factors(n):
    return reduce(list.__add__, ([i, n//i] for i in range(1, int(n**0.5) + 1) if n % i == 0))
for i in range(1, 2000):
    p1=int(str(i)+str(i)+"7")
    if len(factors(p1))<3:
        print(p1, end=',')
from sympy import isprime
from itertools import count, islice
def agen(): yield from filter(isprime, (int(str(k)+str(k)+'7') for k in count(1)))
print(list(islice(agen(), 36))) # _Michael S. Branicky_, Jul 26 2022

