# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A001751

from sympy import primepi
def A001751(n):
    def bisection(f,kmin=0,kmax=1):
        while f(kmax) > kmax: kmax <<= 1
        while kmax-kmin > 1:
            kmid = kmax+kmin>>1
            if f(kmid) <= kmid:
                kmax = kmid
            else:
                kmin = kmid
        return kmax
    def f(x): return int(n+x-primepi(x)-primepi(x>>1))
    return bisection(f,n,n) # _Chai Wah Wu_, Oct 17 2024

