# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A001614

from math import isqrt
def A001614(n): return (m:=n<<1)-(k:=isqrt(m))-int((m<<2)>(k<<2)*(k+1)+1) # _Chai Wah Wu_, Jul 26 2022

