# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A001843

[((n-2)//2*(n-1)//3 - int(n%6 == 0)) * n // 4 for n in range(4, 50)]
# _Andrey Zabolotskiy_, Jan 28 2021

