# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A001988

from sympy import legendre_symbol as L, primerange, prime, nextprime
def isok(p, oddpn):
    for q in primerange(3, oddpn + 1):
        if L(p, q)!=-L(-1, q): return 0
    return 1
def a(n):
    oddpn=prime(n + 1)
    p=3
    while True:
        if p%8==7:
            if isok(p, oddpn): return p
        p=nextprime(p) # _Indranil Ghosh_, Oct 23 2017, after PARI code by _Michel Marcus_

