# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A211889

from sympy import isprime, prime, primorial, primepi
def A211889(n):
    if n == 1:
        return 1
    delta = primorial(primepi(n))
    p, d = prime(n), delta
    while True:
        q = p
        for _ in range(n):
            q += d
            if not isprime(q):
                break
        else:
            return d
        d += delta # _Chai Wah Wu_, Jun 28 2019

