# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A056624

from sympy import factorint
def A056624(n): return 1<<sum(e&1^1 for e in factorint(n).values()) # _Chai Wah Wu_, Aug 03 2024

