# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A056653

from sympy import composite
def A056653(n): return composite(n) if n>1 else 1 # _Chai Wah Wu_, Jul 31 2024

