# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A056733

def a():
  for i in range(1,10):
    for j in range(10):
      for k in range(10):
        if i**3 + j**3 + k**3 == i*100 + j*10 + k:
          print(i*100 + j*10 + k)
  for i in range(10,100):
    for j in range(100):
      for k in range(100):
        if i**3 + j**3 + k**3 == i*10000 + j*100 + k:
          print(i*10000 + j*100 + k)
  for i in range(100,1000):
    for j in range(1000):
      for k in range(1000):
        if i**3 + j**3 + k**3 == i*1000000 + j*1000 + k:
          print(i*1000000 + j*1000 + k)
a()
# _Denys Contant_, Feb 23 2017

