# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A034704

def a(n):
    if n < 10: return n
    d = sorted(map(int,list(str(n))))
    for q in [1,0]:
        while q in d and (i := d.index(q)) != len(d)-1:
            d.pop(i)
            d[-1] = (d[-1]*10)+q
    for q, r in [(2, 5), (3, 3)]:
        if (len(d)) == 1: return d[0]
        if d[-2] == q and d[-1] <= r:
            d.pop(-2)
            d[-1] = (d[-1]*10)+q
    for i in range(len(d)-2,-1,-1): d[i] = d[i] ** d[i+1]
    return d[0] # _Dominic McCarty_, Mar 15 2025

