# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A034947

def A034947(n):
    s = bin(n)[2:]
    m = len(s)
    i = s[::-1].find('1')
    return 1-2*int(s[m-i-2]) if m-i-2 >= 0 else 1 # _Chai Wah Wu_, Apr 08 2021
def A034947(n): return -1 if n>>(-n&n).bit_length()&1 else 1 # _Chai Wah Wu_, Feb 26 2025

