# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A034180

from itertools import count, islice
def A034180_gen(): # generator of terms
    for l in count(1):
        clist = []
        for k in range(1,10):
            a, b = 10**l-k, 10**(l-1)-k
            for m in range(1,10):
                q, r = divmod(m*a-1,10*k-1)
                if r == 0 and b <= q - k <= a:
                    clist.append(10*q+m)
        yield from sorted(clist)
A034180_list = list(islice(A034180_gen(),20)) # _Chai Wah Wu_, Apr 23 2022

