# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A089589

from itertools import islice
from num2words import num2words
def agen(): yield from (k for k in range(10**6) if "i" not in num2words(k))
print(list(islice(agen(), 60))) # _Michael S. Branicky_, Aug 04 2022

