# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A045177

from sympy.ntheory import count_digits
def ok(n): c = count_digits(n, b=5); return c[0] == c[2] == 1
print([k for k in range(354) if ok(k)]) # _Michael S. Branicky_, Oct 27 2021

