# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A045345

from itertools import accumulate, count, islice
from sympy import prime
def A045345_gen(): return (i+1 for i, m in enumerate(accumulate(prime(n) for n in count(1))) if m % (i+1) == 0)
A045345_list = list(islice(A045345_gen(),5)) # _Chai Wah Wu_, Feb 23 2022

