# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A045547

from functools import reduce
from itertools import count, islice
from sympy.ntheory.factor_ import digits
def A045547_gen(startvalue=1): # generator of terms
    return filter(lambda n:2==reduce(lambda x,y:x*y%10,((1,1,2,6,4)[a]*((6,2,4,8)[i*a&3] if i*a else 1) for i, a in enumerate(digits(n,5)[-1:0:-1])))*6%10, count(max(startvalue,1)))
A045547_list = list(islice(A045547_gen(),30)) # _Chai Wah Wu_, Dec 07 2023

