# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A045309

from itertools import count, islice
from sympy import isprime
def A045309_gen(): # generator of terms
    yield from (2,3)
    yield from filter(isprime, count(5,6))
A045309_list = list(islice(A045309_gen(),48)) # _Chai Wah Wu_, Apr 28 2025

