# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A258484

def moda(n,a,m):
    kk = 0
    while n > 0:
        na=int(n%m)
        kk= kk+a**na
        n =int(n//m)
    return kk
for c in range (1, 10**8):
    for a in range (1,20):
        if  c==moda(c,a,10):
            print (a,c)

