# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A035497

from sympy import isprime
def swb(n): return sum(map(lambda x: x*x, map(int, str(n))))
def happy(bd):
    while bd not in [1, 4]: bd = swb(bd) # iterate to fixed point or cycle
    return bd == 1
def ok(n): return isprime(n) and happy(n)
def aupto(n): return [k for k in range(1, n+1) if ok(k)]
print(aupto(2012)) # _Michael S. Branicky_, Jul 13 2022

