# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A110529

from re import split
from sympy import isprime
def ternary (n):
    if n == 0:
        return '0'
    nums = []
    while n:
        n, r = divmod(n, 3)
        nums.append(str(r))
    return ''.join(reversed(nums))
seq_list, n = [],1
while len(seq_list) < 10000:
    for d in split('1+|2+', ternary(n)[1:]):
        if isprime(len(d)):
            seq_list.append(n)
    n += 1
# _W. Zane Billings_, Jun 28 2019

