# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A110751

from sympy import primefactors
A110751 = [n for n in range(1,10**5) if primefactors(n) == primefactors(int(str(n)[::-1]))] # _Chai Wah Wu_, Aug 14 2014

