# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A018900

print([n for n in range(1, 3001) if bin(n)[2:].count("1")==2]) # _Indranil Ghosh_, Jun 03 2017
A018900_list = [2**a+2**b for a in range(1,10) for b in range(a)] # _Chai Wah Wu_, Jan 24 2021

