# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A018837

 def a(n): return 3 if n == 1 else (n + n % 4) // 2 # _Elisha Hollander_, Aug 05 2021

