# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A335497

a1 = 1; print(a1, end =', '); S = str(a1)
for n in range(2, 100): ct = S.count(str(a1)); S += str(ct); print(ct, end = ', '); a1 = ct # _Ya-Ping Lu_, Dec 16 2021

