# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A335663

Used = [(1, 2)]
def bfun(num):
    print("a(1)=2")
    for i in range(2, num + 1):
        if any(i in coordinate for coordinate in Used):
            for j in range(0, len(Used) + 1):
                if i in Used[j]:
                    print("a(" + str(i) + ")=" + str(Used[j][0]))
                    break
        else:
            Used.append((i, i + 2 * len(Used) + 1))
            print("a(" + str(i) + ")=" + str(i + 2 * len(Used) - 1))
bfun(70)

