# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A335051

from numba import njit
@njit
def hasdigits01(n, b):
    has0, has1 = False, False
    while n >= b:
      n, r = divmod(n, b)
      if r == 0: has0 = True
      if r == 1: has1 = True
      if has0 and has1: return True
    return has0 and (has1 or n==1)
@njit
def a(n, start=2):
  k = start
  while True:
    for b in range(n, 1, -1):
      if not hasdigits01(k, b): break
    else: return k
    k += 1
anm1 = 2
for n in range(2, 21):
  an = a(n, start=anm1)
  print(an, end=", ")
  anm1 = an # _Michael S. Branicky_, Feb 09 2021

