# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A335924

import math
n_max = 1000000
a_last = 0
list1 = [a_last]
print(0)
for n in range(1, n_max+1):
    m1 = a_last - n
    m2 = a_last + math.ceil(n/2)
    if m1 >= 0 and m1 not in list1:
        a = m1
    elif m2 not in list1:
        a = m2
    else:
        a = a_last + n
    list1.append(a)
    print(a)
    a_last = a

