# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A335296

def a(n):
    b = [1];
    for i in range(2,n+1):
        b.append(b.count(b[-1]));
    prev = {tuple(b):1};
    m = 1;
    while(True):
        b.append(b.count(b[-1]));
        del b[0];
        m += 1;
        if(tuple(b) in prev):
            return prev[tuple(b)]
        else:
            prev[tuple(b)] = m;

