# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A095287

from sympy import isprime
i=1
j=1
while j<=250:
    if isprime(i) and bin(i)[2:].count("1")<=1+bin(i)[2:].count("0"):
        print(str(j)+" "+str(i))
        j+=1
    i+=1 # _Indranil Ghosh_, Feb 03 2017

