# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A136371

 # uses A136370gen() and imports from A136370
from sympy import isprime
def agen(): yield from (k for k, ak in enumerate(A136370gen(), 1) if isprime(ak))
print(list(islice(agen(), 5))) # _Michael S. Branicky_, Jun 26 2022

