# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A361877

from functools import cache
@cache
def A361877(n: int) -> int:
    if n < 2: return n + 1
    return ((4*n - 2)**2 * A361877(n-1)) // (n*n)
print([A361877(n) for n in range(21)])  # _Peter Luschny_, Nov 17 2025

