# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A361181

from math import prod
from sympy import factorint
def ispal(n): return (s:=str(n)) == s[::-1]
def ok(n): return ispal(sum(f:=factorint(n))) and ispal(prod(f))
print([k for k in range(2, 999) if ok(k)]) # _Michael S. Branicky_, Mar 06 2023

