# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A361902

from sympy import isprime,fibonacci
from itertools import count
def A361902(n):
    # Note: the function hangs if a(n) = -1.
    return next(k for k in count() if isprime(n+fibonacci(k)))

