# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A361648

from math import comb
from itertools import accumulate
def A361648(n):
    if n<=1:
        return 1
    blist = (0,1)
    for _ in range((m:=n>>1)-1):
        blist = tuple(accumulate(reversed(blist),initial=0))
    return blist[-1]*sum(blist)*comb(n,m) if n&1 else blist[-1]**2*comb(n,m) # _Chai Wah Wu_, Apr 16 2023

