# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A361257

from collections import Counter
def A361257(n): return sum(j*n**i for i, j in Counter(j.bit_count() for j in range(n+1)).items()) # _Chai Wah Wu_, Mar 06 2023

