# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A361289

from sympy import factorint, prevprime
# Stale copy of code for is_A005153 deleted, please see there. Code duplication potentially creates important problems. - _M. F. Hasler_, Jun 19 2023
A361289 = []
for odds in range(3,192,2):
    prime = prevprime(odds)
    while not is_A005153(odds - prime): prime = prevprime(prime)
    A361289.append(odds - prime)
print(A361289) # _Karl-Heinz Hofmann_, Mar 08 2023

