# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A357680

from sympy import isprime
from math import factorial
from itertools import product
def a(n):
    f = [2*factorial(i) for i in range(1, n+1)]
    t = sum(f)//2
    return sum(1 for s in product([0, 1], repeat=n-1) if isprime(t-sum(f[i] for i in range(n-1) if s[i])))
print([a(n) for n in range(1, 20)]) # _Michael S. Branicky_, Oct 15 2022

