# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A357907

def a(n): return (2*pow(75, n-1, 65537) - 1)%65537
print([a(n) for n in range(1, 43)]) # _Michael S. Branicky_, Oct 23 2022

