# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A357489

from itertools import count, islice
def A357489_gen(): # generator of terms
    for n in count(1):
        yield from sorted((1<<n-1)+(1<<x+(y:=m//6)-1)+(1<<y-1) for x in range(1,n) if (m:=2*n-5*x)>0 and 6*(n-x)>m and m%6==0)
A357489_list = list(islice(A357489_gen(),40)) # _Chai Wah Wu_, Nov 02 2022

