# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A357077

from sympy import factorint
def is033942(n): return sum(factorint(n).values()) > 2
def ok(n): return is033942(n) and is033942(n+1)
print([k for k in range(400) if ok(k)]) # _Michael S. Branicky_, Sep 10 2022

