# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A055018

from itertools import count, islice
def modest(n):
    pow10 = 1
    while (t:= divmod(n, pow10))[0]:
        if t[1] and n%t[1] == t[0]: return True
        pow10 *= 10
    return False
def agen(start=1): # generator of terms >= start
    modestk = modest(start-1)
    for k in count(start):
        modestk1, modestk = modestk, modest(k)
        if modestk and modestk1: yield k-1
print(list(islice(agen(), 38))) # _Michael S. Branicky_, Dec 08 2025

