# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A055037

from functools import reduce
from operator import ixor
from sympy import factorint
def A055037(n): return sum(1 for i in range(1,n+1) if not (reduce(ixor, factorint(i).values(),0)&1)) # _Chai Wah Wu_, Jan 01 2023

