# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A055032

from sympy import Integer
def a(n): return ((sum(m**(n - 1) for m in range(1, n)) + 1)/Integer(n)).denominator # _Indranil Ghosh_, May 17 2017

