# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A055411

# uses Python code for A046895
def A055411(n): return A046895(m:=n**2)+(sum(A046895(m-k**2) for k in range(1,n+1))<<1) # _Chai Wah Wu_, Jun 23 2024

