# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A120613

from math import isqrt
def A120613(n): return (m:=(n+isqrt(5*n**2)>>1)-n)+isqrt(5*m**2)>>1 # _Chai Wah Wu_, Aug 26 2022

