# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A120004

def A120004(n):
    s = str(n)
    m = len(s)
    return len(set(int(s[i:j]) for i in range(m) for j in range(i+1,m+1))) # _Chai Wah Wu_, Oct 19 2021

