# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A324903

from sympy import divisor_sigma
def A324903(n): return int((~(m:=int(divisor_sigma(n)))&m-1).bit_length()>(~n&n-1).bit_length()) # _Chai Wah Wu_, Jul 11 2022

