# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A324902

from sympy import divisor_sigma
def A324902(n): return (~(m:=n|int(divisor_sigma(n))-n) & m-1).bit_length() # _Chai Wah Wu_, Jul 01 2022

