# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A248217

def A248217(n): return 6*binomial(pow(2,n) +1, 3)
print([A248217(n) for n in range(41)]) # _G. C. Greubel_, Dec 26 2024

