# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A246600

from sympy import divisors
def A246600(n):
    return sum(1 for d in divisors(n) if n|d == n)
# _Chai Wah Wu_, Sep 06 2014

