# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A246520

def A246520(n):
    return(max(int(bin(n-k)[2:]+bin(n+k)[2:],2) for k in range(n+1)))
# _Chai Wah Wu_, Sep 07 2014

