# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A188902

from sympy import divisor_count, Integer
def a(n): return (divisor_count(n) / 2).numerator()
print([a(n) for n in range(2, 51)])  # _Indranil Ghosh_, May 27 2017

