# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A188044

from math import isqrt
def A188044(n): return isqrt(n**2<<1)-isqrt((n-4)**2<<1)-5 if n>3 else (1,0,1)[n-1]

