# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A188065

from sympy import integer_nthroot
from itertools import count, islice
def inthrt(n, r): return integer_nthroot(n, r)[0]
def A188065_gen(root=3): # generator of terms
    for d in count(1): # digits of nth power
        seen, repeated = dict(), set()
        for i in range(inthrt(10**(d-1), root), inthrt(10**d-1, root)+1):
            key = "".join(sorted(str(i**root)))
            if key in seen: repeated.update([seen[key], i])
            else: seen[key] = i
        yield from sorted(repeated)
print(list(islice(A188065_gen(), 77))) # _Michael S. Branicky_, May 27 2024

