# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A344879

from math import prod, lcm
from sympy import factorint
def A344879(n): return prod(a := tuple(p**(e+int(p==2))-1 for p, e in factorint(n).items()))//lcm(*a) # _Chai Wah Wu_, Jun 15 2022

