# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A141430

def A141430(n): return (2, 7, 1, 2, 5, 7, 7, 2, 8, 7, 4, 2)[n%12] if n>1 else 1 # _Chai Wah Wu_, Apr 17 2023

