# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A217397

def A217397(n): return n+(35*10**(len(str(9*n-8))-1))//9 # _Chai Wah Wu_, Dec 07 2024

