# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A369515

from sympy.ntheory.generate import prime
from math import ceil
def get_column_tops(n):
    return [1 + abs((n-1)-2*m) for m in range(1,n-1)]
def get_indices(rowNum):
  left=(rowNum*(rowNum-1))//2
  right=left+rowNum-1
  return (left, right)
def get_least(m,seq):
  mult=2
  d=m*mult
  while d in seq:
    mult+=1
    d=m*mult
  return d
seq,rnum = ([],1)
while len(seq)<56:
  seq.append(prime(rnum+max(0,rnum-2)))
  cols = get_column_tops(rnum)
  for k in range(len(cols)):
      ndcs=get_indices(cols[k])
      if k<ceil(len(cols)/2):
        m=seq[ndcs[0]]
        seq.append(get_least(m,seq))
      else:
        m=seq[ndcs[1]]
        seq.append(get_least(m,seq))
  if rnum > 1:
    seq.append(prime(2*rnum-1))
  rnum+=1
seq=[0,1]+seq
print(seq)

