# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A369698

from math import factorial
def A369698(n): return ((n*(n+1))**(m:=n<<1)>>m) - n**n*factorial(n)**3 # _Chai Wah Wu_, Jan 29 2024

