# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A369765

from collections import Counter
from sympy import prime
def A369765(n):
    c = {0:1,1:1}
    for k in range(1,n):
        p, d = prime(k), Counter(c)
        for j in c:
            d[j+p] += c[j]
        c = d
    return max(c.values()) # _Chai Wah Wu_, Feb 01 2024

