# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A120498

from itertools import count, islice
from math import prod, gcd
from sympy import primefactors
def A120498_gen(startvalue=1): # generator of terms >= startvalue
    for c in count(max(startvalue,1)):
        pc = set(primefactors(c))
        for a in range(1,(c>>1)+1):
            b = c-a
            if gcd(a,b)==1 and c>prod(set(primefactors(a))|set(primefactors(b))|pc):
                yield c
                break
A120498_list = list(islice(A120498_gen(),30)) # _Chai Wah Wu_, Oct 19 2023

