# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A120046

from math import isqrt
from sympy import primepi, primerange, integer_nthroot
from oeis_sequences.OEISsequences import bisection
def A120046(n):
    n10 = 10**n
    def f(x): return int(n10+x-sum(primepi(x//(k*m*r*s))-d for a,k in enumerate(primerange(integer_nthroot(x,5)[0]+1)) for b,m in enumerate(primerange(k,integer_nthroot(x//k,4)[0]+1),a) for c,r in enumerate(primerange(m,integer_nthroot(x//(k*m),3)[0]+1),b) for d,s in enumerate(primerange(r,isqrt(x//(k*m*r))+1),c)))
    return bisection(f,n10,n10) # _Chai Wah Wu_, Jun 03 2026

