# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A277021

from sympy import primorial, primepi, prime, factorint
def a002110(n): return 1 if n<1 else primorial(n)
def a276085(n):
    f=factorint(n)
    return sum([f[i]*a002110(primepi(i) - 1) for i in f])
def a053645(n): return n - 2**(n.bit_length()-1)
def b(n): return n + 1 if n<2 else prime(1 + (len(bin(n)[2:]) - bin(n)[2:].count("1"))) * b(a053645(n))
def a(n): return a276085(b(n - 1))
print([a(n) for n in range(1, 101)]) # _Indranil Ghosh_, Jun 22 2017

