# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A277561

def A277561(n):
    return sum(int(not (~(n+2*k) & 2*k) | (~n & k)) for k in range(n+1))

