# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A277885

from sympy import factorint, primepi, isprime, primefactors
def a049084(n): return primepi(n)*(1*isprime(n))
def a055396(n): return 0 if n==1 else a049084(min(primefactors(n)))
def a028234(n):
    f = factorint(n)
    return 1 if n==1 else n/(min(f)**f[min(f)])
def a067029(n):
    f=factorint(n)
    return 0 if n==1 else f[min(f)]
def a(n): return 0 if n==1 else a055396(n) if a067029(n)>1 else a(a028234(n)) # _Indranil Ghosh_, May 15 2017

