# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A277030

from sympy import totient
def a(n):
    m=0
    if n==1: return 0
    else:
        while True:
            m+=1
            b=1
            while (b**totient(n))%n==(b**m)%n:
                b+=1
                if b>n: return m
print([a(n) for n in range(1, 101)]) # _Indranil Ghosh_, Jul 29 2017, after PARI code

