# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A249991

TOP = 100000
a = list(range(TOP))
for step in range(2,TOP):
  numBlocks = (len(a)-1) // step
  if numBlocks==0:  break
  a = a[:(1+numBlocks*step)]
  for pos in range(1,len(a),step):
    a[pos:pos+step] = a[pos+step-1:pos-1:-1]
  print(a[1], end=', ')
  a[1:] = a[2:]

