# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A249067

def a(n):
   got = [0]*10
   i = 1
   while sum(got)<9:
      d=int(str(n*i)[0])
      got[d] = 1
      i += 1
   return i-1

