# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A082755

from sympy import nextprime, isprime
from itertools import count, islice, product
def onlypd(n): return set(str(n)) <= set("2357")
def agen():
    yield from [2, 3, 5]
    for digits in count(2):
        for p in product("2357", repeat=digits-1):
            for end in "37":
                t = int("".join(p) + end)
                if isprime(t) and onlypd(nextprime(t)):
                    yield t
print(list(islice(agen(), 40))) # _Michael S. Branicky_, Mar 11 2022

