# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A082850

S = []; [S.extend(S + [n]) for n in range(1, 8)]
print(S) # _Michael S. Branicky_, Jul 02 2022

