# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A346744

def a(n): return sum((k**(n-k) + (n-k)**k)%n == 0 for k in range(1, n))
print([a(n) for n in range(1, 101)]) # _Michael S. Branicky_, Jul 31 2021

