# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A346068

from sympy import factorint, isprime, primepi
def ok(n):
    f = factorint(n)
    if not all(isprime(e) for e in f.values()): return False
    return all(isprime(primepi(p)) for p in f)
print(list(filter(ok, range(35000)))) # _Michael S. Branicky_, Jul 30 2021

