# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A346879

from sympy import divisors
def a(n): return sum(divisors(2*n-1)[1:-1])
print([a(n) for n in range(1, 79)]) # _Michael S. Branicky_, Aug 19 2021

