# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A318755

from sympy import divisor_count
def A318755(n): return sum(divisor_count(k)**3 for k in range(1,n+1)) # _Chai Wah Wu_, Oct 26 2025

