# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A374263

from sympy import totient
def A374263(n): return (sum(totient(n) for n in range(1,n+1,2))>>1) + sum(totient(n) for n in range(2,n+1,2)) # _Chai Wah Wu_, Aug 04 2024

