# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A300902

from __future__ import division
from sympy import isprime
A300902_list, m = [1], 1
for n in range(1,501):
    m *= n
    A300902_list.append(m)
    if isprime(n):
        m //= n # _Chai Wah Wu_, Mar 16 2018

