# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A132296

from sympy import integer_nthroot
def A132296(n): return n*(n+1)-(((r:=integer_nthroot(n,3)[0])*(r+1))**2>>1)>>1 # _Chai Wah Wu_, Sep 03 2024

