# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A084561

from math import isqrt, comb
from sympy.ntheory.primetest import is_square
from oeis_sequences.OEISsequences import bisection
def A084561(n):
    def f(x):
        s = bin(x)[-1:1:-1]
        m = x.bit_count()
        l = x.bit_length()
        a = is_square(m)
        c = n+x-a
        for i in range(l):
            j = int(s[i])
            if j:
                m -= 1
                for p in range(isqrt(m)+(not is_square(m)),isqrt(l)+1):
                    c -= comb(i,p**2-m)
        return c
    return bisection(f,n-1,n-1) # _Chai Wah Wu_, Jun 08 2026

