# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A084007

from itertools import count, islice
from math import prod, isqrt
from sympy import factorint
def A084007_gen(): # generator of terms
    for l in count(1):
        m = 10**l-1
        x = prod(p for p, e in factorint(m).items() if e&1)
        y = isqrt(x*m)
        yield from (j*y for j in range(isqrt(10**(l-1)//x)+1,isqrt(m//x)+1))
A084007_list = list(islice(A084007_gen(),30)) # _Chai Wah Wu_, Mar 20 2025

