# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A084188

from math import isqrt
def A084188(n): return isqrt(1<<(n<<1)+1) # _Chai Wah Wu_, Jan 24 2024

