# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A084126

from sympy import primepi, primerange, primefactors
def A084126(n):
    def bisection(f,kmin=0,kmax=1):
        while f(kmax) > kmax: kmax <<= 1
        kmin = kmax >> 1
        while kmax-kmin > 1:
            kmid = kmax+kmin>>1
            if f(kmid) <= kmid:
                kmax = kmid
            else:
                kmin = kmid
        return kmax
    def f(x): return int(n+x+((t:=primepi(s:=isqrt(x)))*(t-1)>>1)-sum(primepi(x//p) for p in primerange(s+1)))
    return min(primefactors(bisection(f,n,n))) # _Chai Wah Wu_, Apr 03 2025

