# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A351741

from sympy import primeomega
def afind(limit, startk=1):
    k = startk
    sk = "".join(str(i) for i in range(1, k))
    skr = "".join(str(i) for i in range(k-1, 0, -1))
    for k in range(startk, limit+1):
        sk += str(k)
        skr = str(k) + skr
        if primeomega(int(sk)) == primeomega(int(skr)):
            print(k, end=", ")
afind(23) # _Michael S. Branicky_, Feb 17 2022

