# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A283776

import math
from sympy import sqrt
print([n for n in range(1, 126) if int(math.floor(n*sqrt(3)))%2==1]) # _Indranil Ghosh_, Mar 21 2017

