# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A283986

from functools import reduce
def A283986(n): return sum(reduce(lambda x,y:(x[0],x[0]+x[1]) if int(y) else (x[0]+x[1],x[1]),bin(n)[-1:2:-1],(1,0)))|sum(reduce(lambda x,y:(x[0],x[0]+x[1]) if int(y) else (x[0]+x[1],x[1]),bin(n-1)[-1:2:-1],(1,0))) # _Chai Wah Wu_, May 05 2023

