# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A283811

 def A283811(n): return 120*6**n - 240*5**n + 150*4**n - 30*3**n + 2**n  # _Indranil Ghosh_, Mar 17 2017

