# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A350246

from itertools import count, islice
from sympy import isprime
def A350246_gen(): # generator of terms
    yield 11
    s = '11'
    while True:
        for k in count(3,3):
            t = str(k)
            m = int(t+s)
            if isprime(m) and isprime(m+2):
                yield k
                break
        s = t+s
A350246_list = list(islice(A350246_gen(),20)) # _Chai Wah Wu_, Jan 12 2022

