# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A350233

from itertools import count, islice
def A350233gen(): return filter(lambda n:(m := int(str(n)[::-1])) % 5 and not m % 4,filter(lambda n: n % 4 and not n % 5,count(1)))
A350233_list = list(islice(A350233gen(),20)) # _Chai Wah Wu_, Dec 21 2021

