# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A350346

from itertools import count, islice
def A350346_gen(): # generator of terms
    yield 0
    for n in count(1):
        s = bin(n)[2:]
        c, l = 0, len(s)
        for i in range(l):
            c += int(s[l-i-1])
            if 2*c <= i:
                break
        else:
            yield int(s)
A350346_list = list(islice(A350346_gen(),20)) # _Chai Wah Wu_, Dec 30 2021

