# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A152535

from sympy import prime, primerange
def A152535(n): return (n-1)*(p:=prime(n))-sum(primerange(p)) # _Chai Wah Wu_, Jan 01 2024

