# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A109351

from sympy import integer_nthroot
from sympy.ntheory.factor_ import antidivisors
A109351_list = [n for n in range(2,10**4) if integer_nthroot(sum(antidivisors(n)),3)[1]] # _Chai Wah Wu_, Jun 13 2015

