# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A109652

from math import isqrt
from sympy import prime
def A109652(n): return prime(n+isqrt(5*n**2)>>1) # _Chai Wah Wu_, Aug 10 2022

