# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A109019

from sympy import factorint
def Omega(n): return sum(factorint(n).values())
def ok(n): return n != (r:=int(str(n)[::-1])) and Omega(n) == Omega(r)
print([k for k in range(300) if ok(k)]) # _Michael S. Branicky_, Mar 05 2026

