# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A115304

def A115304(n): # according to Formula by _Alan Michael Gómez Calderón_
    m = 4**floor(log(n,4))-1
    return n^m # _A.H.M. Smeets_, Apr 01 2025

