# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A115364

def A115364(n): return (m:=((~n & n-1).bit_length()+1))*(m+1)>>1 # _Chai Wah Wu_, Jul 02 2022

