# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A051640

from sympy.ntheory.factor_ import digits
def A051640(n):
    m = 0
    while True:
        for b in range(2,n+1):
            if b-1 not in digits(m,b)[1:]:
                break
        else:
            return m
        m += 1 # _Chai Wah Wu_, May 18 2020

