# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A085410

from sympy import divisors, divisor_count, npartitions, mobius
def a006128(n): return sum([divisor_count(m)*npartitions(n - m) for m in range(1, n + 1)])
def a(n): return sum([mobius(n/d)*a006128(d) for d in divisors(n)]) # _Indranil Ghosh_, Apr 25 2017

