# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A085060

def A085060(n): return (3*(k:=n+1)*3**(m:=(-k&k).bit_length())>>m)-1 # _Chai Wah Wu_, Feb 26 2025

