# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A167508

import re
from num2words import num2words
from unidecode import unidecode
def A167508(n): return len(set(re.sub("[^a-z]", "", unidecode(num2words(n, lang='fr'))))) # _Chai Wah Wu_, Jun 13 2021

