# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A344983

f = open("M77232917.txt", "a")
f.write(str(pow(2, 77232917)-1))
f.close() # _Karl-Heinz Hofmann_, Jun 06 2021
from gmpy2 import mpz
def A344983(n): return int((mpz(2)**77232917-1)//mpz(10)**(46498849-n) % 10) # _Chai Wah Wu_, Jun 07 2021

