# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A344550

from itertools import product
def pals(d, base=10): # returns a string
  digits = "".join(str(i) for i in range(base))
  for p in product(digits, repeat=d//2):
    if d//2 > 0 and p[0] == "0": continue
    left = "".join(p); right = left[::-1]
    for mid in [[""], digits][d%2]:
        if left + mid + right != '0': yield left + mid + right
def auptod(dd):
  yield 0
  for d in range(1, dd+1):
    yield from (int(p+p[-1-d%2::-1]) for p in pals((d+1)//2))
print([np for np in auptod(6)]) # _Michael S. Branicky_, May 22 2021

