# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A344129

 # uses get_coordinate(n) in A296030
KM=[(2, 1), (1, 2), (-1, 2), (-2, 1), (-2, -1), (-1, -2), (1, -2), (2, -1)]
def next_moves(i, j): return [(i+k, j+m) for k, m in KM]
def a(n):
    start, goal, steps = (0, 0), get_coordinate(n), 0
    reach, expand = {start}, {start}
    while goal not in reach:
        reach1 = set(m for i, j in expand for m in next_moves(i, j))
        expand = reach1 - reach
        steps, reach, reach1 = steps + 1, reach | reach1, set()
    return steps
print([a(n) for n in range(1, 101)]) # _Michael S. Branicky_, Jun 15 2021

