# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A060946

from itertools import accumulate, count, islice
def A060946_gen(): # generator of terms
    yield from accumulate((k**(k-1) for k in count(1)))
A060946_list = list(islice(A060946_gen(),20)) # _Chai Wah Wu_, Jun 17 2022

