# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A060461

from sympy import isprime; from sys import maxsize as oo
is_A060461 = lambda n: not (isprime(n*6-1) or isprime(n*6+1))
def A060461(n = None, first = oo, start = 1, end = oo):
    "Return the n-th term or a generator of up to 'first' terms less than 'end', starting at 'start'."
    if n: first = n
    seq = (m for m,_ in zip(filter(is_A060461, range(start,end)), range(first)))
    return max(seq) if n else seq
list(A060461(first=20)) # _M. F. Hasler_, Jul 10 2025

