# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A006047

from sympy.ntheory import digits
def A006047(n): return 3**(s:=digits(n,3)).count(2)<<s.count(1) # _Chai Wah Wu_, Apr 24 2025

