# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A132739

def A132739(n):
    a, b = divmod(n, 5)
    while b == 0:
        a, b = divmod(a,5)
    return 5*a+b # _Chai Wah Wu_, Dec 05 2021

