# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A106497

from itertools import count, islice
from sympy import sqrt_mod
def A106497_gen(): # generator of terms
    for j in count(0):
        b = 10**j
        a = b*10+1
        for k in sorted(sqrt_mod(0,a,all_roots=True)):
            if a*b <= k**2 < a*(a-1):
                yield k
A106497_list = list(islice(A106497_gen(),10)) # _Chai Wah Wu_, Feb 19 2024

