# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A027829

from math import isqrt
from itertools import count, islice
def A027829_gen(): # generator of terms
    return filter(lambda n: (s:=str(n))[:(t:=(len(s)+1)//2)]==s[:-t-1:-1], map(lambda n: n**2, (d for l in count(2,2) for d in range(isqrt(10**(l-1))+1,isqrt(10**l)+1))))
A027829_list = list(islice(A027829_gen(),3)) # _Chai Wah Wu_, Jun 23 2022

