# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A027856

from itertools import islice
from heapq import heappop, heappush
from sympy import isprime
def A027856_gen(): # generator of terms
    yield from (4,6)
    h, hset = [2,3], {2,3}
    while True:
        m = heappop(h)
        if isprime(m-1) and isprime(m+1):
            yield m
        for p in (4,6,9):
            mp = m*p
            if mp not in hset:
                heappush(h,mp)
                hset.add(mp)
A027856_list = list(islice(A027856_gen(),50)) # _Chai Wah Wu_, Apr 04 2026

