# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A071364

from math import prod
from sympy import prime, factorint
def A071364(n): return prod(prime(i+1)**p[1] for i,p in enumerate(sorted(factorint(n).items()))) # _Chai Wah Wu_, Sep 16 2022

