# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A071317

from itertools import count, islice, accumulate
def A071317_gen(): # generator of terms
    return accumulate(map(lambda n:sum(map(int,str(n**2))),count(0)))
A071317_list = list(islice(A071317_gen(),20)) # _Chai Wah Wu_, Mar 15 2023

