# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A071101

from math import log
a0,a1,a2,a3,n = 130,45,16,5,3
print(0,a3)
print(1,a2)
print(2,a1)
print(3,a0)
while log(a0)/log(10) < 1000:
    a0,a1,a2,a3,n = 2*(a0+a1+a2)-a3,a0,a1,a2,n+1
    print(n,a0) # _A.H.M. Smeets_, Sep 12 2018

