# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A264868

from sympy.core.cache import cacheit
from sympy import binomial
@cacheit
def a(n):
    return 1 if n<3 else sum([(-1)**(k + 1)*binomial(n + 1 - 2*k, k)*a(n - k) for k in range(1, (n + 1)//3 + 1)])
print([a(n) for n in range(1, 26)]) # _Indranil Ghosh_, Aug 30 2017

