# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A167171

from math import isqrt
from sympy import primepi, primerange
from oeis_sequences.OEISsequences import bisection
def A167171(n):
    def f(x): return int(n+x+(t:=primepi(s:=isqrt(x)))+(t*(t-1)>>1)-sum(primepi(x//k) for k in primerange(1, s+1)))-primepi(x)
    return bisection(f,n,n) # _Chai Wah Wu_, Mar 08 2026

