# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A167416

from sympy import sieve, isprime
from itertools import permutations
for n in range(1, 20):
    sieve.extend_to_no(n)
    p = list(map(str, list(sieve._list)))[:n]
    mint = 10**1000
    for i in permutations(p, len(p)):
        t = int(''.join(i))
        if  t < mint and isprime(t):
            mint = t
    if mint == 10**1000:
        print(0, end = ', ')
    else:
        print(mint, end = ', ') # _Gleb Ivanov_, Dec 04 2021

