# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A382434

from math import comb
def A382434(n): return (sum((comb(n,j)*(m:=n-(j<<1)+1)//(m+j))**4 for j in range((n>>1)+1))<<1)-1 # _Chai Wah Wu_, Mar 25 2025

