# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A382102

def f(s, r):
    return int(s) if (s:=s.replace(r, "")) != "" else 0
def a(n):
    s = str(n)
    return min(f(s, d) for d in set(s))
print([a(n) for n in range(1, 88)]) # _Michael S. Branicky_, Mar 16 2025

