# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A253315

def a(n):
    r = 0
    b = 0
    while n > 0:
        if (n & 1):
            r = r ^ b
        b = b + 1
        n = n >> 1
    return r
print([a(n) for n in range(20)])

