# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A253902

from sympy import integer_nthroot
def A253902(n): return (k:=(m:=integer_nthroot(3*n,3)[0])+(6*n>m*(m+1)*((m<<1)+1))+2)*(k*((k<<1)-9)+13)//6-n # _Chai Wah Wu_, Nov 05 2024

