# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A100440

from numba import njit
@njit()
def aupton(terms):
  aset, alst = set(), []
  for n in range(1, terms+1):
    for i in range(1, n+1):
      for j in range(i, n+1):
        aset.add(i*j + j*n + n*i)
    alst.append(len(aset))
  return alst
print(aupton(50)) # _Michael S. Branicky_, Mar 23 2021

