# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A100223

A100223 = [1, 0, 1]
for n in range(3, 801):
    A100223.append( ((2*n-3)*A100223[-1]
      - 5*(n-3)*A100223[-2])//n )  # _Gennady Eremin_, Apr 24 2021

