# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A158354

from num2words import num2words
from itertools import count, islice
def vowels(n): return sum(1 for c in num2words(n) if c in "aeiouy")
def agen():
    n, adict = 1, dict()
    for k in count(1):
        v = vowels(k)
        if v not in adict: adict[v] = k
        while n in adict: yield adict[n]; n += 1
print(list(islice(agen(), 23))) # _Michael S. Branicky_, Aug 09 2022

