# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A158215

from __future__ import division
from itertools import combinations
from sympy import prime, isprime
def A158215(n):
    if n == 1:
        return 11
    if n == 2:
        return 0
    p2 = prime(n)//2
    l = p2
    while True:
        for i in combinations(range(l),l-p2):
            s = ['1']*l
            for x in i:
                s[x] = '0'
            s = ''.join(s)
            q = int(s+'1'+s[::-1])
            if isprime(q):
                return q
        l += 1 # _Chai Wah Wu_, Nov 05 2015

