# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A237017

from sympy import isprime, primerange
is_a237017 = lambda p: return all(isprime(q) for q in (p+8, 2*p+1, 2*p+9, 4*p+3, 4*p+11, 8*p+7, 8*p+15))
print(*[p for p in primerange(10**8) if is_a237017(p)], sep=', ')
# _David Radcliffe_, May 11 2025

