# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A032913

def A032913(n): return (int(bin(m:=n+1)[3:],6)<<1) + (6**(m.bit_length()-1)-1)//5 # _Chai Wah Wu_, Oct 13 2023

