# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A362398

 # uses generator in A336830
from itertools import count, islice
def agen(r=-1): yield from (r:=v for v in A336830() if v > r)
print(list(islice(agen(), 32)))

