# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A362850

 # uses imports, functions in A194943
from itertools import count, islice
def agen(r=-1): # generator of terms
    yield from (k for k in count(2) if (v:=A194943(k)) > r and (r:=v))
print(list(islice(agen(), 20))) # _Michael S. Branicky_, May 18 2023

