# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A259836

from __future__ import division
from gmpy2 import is_square
from sympy import divisors
A259836_list = []
for n in range(10000):
    m = n**3+(n+1)**3
    for x in divisors(m):
        x2 = x**2
        if x2 > m:
            break
        if x != (2*n+1) and m < x*x2 and is_square(12*m//x-3*x2):
            A259836_list.append(n)
            break # _Chai Wah Wu_, Jan 10 2016

