# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A014701

def a(n): return n.bit_count() + n.bit_length() - 2
print([a(n) for n in range(1, 87)]) # _Michael S. Branicky_, Mar 19 2026

