# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A332936

g=1
b=7
sg=0
sb=0
bl=[]
gl=[]
for int in range(1,20):
  sg=g*1+b*2
  sb=b*7+g*2
  g=sg
  b=sb
  gl.append(g)
  bl.append(b)
print(bl)

