# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A332598

from sympy import totient
def A332598(n): return 22*n-17 if n <= 2 else 4*(n-1)*(3*n-1) + 12*sum(totient(i)*(n+1-i)*i for i in range(2,n//2+1)) + 4*sum(totient(i)*(n+1-i)*(2*n+2-i) for i in range(n//2+1,n+1)) # _Chai Wah Wu_, Aug 16 2021

