# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A332867

def A332867(n):
    m, k = int(''.join(str(d) for d in range(1,n+1))), 1
    i = n+k
    i2, l = i % m, len(str(i))
    t = 10**l
    t2, r = t % m, i % m
    while r != 0:
        k += 1
        i += 1
        i2 = (i2+1) % m
        if i >= t:
            l += 1
            t *= 10
            t2 = (10*t2) % m
        r = (r*t2 + i2) % m
    return k # _Chai Wah Wu_, May 20 2020

