# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A332941

def A(ee):
    a=[1]
    print(1)
    n=1
    while n<=ee:
        i=1
        while i>0:
            ii=i
            iz=c=0
            while iz<=len(a):
                c=0
                if ii>2:
                    for j in range(2, int((ii)**0.5+1.5)):
                        if ii%j==0:
                            c=1
                            break
                if c==0 and ii>1:
                    break
                else:
                    iz += 1
                    ii=ii+a[n-iz]
            if c==1:
                n += 1
                a.append(i)
                print(i)
                break
            if i<4:
                i=4
            else:
                i += 1
    return a

