# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A332687

from sympy import primenu, primepi
def A332687(n):
    c, j = n-primenu(n), 1
    while j <= n:
        c += primepi(k:=n//j)*(-j+(j:=n//k+1))
    return c # _Chai Wah Wu_, Jan 29 2026

