# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A102082

from num2words import num2words
def a(n): return num2words(n).replace(" and", "").count(chr(96+n%26))
print([a(n) for n in range(87)]) # _Michael S. Branicky_, Jul 15 2022

