# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A380763

 A380763 = lambda n: (n := A053615(n))*(n+1)//2
def A380763(upto = 999): # generator of the sequence
    for m in range(0, 2*upto, 2):
        for x in range(m): yield (x := min(x, m-x))*(x+1)//2
list(A380763(upto=5))  # first 4 "peaks"
list(a for a,_ in zip(A380763(), range(99))) # first 99 terms

