# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A070871

def a002487(n): return n if n<2 else a002487(n/2) if n%2==0 else a002487((n - 1)/2) + a002487((n + 1)/2)
def a(n): return a002487(n)*a002487(n + 1) # _Indranil Ghosh_, Jun 08 2017
from functools import reduce
def A070871(n): return sum(reduce(lambda x,y:(x[0],x[0]+x[1]) if int(y) else (x[0]+x[1],x[1]),bin(n)[-1:2:-1],(1,0)))*sum(reduce(lambda x,y:(x[0],x[0]+x[1]) if int(y) else (x[0]+x[1],x[1]),bin(n+1)[-1:2:-1],(1,0))) # _Chai Wah Wu_, May 05 2023

