# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A189820

from gmpy2 import digits
def A189820(n):
    l = (s:=digits(n-2,3)).find('2')
    if l >= 0: s = s[:l]+'1'*(len(s)-l)
    m = (t:=digits(n-1,3)).find('2')
    if m >= 0: t = t[:m]+'1'*(len(t)-m)
    return 1+int(s,2)-int(t,2) # _Chai Wah Wu_, Dec 05 2024

