# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A189151

from itertools import count, islice
def A189151_gen(): # generator of terms
    return (n for k in count(0) for n in range(k**2+1,k*(k+1)))
A189151_list = list(islice(A189151_gen(),25)) # _Chai Wah Wu_, Jul 28 2022

