# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A050470

from math import prod
from sympy import factorint
def A050470(n): return prod((p**(e+1<<1)-(m:=(0,1,0,-1)[p&3]))//(p**2-m) for p, e in factorint(n).items()) # _Chai Wah Wu_, Jun 21 2024

