# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A050548

from itertools import accumulate
def f(an, _): return an*(an+1)//2
print(list(accumulate([7]*11, f))) # _Michael S. Branicky_, Jul 28 2021

