# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A050918

from sympy import isprime
def auptok(limit):
    return list(filter(isprime, (k*2**k-1 for k in range(1, limit+1))))
print(auptok(1000)) # _Michael S. Branicky_, Jul 23 2021

