# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A050231

def a(n, adict={0:0, 1:0, 2:1, 3:3}):
    if n in adict:
        return adict[n]
    adict[n]=3*a(n-1)-a(n-2)-a(n-3)-2*a(n-4)
    return adict[n] # _David Nacin_, Mar 07 2012

