# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A256437

A256437_list = [i for i in range(10**6) if str(i**2 + int(str(i)[::-1])**2) == str(i**2 + int(str(i)[::-1])**2)[::-1]] # _Chai Wah Wu_, Apr 09 2015

