# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A306323

# See A000002 for the definition of Kolakoski()
def a306323():
    last = count = 0
    for k in Kolakoski():
        if k is last:
            yield count
            count = 0
        count += 1
        last = k
from itertools import islice
print(*list(islice(a306323(), 108)), sep=', ')
# corrected by _David Radcliffe_, May 10 2025

