# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A306836

from itertools import accumulate, count, islice
def A306836_gen(): # generator of terms
    blist, a, b = (1,), 1, 1
    yield from blist
    for i in count(2):
        yield (blist := tuple(accumulate(reversed(blist),initial=b)))[-1]
        a, b = b, (b*(2*i+1)+(3*i-3)*a)//(i+2)
A306836_list = list(islice(A306836_gen(),40)) # _Chai Wah Wu_, Jun 12 2022

