# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A066829

from operator import ixor
from functools import reduce
from sympy import factorint
def A066829(n): return reduce(ixor, factorint(n).values(),0)&1 # _Chai Wah Wu_, Jan 01 2023

