# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A027663

from math import isqrt
def A027663(n): return (m:=isqrt(k:=n*10**10))+int((k-m*(m+1)<<2)>=1) # _Chai Wah Wu_, Jul 30 2022

