# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A381617

from mpmath import iv
zeta2 = iv.pi**2/6
def prob_count_diff(j, k, count):
    return  k/(zeta2*j*j) - count
def sample_zeta_distribution(num_coeffs):
    coeffs, unreached_val, counts = [], 1, {}
    for k in range(1, num_coeffs+1):
        prob_count_diffs = [prob_count_diff(i, k, counts.get(i, 0)) for i in range(1, unreached_val+1)]
        most_probable = prob_count_diffs.index(max(prob_count_diffs)) + 1
        unreached_val += most_probable == unreached_val
        coeffs.append(most_probable)
        counts[most_probable] = counts.get(most_probable, 0) + 1
    return coeffs
A381617 = sample_zeta_distribution(120)  # _Jwalin Bhatt_, Dec 18 2025

