# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A381126

from sympy import isprime, primerange, prime
def a(limit: int) -> list[int]:
    result: list[int] = []
    for p in primerange(2, limit):
        pth_prime = prime(p)
        rc_val = int(f"{pth_prime}{p}")
        if isprime(rc_val):
            result.append(rc_val)
    return result
print(a(1700))

