# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A381815

from sympy import isprime
from itertools import count
def a(n): return next(k for k in count(2) if isprime(k**(3*(2**n)) * 10 + 1))

