# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A381646

def A381646(n): return ((1<<n+2)+n*(n+3)+4<<n-3)-(n+3)*3**(n-1)<<1 if n>2 else 0 # _Chai Wah Wu_, Mar 15 2025

