# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A381246

import sys
import gmpy2
sys.set_int_max_str_digits(0)
def floorJuggler(n):
    a=n
    max=n
    while a > 1:
        b=0
        if a%2 == 0:
            b1=gmpy2.iroot(a,3)
            b=b1[0]
        else:
            b1=gmpy2.iroot(a**4,3)
            b=b1[0]
        a=b
        if a > max:
            max = a
    return max
maxcount=0
for i in range (1, 100):
    print (i, floorJuggler(i))

