# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A337769

from sympy import prime
def sum_p(m):
    sum1 = 0
    for i in range(1, m+1):
        sum1 += prime(i)
    return sum1
pi = 1
for n in range(1, 101):
    while sum_p(pi) <= n*n:
        pi += 1
    print(pi)

