# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A337447

from itertools import islice, accumulate
from operator import sub
def A337447_gen(): # generator of terms
    yield from (1,0)
    blist, alist = (1,0), (1,)
    while True:
        yield (blist := tuple(accumulate(reversed(blist),func=sub,initial=(alist := list(accumulate(alist, initial=alist[-1])))[-1])))[-1]
A337447_list = list(islice(A337447_gen(),30)) # _Chai Wah Wu_, Jun 11-12 2022

