# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A285729

from sympy import divisors, factorint
def a032742(n): return 1 if n==1 else max(divisors(n)[:-1])
def T(n, m): return ((n + m)**2 - n - 3*m + 2)/2
def P(n):
   f = factorint(n)
   return sorted([f[i] for i in f])
def a046523(n):
    x=1
    while True:
        if P(n) == P(x): return x
        else: x+=1
def a(n): return T(a032742(n), a046523(n)) # _Indranil Ghosh_, May 05 2017

