# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A285103

# uses [A000120]
l=[1]
for n in range(1, 101):
    x = l[n - 1]
    l.append(x^(2**n*x))
print([A000120(k) for k in l]) # _Indranil Ghosh_, Jun 28 2017

