# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A323724

 [int((1/2)*(-1 + n)**2*n - (-1 + n)*int(n/2) + 2*(int(n/2))**2) for n in range(0,50)]

