# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A323832

from re import split
def A321801(n):
    return int('0'+''.join(d for d in split('(0+)|(1+)|(2+)|(3+)|(4+)|(5+)|(6+)|(7+)|(8+)|(9+)',str(n)) if d != '' and d != None and len(d) == 1))
def f(n):
    x = 2*n
    y = A321801(x)
    while x != y:
        x, y = y, A321801(y)
    return x
def A323832(n):
    mset, m, c = set(), n, 0
    while True:
        if m == 1 or m == 0 or m == 5:
            return c
        m = f(m)
        if m in mset:
            return -1
        mset.add(m)
        c += 1 # _Chai Wah Wu_, Feb 04 2019, Feb 11 2019

