# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A164937

from sympy import isprime
from itertools import count, islice
def agen(): # generator of terms
    for d in count(3):
        ds = set()
        for end in "1379":
            ds.update(int(c*(d-1) + end) for c in "123456789" if c != end)
            for diff in "0123456789":
                if end == diff: continue
                cands = (end*i + diff + end*(d-1-i) for i in range(d-1))
                ds.update(int(t) for t in cands if t[0] != "0")
        yield from sorted(t for t in ds if isprime(t))
print(list(islice(agen(), 52))) # _Michael S. Branicky_, May 17 2022

