# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A374979

from functools import lru_cache
from sympy import divisor_sigma
def A374979(n):
    @lru_cache(maxsize=None)
    def g(x):
        f = factorint(x+1).items()
        return(5*prod((p**(3*(e+1))-1)//(p**3-1) for p,e in f)-(5+6*x)*prod((p**(e+1)-1)//(p-1) for p, e in f))//12
    return sum(g(i)*g(j)*g(n-3-i-j) for i in range(1,n-4) for j in range(1,n-i-3))

