# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A374070

from sympy import Matrix, composite
def A374070(n): return Matrix(n,n,[composite(abs(j-k)) if j!=k else 0 for j in range(n) for k in range(n)]).per() if n else 1 # _Chai Wah Wu_, Jul 01 2024

