# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A374989

from math import prod
from itertools import count, islice
from collections import Counter
from sympy import factorint
def A374989_gen(): # generator of terms
    c = Counter()
    for i in count(0):
        c += Counter(factorint(i))
        yield prod(p**(e>>1) for p, e in c.items() if e&1^1)
A374989_list = list(islice(A374989_gen(),30)) # _Chai Wah Wu_, Jul 27 2024

