# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A374559

from itertools import count, islice
from gmpy2 import digits
def A374559_gen(startvalue=1): # generator of terms >= startvalue
    return filter(lambda n: max(d:=digits(n,7))<='3' and not (d.count('1')%3 or (d.count('2')^d.count('3'))&1), count(max(startvalue,1)))
A374559_list = list(islice(A374559_gen(),10)) # _Chai Wah Wu_, Jul 13 2024

