# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A168612

from math import gcd
from itertools import count, islice
def agen(): # generator of terms
    an, alst = 1, []
    while True:
        yield an; alst.append(an); b = an.bit_length(); t = 1 << b
        for z in count(0):
            an = (t << z) + alst[-1]
            if all(gcd(an, ai) == 1 for ai in alst): break
print(list(islice(agen(), 25))) # _Michael S. Branicky_, Feb 07 2023

