# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A286147

def T(a, b): return ((a + b)**2 + 3*a + b)//2
def A(n, k): return T(n^k, k)
for n in range(21): print([A(n - k, k) for k in range(n + 1)]) # _Indranil Ghosh_, May 21 2017

