# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A286475

from sympy import divisors, primefactors
def a(n): return 1 if n==1 else 6*divisors(n)[-2] +(min(primefactors(n))%6) # _Indranil Ghosh_, May 12 2017

