# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A271986

from sympy.ntheory.factor_ import digits
def bump(n,b):
  s=digits(n,b)[1:]
  l=len(s)
  return sum(s[i]*(b+1)**bump(l-i-1,b) for i in range(l) if s[i])
def A271986(n):
  if n==3: return 0
  for i in range(2,12):
    n=bump(n,i)-1
  return n # _Pontus von Brömssen_, Sep 25 2020

