# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A271503

from itertools import count, islice
from math import prod
from sympy import divisors
def A271503_gen(): # generator of terms
    A271503_dict = {1:1}
    yield 1
    for n in count(2):
        yield (s:=prod(A271503_dict.get(d,1) for d in divisors(n,generator=True)))
        A271503_dict[s] = A271503_dict.get(s,1)*n
A271503_list = list(islice(A271503_gen(),40)) # _Chai Wah Wu_, Nov 17 2022

