# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A377704

from math import comb
from gmpy2 import fib2
def A377704(n): return comb(*(lambda x:(x[0]-2,x[1]-1))(fib2(n+2))) # _Chai Wah Wu_, Nov 22 2024

