# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A377886

from sympy import sieve
from sympy.ntheory import digits
def ok(n): return any(len(set(digits(n, p)[1:]))==1 for p in sieve.primerange(2, n-1))
print([k for k in range(253) if ok(k)]) # _Michael S. Branicky_, Nov 13 2024

