# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A377078

from math import gcd
from itertools import count, islice
def agen(): # generator of terms
    an2, an1, aset, m = 2, 3, {2, 3}, 4
    yield from [2, 3]
    while True:
        t = an2%an1
        an = next(k for k in count(m) if k not in aset and an1%k > 1 and gcd(k, t) > 1)
        yield an
        aset.add(an)
        while m in aset: m += 1
        an2, an1 = an1, an
print(list(islice(agen(), 90))) # _Michael S. Branicky_, Oct 15 2024

