# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A377306

from sympy import integer_nthroot
def A377306(n): return n+(m:=integer_nthroot(5*n,5)[0])-(30*n<=m*(m-1)*(m*(m*(3*((m<<1)+7))+31)+31))

