# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A377900

from sympy import isprime
from itertools import count, islice
def nextcomposite(n): return next(k for k in count(n+1) if not isprime(k))
def agen(): # generator of terms
    yield from [1, 1, 1]
    c, c2 = 4, 6
    for n in count(4):
        if n == c2: c, c2 = c2, nextcomposite(nextcomposite(c2))
        yield c2
print(list(islice(agen(), 70))) # _Michael S. Branicky_, Nov 29 2024

