# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A145388

from math import prod
from sympy import factorint
def A145388(n): return prod((p**e<<1)-1 for p,e in factorint(n).items()) # _Chai Wah Wu_, Feb 13 2025

