# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A145397

from math import comb
from sympy import integer_nthroot
def A145397(n): return n+(m:=integer_nthroot(6*n,3)[0])-(n+m<=comb(m+2,3)) # _Chai Wah Wu_, Oct 01 2024

