# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A078796

from math import isqrt
def A078796(n): return (n+(m:=isqrt(5*n**2))&-2)-m+1 # _Chai Wah Wu_, Aug 17 2022

