# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A078823

def a(n): return sum(set(((((2<<l)-1)<<i)&n)>>i for i in range(n.bit_length()) for l in range(n.bit_length()-i)))
print([a(n) for n in range(64)]) # _Michael S. Branicky_, Jul 28 2022

