# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A210482

from sympy import isprime, primerange
mul=1
for i in [1]+list(primerange(60)):
    mul*= i*i
    if isprime(mul+1):
        print(mul+1, end=', ')

