# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A210536

t=int((math.sqrt(8*n-7) - 1)/ 2)
i=n-t*(t+1)/2
j=(t*t+3*t+4)/2-n
result=3*i + (j-1) % 3 - 2

