# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A210698

from __future__ import division
def A210698(n):
    if n % 3 == 0:
        return 11*n**4//27
    elif n % 3 == 1:
        return (11*n**4 - 8*n**3 + 6*n**2 + 4*n + 14)//27
    else:
        return (11*n**4 - 16*n**3 + 24*n**2 + 32*n + 8)//27 # _Chai Wah Wu_, Nov 30 2016

