# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A210535

t=int((math.sqrt(8*n-7)-1)/2)
i=n-t*(t+1)/2
v=int((2*n+1-t*(t+1))/(t+3))
result=2*i-v*(4*i-2*t-3)

