# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A210497

from sympy import prime, nextprime
def A210497(n): return -(p:=prime(n))+(nextprime(p)<<1) # _Chai Wah Wu_, Oct 29 2024

