# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A354860

from fractions import Fraction
from sympy import prime, primerange
def a(n): return sum(Fraction(n-i, p) for i, p in enumerate(primerange(1, prime(n)+1))).denominator
print([a(n) for n in range(1, 21)]) # _Michael S. Branicky_, Jun 09 2022

