# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A354748

from sympy import isprime
def f(x): return 3*x + 2
def a(n):
    fn, c = f(2*n-1), 1
    while not isprime(fn): fn, c = f(fn), c+1
    return fn
print([a(n) for n in range(1, 54)]) # _Michael S. Branicky_, Jun 07 2022

