# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A354819

from sympy import factorint
def A354819(n): return int(n==1 or (len(f:=factorint(n))>1 and max(f.values())==1)) # _Chai Wah Wu_, Nov 08 2025

