# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A108276

from sympy import integer_log
def A108276(n):
    ptuple = (2, 3, 5, 7, 11, 13, 17, 19)
    def g(x, m): return sum(g(x//(ptuple[m]**i), m-1)for i in range(integer_log(x, ptuple[m])[0]+1)) if m else x.bit_length()
    return g(10**n,7) # _Chai Wah Wu_, Mar 16 2026

