# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A108967

print([ord(c.lower())-ord('a')+1 for c in "This finite sequence is obtained by replacing the letters you are reading now with their rank in the alphabet" if c.isalpha()]) # _Michael S. Branicky_, Dec 06 2025

