# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A108017

from num2words import num2words
from bisect import bisect, insort
from itertools import count, islice
def agen(): # generator of terms
    s = [""]
    for n in count(1):
        sn = "".join(c for c in num2words(n).replace(" and","") if c.isalpha())
        an = bisect(s, sn)
        insort(s, sn)
        yield an
print(list(islice(agen(), 83))) # _Michael S. Branicky_, Dec 28 2025

