# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A078782

from sympy import prime, composite
def A078782(n): return composite(prime(n)-1) # _Chai Wah Wu_, Nov 13 2024

