# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A078255

from itertools import count, islice
def c(n): return all((s:=str(n)).count(d)<=(len(s)-1)//10+1 for d in "0123456789")
def agen(): yield from filter(c, (k*k for k in count(0)))
print(list(islice(agen(), 50))) # _Michael S. Branicky_, Oct 29 2023

