# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A078971

from __future__ import division
A078971_list = []
for t in range(100):
    A078971_list.append((2**(2*t)-1)//3)
    for j in range(t):
        A078971_list.append((2**(2*t+1)+2**(2*j+1)-1)//3) # _Chai Wah Wu_, Mar 06 2016

