# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A056831

from math import lcm
from sympy import prime
def A056831(n): return lcm(*range(prime(n)+1,prime(n+1))) # _Chai Wah Wu_, Apr 16 2023

