# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A056849

def a(n): return pow(n, n, 10)
print([a(n) for n in range(1, 101)]) # _Michael S. Branicky_, Sep 13 2022

