# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A302187

from math import comb as binomial
def a(n):
    return sum(binomial(n, k)*binomial(k, k//2)*binomial(n-k, (n-k)//2)**2 for k in range(n+1))
print([a(n) for n in range(26)]) # _Mélika Tebni_, Nov 25 2024

