# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A028363

for n in range(8, 50, 8):
    product = 1
    for i in range(n//2 - 1):
        product *= 2**i + 1
    print(product, end=", ")
# _Nathan J. Russell_, Mar 01 2016

