# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A028459

# Number of perfect matchings in P_2 X C_7 X P_n, by cylindrical transfer matrix.
def A028459(n):
    P, C = 2, 7
    NV = P*C
    E = [(p*C+c, p*C+(c+1)%C) for p in range(P) for c in range(C)] + \
        [(c, C+c) for c in range(C)]
    def layer(inc):
        out = {}
        def rec(v, used, og):
            if v == NV:
                out[og] = out.get(og, 0) + 1; return
            if (used>>v)&1: rec(v+1, used, og); return
            if (inc>>v)&1:  rec(v+1, used|(1<<v), og); return
            rec(v+1, used|(1<<v), og|(1<<v))
            for a, b in E:
                w = b if a==v else a if b==v else -1
                if w>v and not (used>>w)&1 and not (inc>>w)&1:
                    rec(v+1, used|(1<<v)|(1<<w), og)
        rec(0, 0, 0)
        return out
    if n == 0: return 1
    vec = {0: 1}
    for _ in range(n):
        nv = {}
        for s, cnt in vec.items():
            for o, w in layer(s).items():
                nv[o] = nv.get(o, 0) + cnt*w
        vec = nv
    return vec.get(0, 0)
print([A028459(n) for n in range(14)])
# _Steven Kotlarz_, May 30 2026

