# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A386743

def A386743(n):
    a, b, m, k = 0, 1, n*((n<<1)|1), (n<<1)|1
    while a<m or a%k:
        a, b = b, a+b
    return a # _Chai Wah Wu_, Aug 11 2025

