# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A284275

from sympy import primepi
def a(n): return primepi(2**n - 1) - primepi(n) # _Indranil Ghosh_, Mar 26 2017

