# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A284648

from fractions import Fraction
from sympy import harmonic
def A284648(n):
    c, j, v = Fraction(0), 1, 0
    while j <= n:
        k = n//j
        m = n//k
        c += k*(-v+(v:=harmonic(m)))
        j = m+1
    return c.p # _Chai Wah Wu_, May 19 2026

