# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A347325

def A347325(n):
    a = [i for i in range(1,n+1)]
    while len(a) != 1:
        del a[:len(a)+1:2]
        a.reverse()
    return a[-1] # _Marc Kouyoumdjian_, Dec 15 2021
def a(n):
    return 1 if n <= 1 else 2 * (n // 2 + 1 - a(n // 2))
# See Zhang's solution. - _Zirui Wang_, Jan 02 2022
from math import log, log2
def A347325(n):
    return (-2) ** int(log2(n)) // 3 + 1 + (n & int('a' * int(log(n, 16) + 1), 16))
# _Zirui Wang_, Jan 03 2022

