# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A347603

 from sympy import divisor_count as tau, divisor_sigma as sigma
print([k for k in range(2, 10**6) if tau(k) == 2*tau(k-1) and sigma(k) == sigma(k-1)]) # _Karl-Heinz Hofmann_, Jan 15 2022

