# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A112047

from sympy import jacobi_symbol as J
def a112046(n):
    i=1
    while True:
        if J(i, 2*n + 1)!=1: return i
        else: i+=1
print([a112046(2*n - 1) for n in range(1, 103)]) # _Indranil Ghosh_, May 11 2017

