# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A112049

from sympy import jacobi_symbol as J, isprime, primepi
def a049084(n):
    return primepi(n) if isprime(n) else 0
def a112046(n):
    i=1
    while True:
        if J(i, 2*n + 1)!=1: return i
        else: i+=1
def a(n): return a049084(a112046(n))
print([a(n) for n in range(1, 103)]) # _Indranil Ghosh_, May 11 2017

