# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A363406

from itertools import islice
def agen():  # generator of terms
    L = list(range(1, 10))
    while True:
        j = L[0]
        k = L[j]
        yield j + k  # an
        L.remove(j)
        L.remove(k)
        L.extend(list(range(L[-1]+1, L[-1]+7)))
print(list(islice(agen(), 62))) # _Michael S. Branicky_, Dec 20 2024

