# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A363070

def aupto(n): # produces n terms, indices 0..n-1
    F1, F, a = [0], [0, 1], [0, 1]
    while len(F) < n:
        F1, F = F, F+F1
    [a.append(a[-2]+a[-1]+F[i]+F[i-1]) for i in range(2, n)]
    return a
print(aupto(42)) # _Michael S. Branicky_, May 17 2023

