# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A363654

from itertools import count, islice
def agen(): # generator of terms
    a, indexes = [1], {1: 0}
    yield a[-1]
    for i in count(0):
        num = 1
        while True:
            if num in indexes:
                if (len(a) - indexes[num]) == (a[i]+1):
                    an = num; indexes[an] = len(a); a.append(an); yield an
                    break
                else:
                    num += 1
            else:
                an = max(a)+1; indexes[an] = len(a); a.append(an); yield an
                num = 1
print(list(islice(agen(), 100))) # _Gavin Lupo_ and _Michael S. Branicky_, Jun 13 2023

