# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A363421

from sympy import divisor_count
def A363421(n): return n**2-2*(n-1)*divisor_count(n)-1 if n else 1 # _Chai Wah Wu_, Jun 28 2023

