# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A363069

from networkx import empty_graph, find_cliques
from itertools import combinations
from sympy.ntheory.primetest import is_square
def A363069(n):
    if n == 0: return 0
    v = [d for d in range(1,n+1) if not is_square(d<<1)]
    G = empty_graph(v)
    G.add_edges_from((a,b) for a, b in combinations(v,2) if not is_square(a+b))
    return max(len(c) for c in find_cliques(G)) # _Chai Wah Wu_, Jan 09 2026

