# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A353906

def A353906(n): return sum((-1 if i % 2 else 1)*int(j) for i, j in enumerate(str(n)[::-1]))**len(str(n)) # _Chai Wah Wu_, May 11 2022

