# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A353730

from itertools import count, islice
from math import gcd
from collections import deque
def A353730_gen(): # generator of terms
    aset, aqueue, c, f = {2}, deque([2]), 1, True
    yield 2
    while True:
        for m in count(c):
            if m not in aset and all(gcd(m,a) == 1 for a in aqueue):
                yield m
                aset.add(m)
                aqueue.append(m)
                if f: aqueue.popleft()
                f = not f
                while c in aset:
                    c += 1
                break
A353730_list = list(islice(A353730_gen(),30)) # _Chai Wah Wu_, May 18-19 2022

