# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A353182

import math
def a(n):
  return (sum(math.comb(n,i)*9**(n-i+1) for i in range(n//2+1,n+1)))
print([a(n) for n in range(1, 31)])

