# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A353238

from sympy import mobius, integer_nthroot
from oeis_sequences.OEISsequences import bisection
def A353238(n):
    def f(x): return int(n+x+sum(mobius(k)*(integer_nthroot(x,k)[0]//3) for k in range(2,x.bit_length())))
    return bisection(f,n,n) # _Chai Wah Wu_, Sep 18 2025

