# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A391269

from sympy import factorint
from functools import cache
@cache
def a(n): return 0 if n == 3 else 1 + a(max(factorint(2*n+1)))
print([a(n) for n in range(1, 84)]) # _Michael S. Branicky_, Dec 13 2025

