# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A391450

import math
def a(n):
    if n <= 1: return 1
    term1 = sum(2 * math.comb(2*m-1, m-1) * math.comb(n-2*m-1, m-1) for m in range(1, n//3 + 1))
    term2 = sum(math.comb(2*m, m) * math.comb(n-2*m-2, m-1) for m in range(1, (n-1)//3 + 1))
    term3 = sum(math.comb(2*m, m-1) * math.comb(n-2*m-2, m) for m in range(1, (n-2)//3 + 1))
    return term1 + term2 + term3
result_list = [a(n) for n in range(100)]
print(result_list)

