# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A391107

from math import prod
from itertools import count, islice
from sympy import factorint
def A391107_gen(startvalue=1): # generator of terms >= startvalue
    for k in count(max(startvalue,1)):
        if prod((e<<1)|1 for p, e in factorint(k).items() if p&3==1)>=9:
            yield k
A391107_list = list(islice(A391107_gen(),58)) # _Chai Wah Wu_, Dec 01 2025

