# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A391616

from sympy import prime
def generate_indices(N):
    # Generates the first N terms of the sequence.
    if N == 0:
        return []
    indices = [1]
    current_index = 1 # i_1 = 1
    for _ in range(N - 1):
        prime_value = prime(current_index)
        next_index = current_index + prime_value + 1
        indices.append(next_index)
        current_index = next_index
    return indices

