# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A391321

from sympy import isprime
A = []
p = 3
while len(A) < 60:
    if isprime(p) and isprime(p+2) and isprime(3*p+2):
        A.append(3*p+2)
    p += 2
print(A)

