# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A391321

from itertools import islice
from sympy import isprime, nextprime
def agen(): # generator of terms
    p, q = 3, 5
    while True:
        if q-p == 2 and isprime(r:=3*p+2): yield r
        p, q = q, nextprime(q)
print(list(islice(agen(), 46))) # _Michael S. Branicky_, Dec 07 2025

