# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A126120

from math import comb
def A126120(n): return 0 if n&1 else comb(n,m:=n>>1)//(m+1) # _Chai Wah Wu_, Apr 22 2024

