# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A126832

from sympy import divisor_sigma
def A126832(n): return n*divisor_sigma(n)%5 # _Chai Wah Wu_, Aug 24 2023

