# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A152086

from math import comb
def A152086(n): return ((n+1<<n-2)-(((n<<1)-1)*comb(n-1,n-1>>1)>>1 if n&1 else (n-1)*comb(n-2,n-2>>1)<<1)) # _Chai Wah Wu_, Oct 28 2024

