# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A033845

from sympy import integer_log
def A033845(n):
    def bisection(f,kmin=0,kmax=1):
        while f(kmax) > kmax: kmax <<= 1
        while kmax-kmin > 1:
            kmid = kmax+kmin>>1
            if f(kmid) <= kmid:
                kmax = kmid
            else:
                kmin = kmid
        return kmax
    def f(x): return n+x-sum((x//3**i).bit_length() for i in range(integer_log(x,3)[0]+1))
    return 6*bisection(f,n,n) # _Chai Wah Wu_, Sep 15 2024
 # faster for initial segment of sequence
import heapq
from itertools import islice
def A033845gen(): # generator of terms
    v, oldv, h, psmooth_primes, = 1, 0, [1], [2, 3]
    while True:
        v = heapq.heappop(h)
        if v != oldv:
            yield 6*v
            oldv = v
            for p in psmooth_primes:
                heapq.heappush(h, v*p)
print(list(islice(A033845gen(), 50))) # _Michael S. Branicky_, Sep 18 2024

