# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A062059

def a(n):
    l=[n, ]
    while True:
        if n%2==0: n//=2
        else: n = 3*n + 1
        if n not in l:
            l+=[n, ]
            if n<2: break
        else: break
    return len([i for i in l if i%2])
[n for n in range(30, 1101) if a(n)==9] # _Indranil Ghosh_, Apr 14 2017

