# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A319584

def nextpal(n, base): # m is the first palindrome successor of n in base base
    m, pl = n+1, 0
    while m > 0:
        m, pl = m//base, pl+1
    if n+1 == base**pl:
        pl = pl+1
    n = n//(base**(pl//2))+1
    m, n = n, n//(base**(pl%2))
    while n > 0:
        m, n = m*base+n%base, n//base
    return m
def rev(n, b):
    m = 0
    while n > 0:
        n, m = n//b, m*b+n%b
    return m
n, a = 1, 0
while n <= 100:
    if a == rev(a, 4) == rev(a, 2):
        print(a)
        n += 1
    a = nextpal(a, 8) # _A.H.M. Smeets_, Jun 08 2019

