# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A390396

from itertools import combinations
def generate_sequence(n_terms):
    sequence = [1]
    while len(sequence) < n_terms:
        sums = set()
        prods = set()
        powers = set()
        for a, b in combinations(sequence, 2):
            sums.add(a + b)
            prods.add(a * b)
            try:
                powers.add(a ** b)
            except OverflowError:
                pass
            try:
                powers.add(b ** a)
            except OverflowError:
                pass
        forbidden = sums.union(prods).union(powers)
        candidate = 1
        while candidate in sequence or candidate in forbidden:
            candidate += 1
        sequence.append(candidate)
    return sequence
seq = generate_sequence(15)

