# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A390629

from math import gcd
from itertools import count, islice
def c(i): return gcd(i, int(str(i)[::-1])) > 1
def A390629_gen(startn=1, startk=1): # generator of terms
    adict, n, r = dict(), startn, 1
    for k in count(startk):
        if c(k): r += 1
        else:
            for v in range(r-1, 0, -1):
                if v not in adict:
                    adict[v] = k - v
            while n in adict: yield adict[n]; n += 1
            r = 1
print(list(islice(A390629_gen(), 17))) # _Michael S. Branicky_, Nov 14 2025

