# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A390504

from functools import cache
@cache
def okb(s): return s == "" or any(okb(s[:i]+s[j:]) for i in range(len(s)-1) for j in range(i+2,len(s)+1) if s[i:j] == s[i:j][::-1])
def ok(n): return okb(bin(n)[2:])
print([k for k in range(100) if ok(k)]) # _Michael S. Branicky_, Mar 07 2026

