# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A390530

from math import comb
def a(n): return sum((2**(n-k)+1)*2**(n-k-1)*comb(n+3, n-k)*(-1)**k for k in range(n)) + (-1)**n
print([a(n) for n in range(24)]) # _Michael S. Branicky_, Nov 15 2025

