# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A390813

def a(n):
    def recurse(k, b, w):
        if k > n: return 0
        s = recurse(k+1, b, w)
        b += (1<<(k**2))
        if not w & (b<<(k**2)): s = max(s, 1+recurse(k+1, b, w+(b<<(k**2))))
        return s
    return recurse(1, 0, 0)
print([a(n) for n in range(1, 26)]) # _Michael S. Branicky_, Nov 20 2025

