# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A390599

from sympy import divisors
from functools import cmp_to_key
def c(x, y): return -1 if x+y < y+x else int(x+y > y+x)
def a(n): return int("".join(sorted(list(map(str, divisors(n))), key=cmp_to_key(c))))
print([a(n) for n in range(1, 39)]) # _Michael S. Branicky_, Nov 12 2025

