# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A174060

from math import isqrt
def A174060(n): return ((m:=isqrt(n+1))*(6*m*(n+1) - (m+1)*(3*m**2+m-1)))//6
# _Karl-Heinz Hofmann_, Jun 15 2023

