# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A174967

from sympy import primefactors
def a(n):
  k = 1
  while len(primefactors(k**2 + k + 1)) != n: k += 1
  return k**2 + k + 1
print([a(n) for n in range(1, 8)]) # _Michael S. Branicky_, Mar 21 2021

