# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A174973

from sympy import divisors
def ok(n):
    d = divisors(n)
    return all(d[i]/d[i-1] <= 2 for i in range(1, len(d)))
print(list(filter(ok, range(1, 257)))) # _Michael S. Branicky_, Jun 22 2021

