# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A396948

def ok(m):
    if m < 10: return False
    q, r = divmod(m, 10)
    return (q*100+r)%m == 0
print([m for m in range(600) if ok(m)]) # _Michael S. Branicky_, Jun 11 2026

