# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A396727

from fractions import Fraction as frac
from math import comb
A396727 = lambda n: sum(comb(n, k) * frac((-1)**k,frac(n - 1, n)**k - 1) for k in range(1, n + 1)).numerator
print(list(map(A396727,range(20))))

