# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A396087

# Prints terms to a(30)
from sympy import primefactors, primepi
M = [0] * 29
iota_m, iota_mp1, iota_mp2, iota_mp3 = 0, 1, 2, 1
for m in range(1, 612_360+1): # Range 1 to A003033(30)
    iota_mp4 = int(primepi(primefactors(m+4)[-1]))
    iota = max(iota_m, iota_mp1, iota_mp2, iota_mp3, iota_mp4)
    if (iota - 2) < 29: M[iota-2] = m
    iota_m, iota_mp1, iota_mp2, iota_mp3 = iota_mp1, iota_mp2, iota_mp3, iota_mp4
for i in range(1, 29):
    if M[i] < M[i-1]: M[i] = M[i-1]
print(M[1:])

