# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A396470

from collections import Counter
from sympy import prime, factorint
def A396470(n):
    c, p = Counter(), prime(n)
    for i in range(p-n+1,p):
        c += factorint(i)
    for i in range(2,n+1):
        c -= factorint(i)
    return sum(c)+p # _Chai Wah Wu_, May 27 2026

