# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A396989

from itertools import product
from collections import deque
from bisect import insort
def tree_from_prufer(n, code):
    deg = [1] * n
    for x in code:
        deg[x] += 1
    leaves = [i for i in range(n) if deg[i] == 1]
    leaves.sort()
    adj = [[] for _ in range(n)]
    for x in code:
        y = leaves.pop(0)
        adj[x].append(y)
        adj[y].append(x)
        deg[x] -= 1
        deg[y] -= 1
        if deg[x] == 1:
            insort(leaves, x)
    if n >= 2:
        x, y = leaves
        adj[x].append(y)
        adj[y].append(x)
    return adj
def farthest(adj, s):
    q = deque([s])
    dist = [-1] * len(adj)
    dist[s] = 0
    while q:
        v = q.popleft()
        for w in adj[v]:
            if dist[w] < 0:
                dist[w] = dist[v] + 1
                q.append(w)
    v = max(range(len(adj)), key=lambda i: dist[i])
    return v, dist[v]
def diameter(adj):
    v, _ = farthest(adj, 0)
    _, d = farthest(adj, v)
    return d
def A(n):
    ans = 0
    for code in product(range(n), repeat=n-2):
        adj = tree_from_prufer(n, code)
        leaves = sum(1 for v in range(n) if len(adj[v]) == 1)
        if leaves == diameter(adj):
            ans += 1
    return ans
print([A(n) for n in range(2, 9)])

