# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A241917

from sympy import primefactors, primepi
def a061395(n): return 0 if n==1 else primepi(primefactors(n)[-1])
def a052126(n): return 1 if n==1 else n/primefactors(n)[-1]
def a(n): return 0 if n==1 else a061395(n) - a061395(a052126(n)) # _Indranil Ghosh_, May 19 2017

