# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A251554

from math import gcd
A251554_list, l1, l2, s, b = [1,2,5], 5, 2, 3, {5}
for _ in range(10**4):
    i = s
    while True:
        if not i in b and gcd(i,l1) == 1 and gcd(i,l2) > 1:
            A251554_list.append(i)
            l2, l1 = l1, i
            b.add(i)
            while s in b:
                b.remove(s)
                s += 1
            break
        i += 1 # _Chai Wah Wu_, Dec 21 2014

