# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A026136

import math
A026136 ={1:1}
for n in range(2,3000):
    h=math.floor(n/2)
    L=n-h
    R=n+h
    if not L in A026136 :
        A026136[L]=n
    else :
        A026136[R]=n
for n in range(1,2000):
    if n in A026136:
       print(str(n) + " "+ str(A026136[n]))
    else:
       break # _R. J. Mathar_, Aug 26 2019

