# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A026356

from math import isqrt
def A026356(n): return (n+1+isqrt(5*(n-1)**2)>>1)+n # _Chai Wah Wu_, Aug 11 2022

