# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A096488

from sympy.ntheory.continued_fraction import continued_fraction
from sympy import sqrt
def A096488(n): return len(set(continued_fraction(sqrt((10**n-1)//9))[-1])) # _Chai Wah Wu_, Mar 30 2021

