# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A096381

from itertools import islice
from collections import deque
def agen(): # generator of terms
    a = deque([2, 7])
    while True:
        a.extend(list(map(int, str(a[0]*a[1]))))
        yield a.popleft()
print(list(islice(agen(), 105))) # _Michael S. Branicky_, Aug 18 2025

