# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A005252

from sympy import fibonacci
def A005252(n): return fibonacci(n+1)+(1,1,0,-1,-1,0)[n%6]>>1 # _Chai Wah Wu_, Jun 10 2026

