# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A356177

# faster version based on Comments
from itertools import count, islice, product
def odgen(d): yield from [1, 3, 5, 7, 9] if d == 1 else sorted(int(f+"".join(p)+o+"".join(p[::-1])+f) for o in "13579" for f in o + "2468" for p in product(o+"02468", repeat=d//2-1))
def evgen(d): yield from (int(f+"".join(p)+"".join(p[::-1])+f) for f in "2468" for p in product("02468", repeat=d//2-1))
def A356177gen():
    for d in count(1, step=2): yield from odgen(d); yield from evgen(d+1)
print(list(islice(A356177gen(), 55))) # _Michael S. Branicky_, Jul 30 2022

