# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A356182

from math import isqrt
def A356182(n): return isqrt(3*((k:=n<<1)+isqrt(k*n))**2) # _Chai Wah Wu_, Sep 05 2022

