# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A052091

from sympy import isprime
A052091_list, p = [2], 2
for _ in range(30):
    m, ps = 1, str(p)
    s = int('1'+ps+'1')
    while not isprime(s):
        m += 1
        ms = str(m)
        if ms[0] in '268':
            ms = str(int(ms[0])+1) + '0'*(len(ms)-1)
            m = int(ms)
        if ms[0] in '45':
            ms = '7' + '0'*(len(ms)-1)
            m = int(ms)
        s = int(ms+ps+ms[::-1])
    p = s
    A052091_list.append(m) # _Chai Wah Wu_, Dec 02 2015

