# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A052055

from sympy import E, S
digits = 1000
pi, e = str(S.Pi.n(digits+3)), str(E.n(digits+3))
print([k for k in range(2, digits+1) if pi[k] == e[k]]) # _Michael S. Branicky_, Apr 29 2023

