# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A052059

def ispal(s): return s == s[::-1]
def longestpalss(n):
    s = str(n)
    for l in range(len(s), 0, -1):
        for offset in range(len(s)-l+1):
            if s[offset] != '0' and ispal(s[offset:offset+l]):
                return l
def a(n):
    k, pow2 = 0, 1
    while longestpalss(pow2) != n: k += 1; pow2 <<= 1
    return k
print([a(n) for n in range(1, 11)]) # _Michael S. Branicky_, Nov 12 2021

