# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A052405

from gmpy2 import digits
def A052405(n): return int(digits(n-1,9).translate(str.maketrans('345678','456789'))) # _Chai Wah Wu_, Jun 28 2025

