# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A122840

def A122840(n): return len(s:=str(n))-len(s.rstrip('0')) # _Chai Wah Wu_, Jul 06 2022

