# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A080368

from sympy import factorint, prime, primepi, isprime, primefactors
def a049084(n): return primepi(n)*(1*isprime(n))
def a055396(n): return 0 if n==1 else a049084(min(primefactors(n)))
def a028234(n):
    f = factorint(n)
    return 1 if n==1 else n/(min(f)**f[min(f)])
def a067029(n):
    f=factorint(n)
    return 0 if n==1 else f[min(f)]
def a277697(n): return 0 if n==1 else a055396(n) if a067029(n)==1 else a277697(a028234(n))
def a(n): return 0 if a277697(n)==0 else prime(a277697(n)) # _Indranil Ghosh_, May 16 2017

