# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A080408

from itertools import count, islice, accumulate
def A080408_gen(): # generator of terms
    blist = tuple()
    for n in count(1):
        yield (blist := tuple(accumulate(reversed(blist),initial=2 if n == 1 else 1 if n % 3 else n//3<<1)))[-1]
A080408_list = list(islice(A080408_gen(),25)) # _Chai Wah Wu_, Jul 27 2022

