# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A080471

def dmo(n, t):
    if t < n: return False
    while n and t:
        if n%10 == t%10:
            n //= 10
        t //= 10
    return n == 0
def fibo(f=1, g=2):
    while True: yield f; f, g = g, f+g
def a(n):
    return next(f for f in fibo() if dmo(n, f))
print([a(n) for n in range(1, 77)]) # _Michael S. Branicky_, Jan 21 2023

