# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A080259

from itertools import count, islice
from sympy import primepi, primefactors
def A080259_gen(startvalue=2): # generator of terms >= startvalue
    for k in count(max(startvalue,2)):
        p = list(map(primepi,primefactors(k)))
        if not(min(p)==1 and max(p)==len(p)):
            yield k
A080259_list = list(islice(A080259_gen(),40)) # _Chai Wah Wu_, Aug 07 2025

