# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A189409

from functools import reduce
import numpy as np
def factors(n):
    return reduce(list.__add__, ([i, n//i] for i in range(1, int(n**0.5) + 1) if n % i == 0))
mul = 1
for i in range(1, 20):
    if len(factors(i))<3:
        mul *= i*i
        print(mul+1, factors(mul+1))
# _Abhiram R Devesh_, Jan 23 2013

