# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A189822

from gmpy2 import digits
def A189822(n):
    def f(x):
        l = (s:=digits(x-1,3)).find('2')
        if l >= 0: s = s[:l]+'1'*(len(s)-l)
        return n+1+int(s,2)
    m, k = n, f(n)
    while m != k: m, k = k, f(k)
    return m # _Chai Wah Wu_, Dec 05 2024

