# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A329179

from sympy.ntheory.primetest import is_square
def ssd(n): return sum(int(d)**2 for d in str(n))
def ok(n): return is_square(n + ssd(n))
def aupto(limit): return [m for m in range(limit+1) if ok(m)]
print(aupto(4000)) # _Michael S. Branicky_, Jan 30 2021

