# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A137066

# uses auptod in A137110
print(auptod(16, only="2345")) # _Michael S. Branicky_, May 25 2021

