# This file is auto-generated from OEIS data.
# Please do not edit this file directly.
# OEIS sequence: A137812

from sympy import isprime
def agen():
    primes = [2, 3, 5, 7]
    while len(primes) > 0:
        yield from primes
        cands = set(int(d+str(p)) for p in primes for d in "123456789")
        cands |= set(int(str(p)+d) for p in primes for d in "1379")
        primes = sorted(c for c in cands if isprime(c))
afull = [an for an in agen()]
print(afull[:60]) # _Michael S. Branicky_, Aug 04 2022

